In [1]:
# =============================================================================
# MODEL 5 - STEP 1
# CLINICAL DECISION SUPPORT + REPORTING SYSTEM
# FRESH PROJECT INITIALIZATION
# =============================================================================

import os
import json
import shutil
import platform
import sys
from pathlib import Path
from datetime import datetime

print("=" * 80)
print("MODEL 5 - STEP 1")
print("CLINICAL DECISION SUPPORT + REPORTING SYSTEM")
print("FRESH PROJECT INITIALIZATION")
print("=" * 80)

# =============================================================================
# 1. MOUNT GOOGLE DRIVE
# =============================================================================

from google.colab import drive

drive.mount("/content/drive")

print("✅ Google Drive mounted")

# =============================================================================
# 2. PROJECT ROOTS
# =============================================================================

COLAB_ROOT = Path("/content/Model5")
DRIVE_ROOT = Path("/content/drive/MyDrive/Model5")

# Raw / temporary data stays in Colab
RAW_ROOT = COLAB_ROOT / "raw"
TEMP_ROOT = COLAB_ROOT / "temp"
CACHE_ROOT = COLAB_ROOT / "cache"

# Persistent compact data stays in Drive
DATA_ROOT = DRIVE_ROOT / "data"
CLINICAL_ROOT = DATA_ROOT / "clinical"
PROCESSED_ROOT = DATA_ROOT / "processed"

MODELS_ROOT = DRIVE_ROOT / "models"
RESULTS_ROOT = DRIVE_ROOT / "results"
REPORTS_ROOT = DRIVE_ROOT / "reports"
AUDIT_ROOT = DRIVE_ROOT / "audit"
KNOWLEDGE_ROOT = DRIVE_ROOT / "knowledge"
EXPORT_ROOT = DRIVE_ROOT / "exports"
CONFIG_ROOT = DRIVE_ROOT / "config"

ALL_DIRS = [
    COLAB_ROOT,
    RAW_ROOT,
    TEMP_ROOT,
    CACHE_ROOT,

    DRIVE_ROOT,
    DATA_ROOT,
    CLINICAL_ROOT,
    PROCESSED_ROOT,

    MODELS_ROOT,
    RESULTS_ROOT,
    REPORTS_ROOT,
    AUDIT_ROOT,
    KNOWLEDGE_ROOT,
    EXPORT_ROOT,
    CONFIG_ROOT,
]

for directory in ALL_DIRS:
    directory.mkdir(parents=True, exist_ok=True)

print()
print("=" * 80)
print("PROJECT DIRECTORIES")
print("=" * 80)

print(f"Colab root       : {COLAB_ROOT}")
print(f"Raw data         : {RAW_ROOT}")
print(f"Temporary data   : {TEMP_ROOT}")
print(f"Drive root       : {DRIVE_ROOT}")
print(f"Clinical data    : {CLINICAL_ROOT}")
print(f"Processed data   : {PROCESSED_ROOT}")
print(f"Models           : {MODELS_ROOT}")
print(f"Results          : {RESULTS_ROOT}")
print(f"Reports          : {REPORTS_ROOT}")
print(f"Audit            : {AUDIT_ROOT}")
print(f"Knowledge        : {KNOWLEDGE_ROOT}")
print(f"Exports          : {EXPORT_ROOT}")

# =============================================================================
# 3. STORAGE CHECK
# =============================================================================

def get_storage(path):
    usage = shutil.disk_usage(path)

    return {
        "total_gb": usage.total / (1024 ** 3),
        "used_gb": usage.used / (1024 ** 3),
        "free_gb": usage.free / (1024 ** 3)
    }

colab_storage = get_storage("/content")
drive_storage = get_storage("/content/drive")

print()
print("=" * 80)
print("STORAGE CHECK")
print("=" * 80)

print()
print("COLAB")
print("------")
print(f"Total : {colab_storage['total_gb']:.2f} GB")
print(f"Used  : {colab_storage['used_gb']:.2f} GB")
print(f"Free  : {colab_storage['free_gb']:.2f} GB")

print()
print("GOOGLE DRIVE")
print("------------")
print(f"Total : {drive_storage['total_gb']:.2f} GB")
print(f"Used  : {drive_storage['used_gb']:.2f} GB")
print(f"Free  : {drive_storage['free_gb']:.2f} GB")

if colab_storage["free_gb"] < 20:
    raise RuntimeError(
        f"Colab free storage is only {colab_storage['free_gb']:.2f} GB."
    )

if drive_storage["free_gb"] < 3:
    raise RuntimeError(
        f"Drive free storage is only {drive_storage['free_gb']:.2f} GB."
    )

print()
print("✅ STORAGE SAFETY CHECK PASSED")

# =============================================================================
# 4. GPU CHECK
# =============================================================================

print()
print("=" * 80)
print("GPU CHECK")
print("=" * 80)

gpu_available = False
gpu_name = None

try:
    import tensorflow as tf

    gpus = tf.config.list_physical_devices("GPU")

    if gpus:
        gpu_available = True
        gpu_name = str(gpus[0])

        print("✅ GPU AVAILABLE")

        for gpu in gpus:
            print(" -", gpu)

    else:
        print("⚠️ NO GPU DETECTED")

except Exception as e:
    print("⚠️ TensorFlow GPU check failed")
    print(str(e)[:1000])

# =============================================================================
# 5. PYTHON / SYSTEM INFORMATION
# =============================================================================

print()
print("=" * 80)
print("SYSTEM INFORMATION")
print("=" * 80)

print()
print("Python:")
print(sys.version)

print()
print("Platform:")
print(platform.platform())

# =============================================================================
# 6. MODEL 5 ARCHITECTURE DEFINITION
# =============================================================================

architecture = {

    "model_name": "Model5",

    "purpose": (
        "Clinical decision support and structured medical reporting "
        "research prototype"
    ),

    "upstream_models": {

        "model3b": {
            "role": "tumor classification",
            "expected_outputs": [
                "tumor_type",
                "classification_confidence"
            ]
        },

        "model4a": {
            "role": "tumor segmentation and measurement",
            "expected_outputs": [
                "tumor_detected",
                "tumor_area_pixels",
                "tumor_area_percent",
                "tumor_width_pixels",
                "tumor_height_pixels",
                "bounding_box",
                "centroid",
                "boundary_pixels"
            ]
        }
    },

    "model5": {
        "role": "clinical decision support",
        "candidate_outputs": [
            "recommendation_category",
            "recommended_specialist",
            "recommended_next_step",
            "follow_up_category"
        ],

        "specific_prescription": False,

        "drug_dosage_prediction": False,

        "drug_frequency_prediction": False,

        "drug_duration_prediction": False
    },

    "gemini": {
        "role": "structured report generation",
        "autonomous_diagnosis": False,
        "autonomous_prescription": False
    }
}

# =============================================================================
# 7. DATASET POLICY
# =============================================================================

dataset_policy = {

    "raw_data_location": str(RAW_ROOT),

    "processed_data_location": str(PROCESSED_ROOT),

    "clinical_data_location": str(CLINICAL_ROOT),

    "drive_raw_mri_storage": False,

    "download_policy": [
        "Verify official dataset source first.",
        "Inspect metadata before downloading large datasets.",
        "Download only datasets that contribute to the final system.",
        "Keep large raw MRI archives in Colab.",
        "Store compact clinical tables in Drive.",
        "Do not fabricate clinical or treatment labels.",
        "Do not infer prescription labels from tumor type.",
        "Do not infer treatment labels from tumor size."
    ]
}

# =============================================================================
# 8. SAFETY POLICY
# =============================================================================

safety_policy = {

    "system_type": "research_prototype",

    "not_a_diagnostic_device": True,

    "not_an_autonomous_prescriber": True,

    "human_clinician_required": True,

    "missing_information_policy": (
        "Never invent patient information. "
        "Missing values must be explicitly represented as unavailable."
    ),

    "low_confidence_policy": (
        "Low-confidence upstream predictions must be surfaced "
        "rather than silently converted into confident recommendations."
    ),

    "recommendation_policy": (
        "Recommendations must be grounded in validated clinical evidence "
        "and rules available to the system."
    ),

    "gemini_policy": (
        "Gemini receives structured validated information and generates "
        "the report. It does not independently determine a diagnosis "
        "or prescription."
    )
}

# =============================================================================
# 9. FEATURE SCHEMA
# =============================================================================

feature_schema = {

    "upstream_model_features": [

        "tumor_type",
        "classification_confidence",

        "tumor_detected",
        "tumor_area_pixels",
        "tumor_area_percent",

        "tumor_width_pixels",
        "tumor_height_pixels",

        "bounding_box",
        "centroid",
        "boundary_pixels"
    ],

    "patient_features": [

        "age",
        "sex",
        "symptoms",
        "neurological_symptoms",
        "known_cancer_history",
        "previous_treatment",
        "known_diagnosis",
        "WHO_grade",
        "hormonal_profile"
    ],

    "candidate_targets": [

        "recommendation_category",
        "recommended_specialist",
        "recommended_next_step",
        "follow_up_category"
    ]
}

# =============================================================================
# 10. DATASET CANDIDATES
# =============================================================================

dataset_candidates = [

    {
        "name": "BraTS Pre-operative Meningioma",
        "tumor_type": "meningioma",
        "priority": 1,
        "status": "AUDIT_REQUIRED",
        "clinical_fields": [
            "age",
            "sex",
            "CNS WHO grade"
        ]
    },

    {
        "name": "BraTS-MEN-RT",
        "tumor_type": "meningioma",
        "priority": 2,
        "status": "AUDIT_REQUIRED",
        "clinical_fields": [
            "age",
            "sex",
            "WHO grade"
        ]
    },

    {
        "name": "PitNET Clinical Dataset",
        "tumor_type": "pituitary_tumor",
        "priority": 1,
        "status": "AUDIT_REQUIRED",
        "clinical_fields": [
            "age",
            "sex",
            "WHO 2022 classification",
            "hormone pattern",
            "pathology",
            "ICD-10"
        ]
    },

    {
        "name": "Pituitary Neuroendocrine Tumor MRI Dataset",
        "tumor_type": "pituitary_tumor",
        "priority": 2,
        "status": "AUDIT_REQUIRED",
        "clinical_fields": [
            "age",
            "sex",
            "clinical phenotype",
            "cell lineage",
            "cell type",
            "Ki-67"
        ]
    }
]

# =============================================================================
# 11. SAVE CONFIGURATION
# =============================================================================

config = {

    "project": {
        "name": "Model5",
        "version": "0.1.0",
        "created": datetime.now().isoformat()
    },

    "storage": {
        "colab_root": str(COLAB_ROOT),
        "drive_root": str(DRIVE_ROOT),
        "raw_root": str(RAW_ROOT),
        "clinical_root": str(CLINICAL_ROOT),
        "processed_root": str(PROCESSED_ROOT)
    },

    "architecture": architecture,

    "dataset_policy": dataset_policy,

    "safety_policy": safety_policy,

    "feature_schema": feature_schema,

    "dataset_candidates": dataset_candidates,

    "hardware": {
        "gpu_available": gpu_available,
        "gpu_name": gpu_name
    }
}

config_path = CONFIG_ROOT / "model5_config.json"

with open(config_path, "w") as f:
    json.dump(config, f, indent=2)

print()
print("=" * 80)
print("CONFIGURATION SAVED")
print("=" * 80)

print(config_path)

# =============================================================================
# 12. STORAGE POLICY FILE
# =============================================================================

storage_policy_text = f"""
MODEL 5 STORAGE POLICY
======================

Created:
{datetime.now().isoformat()}

COLAB
-----
Raw MRI data:
{RAW_ROOT}

Temporary data:
{TEMP_ROOT}

Cache:
{CACHE_ROOT}

GOOGLE DRIVE
------------
Project:
{DRIVE_ROOT}

Clinical:
{CLINICAL_ROOT}

Processed:
{PROCESSED_ROOT}

Models:
{MODELS_ROOT}

Results:
{RESULTS_ROOT}

Reports:
{REPORTS_ROOT}

Audit:
{AUDIT_ROOT}

Knowledge:
{KNOWLEDGE_ROOT}

Exports:
{EXPORT_ROOT}

RULES
-----

1. Large raw MRI files stay in Colab.
2. Do not copy large MRI archives to Drive.
3. Clinical tables may be stored on Drive.
4. Processed compact datasets may be stored on Drive.
5. Trained models are stored on Drive.
6. Every dataset must be audited before training.
7. Never fabricate clinical labels.
8. Never fabricate prescription labels.
"""

storage_policy_path = DRIVE_ROOT / "STORAGE_POLICY.txt"

with open(storage_policy_path, "w") as f:
    f.write(storage_policy_text)

# =============================================================================
# 13. README
# =============================================================================

readme = """
# Model 5

Clinical Decision Support + Structured Medical Reporting Research Prototype.

## Architecture

Model 3B
- Tumor classification

Model 4A
- Tumor segmentation
- Tumor measurements
- Location
- Boundary
- Bounding box

Model 5
- Clinical decision-support layer
- Recommendation category
- Specialist category
- Next clinical step
- Follow-up category

Gemini API
- Structured report generation
- Explanation of validated information

## Important

Model 5 is not an autonomous diagnostic system.

Model 5 does not autonomously prescribe medication.

Clinical recommendations must be grounded in validated evidence.

Missing patient information must never be invented.

## Storage

Large raw MRI data stays in Colab.

Compact clinical data, models, reports and audits are stored in Google Drive.

## Development

1. Project initialization
2. Dataset/source audit
3. Official metadata acquisition
4. Clinical data cleaning
5. Unified clinical dataset
6. Feature engineering
7. Target/label validation
8. Train/validation/test split
9. Baseline ML models
10. Model selection
11. Clinical rules/evidence layer
12. Integration
13. External validation
14. Gemini integration
15. Structured report generation
16. Safety testing
17. End-to-end validation
18. Final export
"""

readme_path = DRIVE_ROOT / "README.md"

with open(readme_path, "w") as f:
    f.write(readme)

# =============================================================================
# 14. INITIAL AUDIT
# =============================================================================

initial_audit = {

    "timestamp": datetime.now().isoformat(),

    "step": "1",

    "status": "COMPLETE",

    "storage_check": {
        "colab_free_gb": round(colab_storage["free_gb"], 2),
        "drive_free_gb": round(drive_storage["free_gb"], 2),
        "passed": True
    },

    "gpu": {
        "available": gpu_available,
        "name": gpu_name
    },

    "large_data_downloaded": False,

    "training_started": False,

    "architecture_frozen": True,

    "dataset_labels_validated": False,

    "clinical_targets_validated": False,

    "gemini_integrated": False
}

audit_path = AUDIT_ROOT / "step1_initialization_audit.json"

with open(audit_path, "w") as f:
    json.dump(initial_audit, f, indent=2)

# =============================================================================
# FINAL STATUS
# =============================================================================

print()
print("=" * 80)
print("MODEL 5 - STEP 1 COMPLETE")
print("=" * 80)

print()
print("Project:")
print("✅ Initialized")

print("Storage:")
print("✅ Safety check passed")

print("Architecture:")
print("✅ Defined")

print("Safety policy:")
print("✅ Defined")

print("Dataset download:")
print("❌ NOT STARTED")

print("Clinical labels:")
print("⏳ NOT VALIDATED")

print("Training:")
print("❌ NOT STARTED")

print("Gemini:")
print("❌ NOT INTEGRATED")

print()
print("Configuration:")
print(config_path)

print()
print("README:")
print(readme_path)

print()
print("Audit:")
print(audit_path)

print()
print("=" * 80)
print("NEXT → STEP 2")
print("OFFICIAL DATASET + CLINICAL LABEL AUDIT")
print("=" * 80)

================================================================================
MODEL 5 - STEP 1
CLINICAL DECISION SUPPORT + REPORTING SYSTEM
FRESH PROJECT INITIALIZATION
================================================================================
Mounted at /content/drive
✅ Google Drive mounted

================================================================================
PROJECT DIRECTORIES
================================================================================
Colab root       : /content/Model5
Raw data         : /content/Model5/raw
Temporary data   : /content/Model5/temp
Drive root       : /content/drive/MyDrive/Model5
Clinical data    : /content/drive/MyDrive/Model5/data/clinical
Processed data   : /content/drive/MyDrive/Model5/data/processed
Models           : /content/drive/MyDrive/Model5/models
Results          : /content/drive/MyDrive/Model5/results
Reports          : /content/drive/MyDrive/Model5/reports
Audit            : /content/drive/MyDrive/Model5/audit
Knowledge        : /content/drive/MyDrive/Model5/knowledge
Exports          : /content/drive/MyDrive/Model5/exports

================================================================================
STORAGE CHECK
================================================================================

COLAB
------
Total : 112.64 GB
Used  : 47.20 GB
Free  : 65.43 GB

GOOGLE DRIVE
------------
Total : 112.64 GB
Used  : 50.48 GB
Free  : 62.15 GB

✅ STORAGE SAFETY CHECK PASSED

================================================================================
GPU CHECK
================================================================================
✅ GPU AVAILABLE
 - PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')

================================================================================
SYSTEM INFORMATION
================================================================================

Python:
3.13.15 (main, Aug  6 2026, 11:06:23) [GCC 11.4.0]

Platform:
Linux-6.6.122+-x86_64-with-glibc2.35

================================================================================
CONFIGURATION SAVED
================================================================================
/content/drive/MyDrive/Model5/config/model5_config.json

================================================================================
MODEL 5 - STEP 1 COMPLETE
================================================================================

Project:
✅ Initialized
Storage:
✅ Safety check passed
Architecture:
✅ Defined
Safety policy:
✅ Defined
Dataset download:
❌ NOT STARTED
Clinical labels:
⏳ NOT VALIDATED
Training:
❌ NOT STARTED
Gemini:
❌ NOT INTEGRATED

Configuration:
/content/drive/MyDrive/Model5/config/model5_config.json

README:
/content/drive/MyDrive/Model5/README.md

Audit:
/content/drive/MyDrive/Model5/audit/step1_initialization_audit.json

================================================================================
NEXT → STEP 2
OFFICIAL DATASET + CLINICAL LABEL AUDIT
================================================================================

In [2]:
# =============================================================================
# MODEL 5 - STEP 2
# OFFICIAL DATASET + CLINICAL LABEL AUDIT
# =============================================================================

import os
import json
import requests
from pathlib import Path
from datetime import datetime

print("=" * 80)
print("MODEL 5 - STEP 2")
print("OFFICIAL DATASET + CLINICAL LABEL AUDIT")
print("=" * 80)

# =============================================================================
# PATHS
# =============================================================================

DRIVE_ROOT = Path("/content/drive/MyDrive/Model5")

AUDIT_ROOT = DRIVE_ROOT / "audit" / "dataset"
CLINICAL_ROOT = DRIVE_ROOT / "data" / "clinical"

AUDIT_ROOT.mkdir(parents=True, exist_ok=True)
CLINICAL_ROOT.mkdir(parents=True, exist_ok=True)

# =============================================================================
# DATASET INVENTORY
# =============================================================================

datasets = [
    {
        "id": "pitnet_clinical_1096",
        "name": "PitNET Clinical Dataset",
        "tumor_type": "pituitary_tumor",
        "priority": 1,

        "expected_cases": 1096,

        "clinical_fields": [
            "age",
            "sex",
            "WHO 2022 pathological classification",
            "hormone pattern",
            "pathology",
            "ICD-10"
        ],

        "imaging_available": False,

        "prescription_labels": False,

        "treatment_labels": False,

        "source": "Mendeley Data",

        "source_url": "https://data.mendeley.com/datasets/mynjx8hjvt",

        "purpose": [
            "clinical feature analysis",
            "PitNET classification",
            "clinical recommendation research"
        ]
    },

    {
        "id": "pituitary_mri_136",
        "name": "Pituitary Neuroendocrine Tumor MRI Dataset",
        "tumor_type": "pituitary_tumor",
        "priority": 2,

        "expected_cases": 136,

        "clinical_fields": [
            "age",
            "sex",
            "clinical phenotype",
            "cell lineage",
            "cell type",
            "Ki-67"
        ],

        "imaging_available": True,

        "prescription_labels": False,

        "treatment_labels": False,

        "source": "Zenodo / published dataset",

        "source_url": "https://zenodo.org/records/18553150",

        "purpose": [
            "MRI-clinical correlation",
            "pituitary tumor phenotype",
            "segmentation / imaging features"
        ]
    },

    {
        "id": "brats_meningioma_1141",
        "name": "BraTS Pre-operative Meningioma",
        "tumor_type": "meningioma",
        "priority": 3,

        "expected_cases": 1141,

        "clinical_fields": [
            "age",
            "sex",
            "CNS WHO grade"
        ],

        "imaging_available": True,

        "prescription_labels": False,

        "treatment_labels": False,

        "source": "BraTS / Synapse",

        "source_url": "https://www.synapse.org/",

        "purpose": [
            "meningioma clinical metadata",
            "WHO grade",
            "MRI research"
        ]
    },

    {
        "id": "brats_men_rt_570",
        "name": "BraTS-MEN-RT",
        "tumor_type": "meningioma",
        "priority": 4,

        "expected_cases": 570,

        "clinical_fields": [
            "age",
            "sex",
            "WHO grade"
        ],

        "imaging_available": True,

        "prescription_labels": False,

        "treatment_labels": False,

        "source": "BraTS / Synapse",

        "source_url": "https://www.synapse.org/Synapse%3Asyn60085033.2",

        "purpose": [
            "meningioma MRI",
            "segmentation",
            "radiotherapy research"
        ]
    }
]

# =============================================================================
# PRINT AUDIT
# =============================================================================

print()
print("=" * 80)
print("DATASET INVENTORY")
print("=" * 80)

for d in datasets:

    print()
    print("-" * 80)
    print(d["name"])
    print("-" * 80)

    print("Dataset ID       :", d["id"])
    print("Tumor type       :", d["tumor_type"])
    print("Priority         :", d["priority"])
    print("Expected cases   :", d["expected_cases"])
    print("Imaging available:", d["imaging_available"])

    print()
    print("Clinical fields:")

    for field in d["clinical_fields"]:
        print("  -", field)

    print()
    print("Treatment labels  :", d["treatment_labels"])
    print("Prescription data :", d["prescription_labels"])

    print()
    print("Source:")
    print(" ", d["source"])

    print()
    print("URL:")
    print(" ", d["source_url"])

# =============================================================================
# CHECK PUBLIC SOURCE AVAILABILITY
# =============================================================================

print()
print("=" * 80)
print("SOURCE AVAILABILITY CHECK")
print("=" * 80)

source_results = []

for d in datasets:

    url = d["source_url"]

    try:

        response = requests.get(
            url,
            timeout=20,
            allow_redirects=True,
            headers={
                "User-Agent": "Mozilla/5.0 Model5-Dataset-Audit"
            }
        )

        result = {
            "dataset_id": d["id"],
            "url": url,
            "http_status": response.status_code,
            "reachable": response.status_code < 400,
            "final_url": response.url,
            "checked_at": datetime.now().isoformat()
        }

        source_results.append(result)

        if response.status_code < 400:
            print(f"✅ {d['name']}")
            print(f"   HTTP {response.status_code}")
        else:
            print(f"⚠️ {d['name']}")
            print(f"   HTTP {response.status_code}")

    except Exception as e:

        result = {
            "dataset_id": d["id"],
            "url": url,
            "reachable": False,
            "error": str(e),
            "checked_at": datetime.now().isoformat()
        }

        source_results.append(result)

        print(f"⚠️ {d['name']}")
        print("  ", str(e)[:500])

# =============================================================================
# CLINICAL LABEL AUDIT
# =============================================================================

print()
print("=" * 80)
print("CLINICAL LABEL AUDIT")
print("=" * 80)

print("""
The following distinction is mandatory:

AVAILABLE CLINICAL LABEL
------------------------
A field actually provided by the dataset.

TREATMENT LABEL
---------------
A documented treatment/management outcome.

PRESCRIPTION LABEL
------------------
A documented medication and prescribing outcome.

We will NOT transform a clinical variable into a treatment label.

Examples:

WHO grade → NOT a prescription label
Tumor size → NOT a prescription label
Tumor type → NOT a prescription label
Hormone phenotype → NOT automatically a prescription label
""")

# =============================================================================
# AVAILABLE TARGETS
# =============================================================================

available_targets = {

    "directly_available_or_potentially_available": [
        "tumor_type",
        "WHO_grade",
        "pathological_classification",
        "hormone_pattern",
        "clinical_phenotype",
        "age",
        "sex",
        "Ki-67",
        "cell_lineage",
        "cell_type"
    ],

    "not_available_from_current_inventory": [
        "validated medication prescription",
        "medication dosage",
        "medication frequency",
        "medication duration",
        "patient-specific treatment decision"
    ]
}

print()
print("=" * 80)
print("TARGET AUDIT")
print("=" * 80)

print()
print("Potentially usable clinical targets:")

for target in available_targets[
    "directly_available_or_potentially_available"
]:
    print("  ✅", target)

print()
print("Unavailable prescription/treatment targets:")

for target in available_targets[
    "not_available_from_current_inventory"
]:
    print("  ❌", target)

# =============================================================================
# MODEL 5 DATA STRATEGY
# =============================================================================

strategy = {

    "phase_1": {
        "name": "Clinical dataset construction",
        "goal": (
            "Build a clean structured clinical dataset from "
            "verified public metadata."
        )
    },

    "phase_2": {
        "name": "Target validation",
        "goal": (
            "Determine which recommendation targets have legitimate "
            "labels rather than creating artificial labels."
        )
    },

    "phase_3": {
        "name": "ML baseline",
        "models": [
            "Logistic Regression",
            "Random Forest",
            "Gradient Boosting"
        ]
    },

    "phase_4": {
        "name": "Clinical knowledge layer",
        "goal": (
            "Use evidence-backed rules/guidelines for recommendations "
            "that cannot legitimately be learned from the datasets."
        )
    },

    "phase_5": {
        "name": "Gemini reporting",
        "goal": (
            "Generate a structured human-readable report from "
            "validated structured inputs."
        )
    }
}

# =============================================================================
# SAVE AUDIT
# =============================================================================

audit = {

    "timestamp": datetime.now().isoformat(),

    "datasets": datasets,

    "source_results": source_results,

    "available_targets": available_targets,

    "strategy": strategy,

    "large_mri_downloaded": False,

    "clinical_metadata_downloaded": False,

    "prescription_model_started": False,

    "decision": (
        "Do not download large MRI datasets until metadata and "
        "usable labels have been verified."
    )
}

audit_path = (
    AUDIT_ROOT /
    "step2_official_dataset_clinical_label_audit.json"
)

with open(audit_path, "w") as f:
    json.dump(audit, f, indent=2)

print()
print("=" * 80)
print("AUDIT SAVED")
print("=" * 80)

print(audit_path)

# =============================================================================
# FINAL STATUS
# =============================================================================

print()
print("=" * 80)
print("MODEL 5 - STEP 2 COMPLETE")
print("=" * 80)

print()
print("Dataset sources audited:")
print("✅")

print("Large MRI download:")
print("❌ NOT STARTED")

print("Clinical metadata download:")
print("❌ NOT STARTED")

print("Prescription labels:")
print("❌ NOT AVAILABLE IN CURRENT INVENTORY")

print("Clinical feature targets:")
print("✅ IDENTIFIED")

print("Target validation:")
print("⏳ NEXT")

print()
print("NEXT → STEP 3")
print("CLINICAL DATASET ACQUISITION + METADATA DOWNLOAD")

print("=" * 80)

================================================================================
MODEL 5 - STEP 2
OFFICIAL DATASET + CLINICAL LABEL AUDIT
================================================================================

================================================================================
DATASET INVENTORY
================================================================================

--------------------------------------------------------------------------------
PitNET Clinical Dataset
--------------------------------------------------------------------------------
Dataset ID       : pitnet_clinical_1096
Tumor type       : pituitary_tumor
Priority         : 1
Expected cases   : 1096
Imaging available: False

Clinical fields:
  - age
  - sex
  - WHO 2022 pathological classification
  - hormone pattern
  - pathology
  - ICD-10

Treatment labels  : False
Prescription data : False

Source:
  Mendeley Data

URL:
  https://data.mendeley.com/datasets/mynjx8hjvt

--------------------------------------------------------------------------------
Pituitary Neuroendocrine Tumor MRI Dataset
--------------------------------------------------------------------------------
Dataset ID       : pituitary_mri_136
Tumor type       : pituitary_tumor
Priority         : 2
Expected cases   : 136
Imaging available: True

Clinical fields:
  - age
  - sex
  - clinical phenotype
  - cell lineage
  - cell type
  - Ki-67

Treatment labels  : False
Prescription data : False

Source:
  Zenodo / published dataset

URL:
  https://zenodo.org/records/18553150

--------------------------------------------------------------------------------
BraTS Pre-operative Meningioma
--------------------------------------------------------------------------------
Dataset ID       : brats_meningioma_1141
Tumor type       : meningioma
Priority         : 3
Expected cases   : 1141
Imaging available: True

Clinical fields:
  - age
  - sex
  - CNS WHO grade

Treatment labels  : False
Prescription data : False

Source:
  BraTS / Synapse

URL:
  https://www.synapse.org/

--------------------------------------------------------------------------------
BraTS-MEN-RT
--------------------------------------------------------------------------------
Dataset ID       : brats_men_rt_570
Tumor type       : meningioma
Priority         : 4
Expected cases   : 570
Imaging available: True

Clinical fields:
  - age
  - sex
  - WHO grade

Treatment labels  : False
Prescription data : False

Source:
  BraTS / Synapse

URL:
  https://www.synapse.org/Synapse%3Asyn60085033.2

================================================================================
SOURCE AVAILABILITY CHECK
================================================================================
⚠️ PitNET Clinical Dataset
   HTTP 403
✅ Pituitary Neuroendocrine Tumor MRI Dataset
   HTTP 200
✅ BraTS Pre-operative Meningioma
   HTTP 200
✅ BraTS-MEN-RT
   HTTP 200

================================================================================
CLINICAL LABEL AUDIT
================================================================================

The following distinction is mandatory:

AVAILABLE CLINICAL LABEL
------------------------
A field actually provided by the dataset.

TREATMENT LABEL
---------------
A documented treatment/management outcome.

PRESCRIPTION LABEL
------------------
A documented medication and prescribing outcome.

We will NOT transform a clinical variable into a treatment label.

Examples:

WHO grade → NOT a prescription label
Tumor size → NOT a prescription label
Tumor type → NOT a prescription label
Hormone phenotype → NOT automatically a prescription label


================================================================================
TARGET AUDIT
================================================================================

Potentially usable clinical targets:
  ✅ tumor_type
  ✅ WHO_grade
  ✅ pathological_classification
  ✅ hormone_pattern
  ✅ clinical_phenotype
  ✅ age
  ✅ sex
  ✅ Ki-67
  ✅ cell_lineage
  ✅ cell_type

Unavailable prescription/treatment targets:
  ❌ validated medication prescription
  ❌ medication dosage
  ❌ medication frequency
  ❌ medication duration
  ❌ patient-specific treatment decision

================================================================================
AUDIT SAVED
================================================================================
/content/drive/MyDrive/Model5/audit/dataset/step2_official_dataset_clinical_label_audit.json

================================================================================
MODEL 5 - STEP 2 COMPLETE
================================================================================

Dataset sources audited:
✅
Large MRI download:
❌ NOT STARTED
Clinical metadata download:
❌ NOT STARTED
Prescription labels:
❌ NOT AVAILABLE IN CURRENT INVENTORY
Clinical feature targets:
✅ IDENTIFIED
Target validation:
⏳ NEXT

NEXT → STEP 3
CLINICAL DATASET ACQUISITION + METADATA DOWNLOAD
================================================================================

In [3]:
# =============================================================================
# MODEL 5 - STEP 3
# CLINICAL DATASET ACQUISITION + METADATA INSPECTION
# =============================================================================

import os
import json
import shutil
import zipfile
import tarfile
import requests
import pandas as pd
from pathlib import Path
from datetime import datetime

print("=" * 80)
print("MODEL 5 - STEP 3")
print("CLINICAL DATASET ACQUISITION + METADATA INSPECTION")
print("=" * 80)

# =============================================================================
# PATHS
# =============================================================================

COLAB_ROOT = Path("/content/Model5")
RAW_ROOT = COLAB_ROOT / "raw"
TEMP_ROOT = COLAB_ROOT / "temp"

DRIVE_ROOT = Path("/content/drive/MyDrive/Model5")
CLINICAL_ROOT = DRIVE_ROOT / "data" / "clinical"
AUDIT_ROOT = DRIVE_ROOT / "audit" / "dataset"

RAW_ROOT.mkdir(parents=True, exist_ok=True)
TEMP_ROOT.mkdir(parents=True, exist_ok=True)
CLINICAL_ROOT.mkdir(parents=True, exist_ok=True)
AUDIT_ROOT.mkdir(parents=True, exist_ok=True)

# =============================================================================
# STORAGE
# =============================================================================

def storage_gb(path):
    u = shutil.disk_usage(path)

    return {
        "total": u.total / (1024 ** 3),
        "used": u.used / (1024 ** 3),
        "free": u.free / (1024 ** 3)
    }

colab = storage_gb("/content")
drive = storage_gb("/content/drive")

print()
print("=" * 80)
print("STORAGE")
print("=" * 80)

print(f"Colab free : {colab['free']:.2f} GB")
print(f"Drive free : {drive['free']:.2f} GB")

if colab["free"] < 20:
    raise RuntimeError("Colab free storage below safety limit.")

if drive["free"] < 3:
    raise RuntimeError("Drive free storage below safety limit.")

print("✅ STORAGE SAFETY CHECK PASSED")

# =============================================================================
# DATASET DOWNLOAD POLICY
# =============================================================================

print()
print("=" * 80)
print("DOWNLOAD POLICY")
print("=" * 80)

print("""
This step intentionally does NOT download large MRI archives.

We will first obtain compact metadata / clinical tables.

For every downloaded dataset:

1. Identify actual files.
2. Inspect file types.
3. Inspect table columns.
4. Count records.
5. Detect duplicate IDs.
6. Measure missing values.
7. Detect clinical labels.
8. Detect treatment/prescription fields.
9. Save a compact audit to Drive.

Large MRI files will NOT be copied to Drive.
""")

# =============================================================================
# DOWNLOAD HELPER
# =============================================================================

def download_file(url, destination, timeout=60):

    destination = Path(destination)
    destination.parent.mkdir(parents=True, exist_ok=True)

    print()
    print("Downloading:")
    print(url)

    try:

        response = requests.get(
            url,
            stream=True,
            timeout=timeout,
            headers={
                "User-Agent": "Mozilla/5.0 Model5-Dataset-Acquisition"
            }
        )

        response.raise_for_status()

        total = response.headers.get("content-length")

        if total:
            total = int(total)
            print(
                "Size:",
                round(total / (1024 ** 2), 2),
                "MB"
            )

        with open(destination, "wb") as f:

            downloaded = 0

            for chunk in response.iter_content(
                chunk_size=1024 * 1024
            ):

                if chunk:

                    f.write(chunk)
                    downloaded += len(chunk)

                    if total:
                        percent = downloaded / total * 100
                        print(
                            f"\rProgress: {percent:6.2f}%",
                            end=""
                        )

        print()

        print("✅ Download complete")
        print("Saved:", destination)

        return True

    except Exception as e:

        print()
        print("❌ Download failed")
        print(str(e)[:2000])

        if destination.exists():
            destination.unlink()

        return False

# =============================================================================
# FILE INSPECTION
# =============================================================================

def inspect_directory(root):

    root = Path(root)

    records = []

    for path in root.rglob("*"):

        if path.is_file():

            try:
                size = path.stat().st_size
            except:
                size = None

            records.append({
                "path": str(path),
                "name": path.name,
                "suffix": path.suffix.lower(),
                "size_bytes": size,
                "size_mb": (
                    size / (1024 ** 2)
                    if size is not None
                    else None
                )
            })

    return records

# =============================================================================
# TABLE INSPECTION
# =============================================================================

def inspect_tables(root):

    root = Path(root)

    table_results = []

    for path in root.rglob("*"):

        if not path.is_file():
            continue

        suffix = path.suffix.lower()

        try:

            if suffix == ".csv":

                df = pd.read_csv(path)

            elif suffix in [".xlsx", ".xls"]:

                df = pd.read_excel(path)

            elif suffix == ".json":

                try:
                    df = pd.read_json(path)

                except:

                    with open(path, "r") as f:
                        obj = json.load(f)

                    if isinstance(obj, list):
                        df = pd.DataFrame(obj)
                    elif isinstance(obj, dict):
                        df = pd.DataFrame([obj])
                    else:
                        continue

            else:
                continue

            result = {

                "file": str(path),

                "rows": int(len(df)),

                "columns": int(len(df.columns)),

                "column_names": [
                    str(c)
                    for c in df.columns
                ],

                "missing_values": {
                    str(c): int(df[c].isna().sum())
                    for c in df.columns
                },

                "duplicate_rows": int(
                    df.duplicated().sum()
                )
            }

            table_results.append(result)

            print()
            print("-" * 80)
            print("TABLE FOUND")
            print("-" * 80)

            print("File:")
            print(path)

            print("Rows:", len(df))
            print("Columns:", len(df.columns))

            print()
            print("Columns:")

            for c in df.columns:
                print(" -", c)

            print()
            print("Duplicate rows:", df.duplicated().sum())

            print()
            print("Missing values:")

            missing = df.isna().sum()

            for c, n in missing.items():

                if n > 0:
                    print(
                        f" - {c}: {n} "
                        f"({n / len(df) * 100:.2f}%)"
                    )

            print()
            print("Preview:")

            display(df.head(5))

        except Exception as e:

            print()
            print("⚠️ Could not inspect:")
            print(path)
            print(str(e)[:1000])

    return table_results

# =============================================================================
# DATASET 1
# PITUITARY MRI DATASET
# =============================================================================

print()
print("=" * 80)
print("DATASET 1")
print("PITUITARY NEUROENDOCRINE TUMOR MRI DATASET")
print("=" * 80)

print("""
The public Zenodo record will be inspected first.

We will not assume its downloadable filename.
""")

pituitary_url = "https://zenodo.org/records/18553150"

try:

    response = requests.get(
        pituitary_url,
        timeout=30,
        headers={
            "User-Agent": "Mozilla/5.0 Model5-Audit"
        }
    )

    print("HTTP status:", response.status_code)

    if response.status_code == 200:

        print("✅ Zenodo record reachable")

        html = response.text

        # Save the public landing-page response for audit only.
        page_path = (
            TEMP_ROOT /
            "pituitary_zenodo_landing_page.html"
        )

        with open(page_path, "w", encoding="utf-8") as f:
            f.write(html)

        print("Landing page saved:")
        print(page_path)

    else:

        print("⚠️ Zenodo returned:", response.status_code)

except Exception as e:

    print("⚠️ Could not access Zenodo:")
    print(str(e)[:1500])

# =============================================================================
# DATASET 2
# MENINGIOMA BRAINTS
# =============================================================================

print()
print("=" * 80)
print("DATASET 2")
print("BRATS PRE-OPERATIVE MENINGIOMA")
print("=" * 80)

print("""
BraTS/Synapse access is normally controlled through the
official Synapse dataset.

We will NOT attempt anonymous bulk MRI download.

Instead we record the dataset for controlled metadata acquisition.
""")

brats_info = {

    "dataset": "BraTS Pre-operative Meningioma",

    "tumor_type": "meningioma",

    "expected_cases": 1141,

    "clinical_fields": [
        "age",
        "sex",
        "CNS WHO grade"
    ],

    "large_mri_download": False,

    "synapse_authentication_required": True
}

print(json.dumps(brats_info, indent=2))

# =============================================================================
# DATASET 3
# BRATS-MEN-RT
# =============================================================================

print()
print("=" * 80)
print("DATASET 3")
print("BRATS-MEN-RT")
print("=" * 80)

brats_rt_info = {

    "dataset": "BraTS-MEN-RT",

    "tumor_type": "meningioma",

    "expected_cases": 570,

    "clinical_fields": [
        "age",
        "sex",
        "WHO grade"
    ],

    "large_mri_download": False,

    "synapse_authentication_required": True
}

print(json.dumps(brats_rt_info, indent=2))

# =============================================================================
# DATASET 4
# PITNET CLINICAL DATASET
# =============================================================================

print()
print("=" * 80)
print("DATASET 4")
print("PITNET CLINICAL DATASET")
print("=" * 80)

print("""
The Mendeley landing page returned HTTP 403 during Step 2.

We therefore DO NOT scrape it.

Instead, the dataset remains pending until its actual downloadable
data file can be obtained through an official/public route.
""")

pitnet_info = {

    "dataset": "PitNET Clinical Dataset",

    "expected_cases": 1096,

    "clinical_fields": [
        "age",
        "sex",
        "WHO 2022 pathological classification",
        "hormone pattern",
        "pathology",
        "ICD-10"
    ],

    "landing_page_status": "HTTP 403",

    "downloaded": False,

    "action": "PENDING OFFICIAL DOWNLOAD FILE"
}

print(json.dumps(pitnet_info, indent=2))

# =============================================================================
# INSPECT ANY EXISTING RAW DATA
# =============================================================================

print()
print("=" * 80)
print("CHECKING RAW DIRECTORY")
print("=" * 80)

existing_files = inspect_directory(RAW_ROOT)

if existing_files:

    print(
        "Existing files:",
        len(existing_files)
    )

    for item in existing_files[:100]:

        print(
            item["path"],
            "|",
            f"{item['size_mb']:.2f} MB"
        )

else:

    print("No raw datasets currently present.")

# =============================================================================
# INSPECT ANY EXISTING TABLES
# =============================================================================

print()
print("=" * 80)
print("INSPECTING AVAILABLE TABLES")
print("=" * 80)

table_results = inspect_tables(RAW_ROOT)

if not table_results:

    print("No clinical tables found yet.")

# =============================================================================
# SAVE STEP 3 AUDIT
# =============================================================================

audit = {

    "timestamp": datetime.now().isoformat(),

    "storage": {

        "colab_free_gb":
            round(colab["free"], 2),

        "drive_free_gb":
            round(drive["free"], 2)
    },

    "downloads": {

        "large_mri_downloaded": False,

        "pituitary_mri_downloaded": False,

        "meningioma_mri_downloaded": False,

        "brats_rt_mri_downloaded": False,

        "pitnet_clinical_downloaded": False
    },

    "datasets": {

        "pituitary_mri": {
            "record": pituitary_url,
            "status": "SOURCE_INSPECTED"
        },

        "brats_meningioma": brats_info,

        "brats_men_rt": brats_rt_info,

        "pitnet_clinical": pitnet_info
    },

    "tables_found": table_results,

    "next_step": (
        "Acquire verified clinical metadata files and inspect "
        "their actual columns before constructing the training dataset."
    )
}

audit_path = (
    AUDIT_ROOT /
    "step3_clinical_dataset_acquisition_audit.json"
)

with open(audit_path, "w") as f:

    json.dump(
        audit,
        f,
        indent=2
    )

# =============================================================================
# FINAL STATUS
# =============================================================================

print()
print("=" * 80)
print("MODEL 5 - STEP 3 COMPLETE")
print("=" * 80)

print()
print("Large MRI download:")
print("❌ NOT PERFORMED")

print()
print("Clinical table inspection:")
print(
    "✅ COMPLETE"
    if table_results
    else "⏳ NO TABLES AVAILABLE YET"
)

print()
print("Pituitary MRI source:")
print("✅ REACHABLE")

print("BraTS sources:")
print("✅ IDENTIFIED")

print("PitNET clinical dataset:")
print("⏳ DOWNLOAD FILE STILL NEEDS VERIFICATION")

print()
print("Audit:")
print(audit_path)

print()
print("=" * 80)
print("NEXT → STEP 4")
print("CLINICAL METADATA DOWNLOAD + SCHEMA INSPECTION")
print("=" * 80)

================================================================================
MODEL 5 - STEP 3
CLINICAL DATASET ACQUISITION + METADATA INSPECTION
================================================================================

================================================================================
STORAGE
================================================================================
Colab free : 65.42 GB
Drive free : 62.15 GB
✅ STORAGE SAFETY CHECK PASSED

================================================================================
DOWNLOAD POLICY
================================================================================

This step intentionally does NOT download large MRI archives.

We will first obtain compact metadata / clinical tables.

For every downloaded dataset:

1. Identify actual files.
2. Inspect file types.
3. Inspect table columns.
4. Count records.
5. Detect duplicate IDs.
6. Measure missing values.
7. Detect clinical labels.
8. Detect treatment/prescription fields.
9. Save a compact audit to Drive.

Large MRI files will NOT be copied to Drive.


================================================================================
DATASET 1
PITUITARY NEUROENDOCRINE TUMOR MRI DATASET
================================================================================

The public Zenodo record will be inspected first.

We will not assume its downloadable filename.

HTTP status: 200
✅ Zenodo record reachable
Landing page saved:
/content/Model5/temp/pituitary_zenodo_landing_page.html

================================================================================
DATASET 2
BRATS PRE-OPERATIVE MENINGIOMA
================================================================================

BraTS/Synapse access is normally controlled through the
official Synapse dataset.

We will NOT attempt anonymous bulk MRI download.

Instead we record the dataset for controlled metadata acquisition.

{
  "dataset": "BraTS Pre-operative Meningioma",
  "tumor_type": "meningioma",
  "expected_cases": 1141,
  "clinical_fields": [
    "age",
    "sex",
    "CNS WHO grade"
  ],
  "large_mri_download": false,
  "synapse_authentication_required": true
}

================================================================================
DATASET 3
BRATS-MEN-RT
================================================================================
{
  "dataset": "BraTS-MEN-RT",
  "tumor_type": "meningioma",
  "expected_cases": 570,
  "clinical_fields": [
    "age",
    "sex",
    "WHO grade"
  ],
  "large_mri_download": false,
  "synapse_authentication_required": true
}

================================================================================
DATASET 4
PITNET CLINICAL DATASET
================================================================================

The Mendeley landing page returned HTTP 403 during Step 2.

We therefore DO NOT scrape it.

Instead, the dataset remains pending until its actual downloadable
data file can be obtained through an official/public route.

{
  "dataset": "PitNET Clinical Dataset",
  "expected_cases": 1096,
  "clinical_fields": [
    "age",
    "sex",
    "WHO 2022 pathological classification",
    "hormone pattern",
    "pathology",
    "ICD-10"
  ],
  "landing_page_status": "HTTP 403",
  "downloaded": false,
  "action": "PENDING OFFICIAL DOWNLOAD FILE"
}

================================================================================
CHECKING RAW DIRECTORY
================================================================================
No raw datasets currently present.

================================================================================
INSPECTING AVAILABLE TABLES
================================================================================
No clinical tables found yet.

================================================================================
MODEL 5 - STEP 3 COMPLETE
================================================================================

Large MRI download:
❌ NOT PERFORMED

Clinical table inspection:
⏳ NO TABLES AVAILABLE YET

Pituitary MRI source:
✅ REACHABLE
BraTS sources:
✅ IDENTIFIED
PitNET clinical dataset:
⏳ DOWNLOAD FILE STILL NEEDS VERIFICATION

Audit:
/content/drive/MyDrive/Model5/audit/dataset/step3_clinical_dataset_acquisition_audit.json

================================================================================
NEXT → STEP 4
CLINICAL METADATA DOWNLOAD + SCHEMA INSPECTION
================================================================================

In [4]:
# =============================================================================
# MODEL 5 - STEP 4
# CLINICAL METADATA DOWNLOAD + SCHEMA INSPECTION
# =============================================================================

import os
import json
import shutil
import requests
import pandas as pd
from pathlib import Path
from datetime import datetime

print("=" * 80)
print("MODEL 5 - STEP 4")
print("CLINICAL METADATA DOWNLOAD + SCHEMA INSPECTION")
print("=" * 80)

# =============================================================================
# PATHS
# =============================================================================

COLAB_ROOT = Path("/content/Model5")
RAW_ROOT = COLAB_ROOT / "raw"
TEMP_ROOT = COLAB_ROOT / "temp"

DRIVE_ROOT = Path("/content/drive/MyDrive/Model5")
CLINICAL_ROOT = DRIVE_ROOT / "data" / "clinical"
AUDIT_ROOT = DRIVE_ROOT / "audit" / "dataset"

RAW_ROOT.mkdir(parents=True, exist_ok=True)
TEMP_ROOT.mkdir(parents=True, exist_ok=True)
CLINICAL_ROOT.mkdir(parents=True, exist_ok=True)
AUDIT_ROOT.mkdir(parents=True, exist_ok=True)

# =============================================================================
# STORAGE CHECK
# =============================================================================

def storage_info(path):
    u = shutil.disk_usage(path)

    return {
        "total_gb": u.total / (1024 ** 3),
        "used_gb": u.used / (1024 ** 3),
        "free_gb": u.free / (1024 ** 3)
    }

colab = storage_info("/content")
drive = storage_info("/content/drive")

print()
print("=" * 80)
print("STORAGE")
print("=" * 80)

print(f"Colab free : {colab['free_gb']:.2f} GB")
print(f"Drive free : {drive['free_gb']:.2f} GB")

if colab["free_gb"] < 20:
    raise RuntimeError("Colab storage below safety threshold.")

print("✅ STORAGE SAFETY CHECK PASSED")

# =============================================================================
# DOWNLOAD FUNCTION
# =============================================================================

def download_small_file(url, destination, max_mb=500):

    destination = Path(destination)
    destination.parent.mkdir(parents=True, exist_ok=True)

    print()
    print("Downloading:")
    print(url)

    try:

        response = requests.get(
            url,
            stream=True,
            timeout=60,
            headers={
                "User-Agent": "Mozilla/5.0 Model5-Metadata-Audit"
            }
        )

        response.raise_for_status()

        content_length = response.headers.get("content-length")

        if content_length:

            size_mb = int(content_length) / (1024 ** 2)

            print(
                f"Remote size: {size_mb:.2f} MB"
            )

            if size_mb > max_mb:

                print(
                    f"⚠️ File exceeds {max_mb} MB."
                )

                return False

        downloaded = 0

        with open(destination, "wb") as f:

            for chunk in response.iter_content(
                chunk_size=1024 * 1024
            ):

                if chunk:

                    f.write(chunk)
                    downloaded += len(chunk)

                    if downloaded % (10 * 1024 * 1024) < (
                        1024 * 1024
                    ):

                        print(
                            f"\rDownloaded: "
                            f"{downloaded / (1024 ** 2):.2f} MB",
                            end=""
                        )

        print()
        print("✅ Downloaded:")
        print(destination)

        return True

    except Exception as e:

        print()
        print("❌ Download failed:")
        print(str(e)[:2000])

        if destination.exists():
            destination.unlink()

        return False

# =============================================================================
# GENERIC TABLE INSPECTOR
# =============================================================================

def inspect_table(path):

    path = Path(path)

    suffix = path.suffix.lower()

    try:

        if suffix == ".csv":

            df = pd.read_csv(path)

        elif suffix in [".xlsx", ".xls"]:

            df = pd.read_excel(path)

        elif suffix == ".json":

            try:

                df = pd.read_json(path)

            except:

                with open(path, "r", encoding="utf-8") as f:
                    obj = json.load(f)

                if isinstance(obj, list):
                    df = pd.DataFrame(obj)

                elif isinstance(obj, dict):

                    # Try records-like JSON
                    if all(
                        isinstance(v, list)
                        for v in obj.values()
                    ):
                        df = pd.DataFrame(obj)

                    else:
                        df = pd.DataFrame([obj])

                else:
                    return None

        elif suffix == ".tsv":

            df = pd.read_csv(
                path,
                sep="\t"
            )

        else:

            return None

        print()
        print("=" * 80)
        print("TABLE INSPECTION")
        print("=" * 80)

        print("File:")
        print(path)

        print()
        print("Rows:", len(df))
        print("Columns:", len(df.columns))

        print()
        print("COLUMN NAMES")

        for column in df.columns:

            print(
                f" - {column}"
                f" | dtype={df[column].dtype}"
                f" | missing={df[column].isna().sum()}"
            )

        print()
        print("DUPLICATE ROWS:")
        print(df.duplicated().sum())

        print()
        print("PREVIEW")

        display(df.head(10))

        return df

    except Exception as e:

        print()
        print("⚠️ Could not inspect:")
        print(path)

        print(str(e)[:2000])

        return None

# =============================================================================
# PITUITARY ZENODO API
# =============================================================================

print()
print("=" * 80)
print("DATASET 1")
print("PITUITARY NEUROENDOCRINE TUMOR MRI DATASET")
print("=" * 80)

ZENODO_RECORD_ID = "18553150"

zenodo_api = (
    f"https://zenodo.org/api/records/{ZENODO_RECORD_ID}"
)

print()
print("Querying Zenodo API:")
print(zenodo_api)

zenodo_data = None

try:

    response = requests.get(
        zenodo_api,
        timeout=60,
        headers={
            "User-Agent": "Model5-Metadata-Audit"
        }
    )

    print()
    print("HTTP status:", response.status_code)

    response.raise_for_status()

    zenodo_data = response.json()

    print("✅ Zenodo API response received")

except Exception as e:

    print("❌ Zenodo API request failed")
    print(str(e)[:2000])

# =============================================================================
# LIST ZENODO FILES
# =============================================================================

zenodo_files = []

if zenodo_data is not None:

    files = zenodo_data.get(
        "files",
        []
    )

    print()
    print("=" * 80)
    print("FILES AVAILABLE IN ZENODO RECORD")
    print("=" * 80)

    if not files:

        print("⚠️ No files found in API response.")

    for item in files:

        key = item.get("key")
        size = item.get("size")
        links = item.get("links", {})

        download_url = links.get(
            "self"
        )

        size_mb = (
            size / (1024 ** 2)
            if size is not None
            else None
        )

        record = {

            "key": key,

            "size_bytes": size,

            "size_mb": size_mb,

            "download_url": download_url
        }

        zenodo_files.append(record)

        print()
        print("File:", key)
        print(
            "Size:",
            f"{size_mb:.2f} MB"
            if size_mb is not None
            else "unknown"
        )

        print(
            "URL:",
            download_url
        )

# =============================================================================
# SELECT SMALL METADATA FILES
# =============================================================================

print()
print("=" * 80)
print("SEARCHING FOR CLINICAL / METADATA FILES")
print("=" * 80)

metadata_keywords = [

    "clinical",
    "metadata",
    "patient",
    "patients",
    "label",
    "labels",
    "annotation",
    "annotations",
    "phenotype",
    "demographic",
    "clinical_data",
    "clinical-data",
    "data.csv",
    "metadata.csv"
]

candidate_files = []

for item in zenodo_files:

    name = str(
        item["key"]
    ).lower()

    if any(
        keyword in name
        for keyword in metadata_keywords
    ):

        candidate_files.append(item)

        print(
            "Candidate:",
            item["key"]
        )

if not candidate_files:

    print(
        "⚠️ No obvious metadata filename found."
    )

# =============================================================================
# DOWNLOAD SMALL CANDIDATES
# =============================================================================

downloaded_metadata = []

print()
print("=" * 80)
print("DOWNLOADING SMALL METADATA CANDIDATES")
print("=" * 80)

for item in candidate_files:

    size_mb = item["size_mb"]

    # Never automatically download large files.
    if size_mb is not None and size_mb > 500:

        print()
        print(
            f"Skipping {item['key']} "
            f"({size_mb:.2f} MB)"
        )

        continue

    destination = (
        RAW_ROOT /
        "pituitary_metadata" /
        Path(item["key"]).name
    )

    success = download_small_file(
        item["download_url"],
        destination,
        max_mb=500
    )

    if success:

        downloaded_metadata.append(
            str(destination)
        )

# =============================================================================
# INSPECT DOWNLOADED METADATA
# =============================================================================

print()
print("=" * 80)
print("INSPECTING DOWNLOADED PITUITARY METADATA")
print("=" * 80)

pituitary_tables = []

for file_path in downloaded_metadata:

    df = inspect_table(
        file_path
    )

    if df is not None:

        pituitary_tables.append({

            "file": file_path,

            "rows": len(df),

            "columns": [
                str(c)
                for c in df.columns
            ],

            "missing": {
                str(c): int(
                    df[c].isna().sum()
                )
                for c in df.columns
            },

            "duplicate_rows": int(
                df.duplicated().sum()
            )
        })

# =============================================================================
# SEARCH ALL ZENODO FILES FOR SMALL TABULAR FILES
# =============================================================================

print()
print("=" * 80)
print("SEARCHING ALL SMALL TABULAR FILES")
print("=" * 80)

tabular_extensions = [
    ".csv",
    ".tsv",
    ".xlsx",
    ".xls",
    ".json"
]

small_tabular_files = []

for item in zenodo_files:

    suffix = Path(
        item["key"]
    ).suffix.lower()

    if suffix in tabular_extensions:

        size_mb = item["size_mb"]

        if (
            size_mb is None
            or size_mb <= 500
        ):

            small_tabular_files.append(
                item
            )

            print(
                item["key"],
                "|",
                f"{size_mb:.2f} MB"
                if size_mb is not None
                else "unknown"
            )

# =============================================================================
# SYNAPSE STATUS
# =============================================================================

print()
print("=" * 80)
print("BRATS / SYNAPSE DATASETS")
print("=" * 80)

synapse_inventory = [

    {
        "dataset":
            "BraTS Pre-operative Meningioma",

        "expected_cases":
            1141,

        "clinical_fields":
            [
                "age",
                "sex",
                "CNS WHO grade"
            ],

        "requires_authentication":
            True,

        "large_mri_download":
            False
    },

    {
        "dataset":
            "BraTS-MEN-RT",

        "expected_cases":
            570,

        "clinical_fields":
            [
                "age",
                "sex",
                "WHO grade"
            ],

        "requires_authentication":
            True,

        "large_mri_download":
            False
    }
]

for dataset in synapse_inventory:

    print()
    print(
        dataset["dataset"]
    )

    print(
        "Expected cases:",
        dataset["expected_cases"]
    )

    print(
        "Clinical fields:",
        dataset["clinical_fields"]
    )

    print(
        "Authentication:",
        dataset["requires_authentication"]
    )

    print(
        "MRI download:",
        dataset["large_mri_download"]
    )

print()
print("""
Synapse authentication is intentionally NOT requested in this step.

If clinical metadata is publicly accessible, we will use it.

If authentication is required, we will stop and ask for the
official credentials/access method rather than bypassing access controls.
""")

# =============================================================================
# PITNET STATUS
# =============================================================================

print()
print("=" * 80)
print("PITNET CLINICAL DATASET")
print("=" * 80)

print("""
The Mendeley landing page returned HTTP 403.

We will not bypass the access restriction.

The dataset remains pending until an official downloadable
file or alternate official repository is identified.
""")

# =============================================================================
# TARGET FIELD DETECTION
# =============================================================================

print()
print("=" * 80)
print("CLINICAL FIELD DETECTION")
print("=" * 80)

target_keywords = {

    "age": [
        "age",
        "patient_age"
    ],

    "sex": [
        "sex",
        "gender"
    ],

    "tumor_type": [
        "tumor_type",
        "tumour_type",
        "diagnosis",
        "diagnosis_type",
        "pathology"
    ],

    "who_grade": [
        "who_grade",
        "cns_who_grade",
        "grade",
        "who"
    ],

    "hormone_pattern": [
        "hormone",
        "hormonal",
        "hormone_pattern"
    ],

    "clinical_phenotype": [
        "phenotype",
        "clinical_phenotype"
    ],

    "ki67": [
        "ki67",
        "ki-67",
        "ki_67"
    ],

    "treatment": [
        "treatment",
        "therapy",
        "management",
        "surgery",
        "radiotherapy",
        "radiation"
    ],

    "medication": [
        "medication",
        "drug",
        "prescription",
        "medicine"
    ]
}

detected_fields = []

for table in pituitary_tables:

    columns = [
        c.lower().strip()
        for c in table["columns"]
    ]

    matches = {}

    for target, keywords in target_keywords.items():

        matched = []

        for column in columns:

            if any(
                keyword in column
                for keyword in keywords
            ):

                matched.append(
                    column
                )

        if matched:

            matches[target] = matched

    detected_fields.append({

        "file":
            table["file"],

        "matches":
            matches
    })

# =============================================================================
# SAVE AUDIT
# =============================================================================

audit = {

    "timestamp":
        datetime.now().isoformat(),

    "storage": {

        "colab_free_gb":
            round(
                colab["free_gb"],
                2
            ),

        "drive_free_gb":
            round(
                drive["free_gb"],
                2
            )
    },

    "zenodo": {

        "record_id":
            ZENODO_RECORD_ID,

        "record_url":
            f"https://zenodo.org/records/{ZENODO_RECORD_ID}",

        "files":
            zenodo_files,

        "candidate_metadata_files":
            candidate_files,

        "downloaded_metadata":
            downloaded_metadata,

        "tables":
            pituitary_tables,

        "detected_fields":
            detected_fields
    },

    "synapse": synapse_inventory,

    "pitnet": {

        "status":
            "PENDING_OFFICIAL_DOWNLOAD"
    },

    "large_mri_downloaded":
        False,

    "prescription_training_started":
        False
}

audit_path = (
    AUDIT_ROOT /
    "step4_clinical_metadata_schema_audit.json"
)

with open(
    audit_path,
    "w"
) as f:

    json.dump(
        audit,
        f,
        indent=2
    )

# =============================================================================
# FINAL STATUS
# =============================================================================

print()
print("=" * 80)
print("MODEL 5 - STEP 4 COMPLETE")
print("=" * 80)

print()
print(
    "Zenodo files discovered:",
    len(zenodo_files)
)

print(
    "Metadata candidates:",
    len(candidate_files)
)

print(
    "Downloaded metadata:",
    len(downloaded_metadata)
)

print(
    "Inspected tables:",
    len(pituitary_tables)
)

print()
print(
    "Large MRI downloaded:"
)
print("❌ NO")

print()
print(
    "Prescription model trained:"
)
print("❌ NO")

print()
print("Audit:")
print(audit_path)

print()
print("=" * 80)
print("NEXT")
print("=" * 80)

if pituitary_tables:

    print("""
STEP 5 → BUILD UNIFIED CLINICAL DATASET

We now have actual columns to work with.
""")

else:

    print("""
STEP 5 → RESOLVE DATASET DOWNLOAD FILES

No usable clinical table was discovered automatically.
We must identify the actual downloadable metadata file
before constructing the training dataset.
""")

print("=" * 80)

================================================================================
MODEL 5 - STEP 4
CLINICAL METADATA DOWNLOAD + SCHEMA INSPECTION
================================================================================

================================================================================
STORAGE
================================================================================
Colab free : 65.42 GB
Drive free : 62.15 GB
✅ STORAGE SAFETY CHECK PASSED

================================================================================
DATASET 1
PITUITARY NEUROENDOCRINE TUMOR MRI DATASET
================================================================================

Querying Zenodo API:
https://zenodo.org/api/records/18553150

HTTP status: 200
✅ Zenodo API response received

================================================================================
FILES AVAILABLE IN ZENODO RECORD
================================================================================

File: 06-Mapping Pituitary.pdf
Size: 1.31 MB
URL: https://zenodo.org/api/records/18553150/files/06-Mapping%20Pituitary.pdf/content

================================================================================
SEARCHING FOR CLINICAL / METADATA FILES
================================================================================
⚠️ No obvious metadata filename found.

================================================================================
DOWNLOADING SMALL METADATA CANDIDATES
================================================================================

================================================================================
INSPECTING DOWNLOADED PITUITARY METADATA
================================================================================

================================================================================
SEARCHING ALL SMALL TABULAR FILES
================================================================================

================================================================================
BRATS / SYNAPSE DATASETS
================================================================================

BraTS Pre-operative Meningioma
Expected cases: 1141
Clinical fields: ['age', 'sex', 'CNS WHO grade']
Authentication: True
MRI download: False

BraTS-MEN-RT
Expected cases: 570
Clinical fields: ['age', 'sex', 'WHO grade']
Authentication: True
MRI download: False


Synapse authentication is intentionally NOT requested in this step.

If clinical metadata is publicly accessible, we will use it.

If authentication is required, we will stop and ask for the
official credentials/access method rather than bypassing access controls.


================================================================================
PITNET CLINICAL DATASET
================================================================================

The Mendeley landing page returned HTTP 403.

We will not bypass the access restriction.

The dataset remains pending until an official downloadable
file or alternate official repository is identified.


================================================================================
CLINICAL FIELD DETECTION
================================================================================

================================================================================
MODEL 5 - STEP 4 COMPLETE
================================================================================

Zenodo files discovered: 1
Metadata candidates: 0
Downloaded metadata: 0
Inspected tables: 0

Large MRI downloaded:
❌ NO

Prescription model trained:
❌ NO

Audit:
/content/drive/MyDrive/Model5/audit/dataset/step4_clinical_metadata_schema_audit.json

================================================================================
NEXT
================================================================================

STEP 5 → RESOLVE DATASET DOWNLOAD FILES

No usable clinical table was discovered automatically.
We must identify the actual downloadable metadata file
before constructing the training dataset.

================================================================================

In [5]:
# =============================================================================
# MODEL 5 - STEP 5
# UNIFIED CLINICAL DATASET CONSTRUCTION
# =============================================================================

import os
import json
import shutil
import pandas as pd
import numpy as np
from pathlib import Path
from datetime import datetime

print("=" * 80)
print("MODEL 5 - STEP 5")
print("UNIFIED CLINICAL DATASET CONSTRUCTION")
print("=" * 80)

# =============================================================================
# PATHS
# =============================================================================

DRIVE_ROOT = Path("/content/drive/MyDrive/Model5")

CLINICAL_ROOT = DRIVE_ROOT / "data" / "clinical"
PROCESSED_ROOT = DRIVE_ROOT / "data" / "processed"
AUDIT_ROOT = DRIVE_ROOT / "audit" / "dataset"

for p in [
    CLINICAL_ROOT,
    PROCESSED_ROOT,
    AUDIT_ROOT
]:
    p.mkdir(parents=True, exist_ok=True)

# =============================================================================
# STORAGE
# =============================================================================

def get_storage(path):
    u = shutil.disk_usage(path)

    return {
        "total": u.total / (1024 ** 3),
        "used": u.used / (1024 ** 3),
        "free": u.free / (1024 ** 3)
    }

colab = get_storage("/content")
drive = get_storage("/content/drive")

print()
print("=" * 80)
print("STORAGE")
print("=" * 80)

print(
    f"Colab free : {colab['free']:.2f} GB"
)

print(
    f"Drive free : {drive['free']:.2f} GB"
)

print("✅ STORAGE CHECK PASSED")

# =============================================================================
# FINAL MODEL 5 INPUT SCHEMA
# =============================================================================

print()
print("=" * 80)
print("MODEL 5 INPUT SCHEMA")
print("=" * 80)

schema = {

    "identity": [
        "patient_id",
        "case_id",
        "dataset"
    ],

    "demographics": [
        "age",
        "sex"
    ],

    "tumor": [
        "tumor_type",
        "WHO_grade",
        "pathological_classification",
        "clinical_phenotype",
        "cell_lineage",
        "cell_type",
        "Ki67"
    ],

    "Model4A_measurements": [
        "tumor_detected",
        "tumor_area_pixels",
        "tumor_area_percent",
        "tumor_width_pixels",
        "tumor_height_pixels",
        "centroid_x",
        "centroid_y",
        "boundary_pixels"
    ],

    "clinical": [
        "symptoms",
        "neurological_symptoms",
        "hormone_pattern",
        "previous_treatment",
        "known_diagnosis"
    ],

    "targets": [
        "recommendation_category",
        "recommended_specialist",
        "recommended_next_step",
        "follow_up_category"
    ]
}

for group, fields in schema.items():

    print()
    print(group.upper())

    for field in fields:
        print(" -", field)

# =============================================================================
# TARGET POLICY
# =============================================================================

print()
print("=" * 80)
print("TARGET POLICY")
print("=" * 80)

target_policy = {

    "recommendation_category": {
        "status": "PENDING_LABEL_VALIDATION",
        "description": (
            "High-level clinical management/recommendation category."
        )
    },

    "recommended_specialist": {
        "status": "PENDING_LABEL_VALIDATION",
        "description": (
            "Appropriate clinical specialty for further evaluation."
        )
    },

    "recommended_next_step": {
        "status": "PENDING_LABEL_VALIDATION",
        "description": (
            "Recommended next clinical evaluation/action category."
        )
    },

    "follow_up_category": {
        "status": "PENDING_LABEL_VALIDATION",
        "description": (
            "General follow-up category."
        )
    },

    "specific_medication": {
        "status": "EXCLUDED",
        "reason": (
            "No validated prescription labels in the current datasets."
        )
    },

    "drug_dosage": {
        "status": "EXCLUDED"
    },

    "drug_frequency": {
        "status": "EXCLUDED"
    },

    "drug_duration": {
        "status": "EXCLUDED"
    }
}

for target, info in target_policy.items():

    print()
    print(target)

    for key, value in info.items():
        print(
            f"  {key}: {value}"
        )

# =============================================================================
# DATASET DEFINITIONS
# =============================================================================

datasets = {

    "brats_meningioma": {

        "dataset_name":
            "BraTS Pre-operative Meningioma",

        "tumor_type":
            "meningioma",

        "public_cases":
            1141,

        "clinical_fields": [
            "age",
            "sex",
            "CNS WHO grade"
        ],

        "metadata_source":
            "Synapse",

        "metadata_file":
            "Meningioma supplementary clinical data and imaging parameters for training and validation sets.xlsx",

        "status":
            "AWAITING_FILE"
    },

    "brats_men_rt": {

        "dataset_name":
            "BraTS-MEN-RT",

        "tumor_type":
            "meningioma",

        "public_cases":
            570,

        "clinical_fields": [
            "age",
            "sex",
            "WHO grade",
            "image parameters"
        ],

        "metadata_source":
            "Synapse",

        "metadata_file":
            "Meningioma radiotherapy supplementary clinical data and imaging parameters for training and validation sets.xlsx",

        "status":
            "AWAITING_FILE"
    },

    "pituitary": {

        "dataset_name":
            "Pituitary Neuroendocrine Tumor MRI Dataset",

        "tumor_type":
            "pituitary_tumor",

        "public_cases":
            136,

        "clinical_fields": [
            "age",
            "sex",
            "clinical phenotype",
            "cell lineage",
            "cell type",
            "Ki-67"
        ],

        "metadata_source":
            "Zenodo / publication",

        "status":
            "METADATA_FILE_NOT_EXPOSED"
    }
}

# =============================================================================
# LOOK FOR SYNAPSE FILES ALREADY PRESENT
# =============================================================================

print()
print("=" * 80)
print("SEARCHING LOCAL FILES FOR CLINICAL METADATA")
print("=" * 80)

search_terms = [
    "Meningioma supplementary clinical",
    "Meningioma radiotherapy supplementary clinical",
    "clinical",
    "metadata",
    "meningioma"
]

local_files = []

for root in [
    Path("/content/Model5"),
    CLINICAL_ROOT
]:

    if root.exists():

        for path in root.rglob("*"):

            if path.is_file():

                local_files.append(path)

print(
    "Files found:",
    len(local_files)
)

candidate_local = []

for path in local_files:

    name = path.name.lower()

    if any(
        term.lower() in name
        for term in search_terms
    ):

        candidate_local.append(path)

        print(
            "Candidate:",
            path
        )

if not candidate_local:

    print(
        "No clinical metadata files found locally."
    )

# =============================================================================
# TABLE NORMALIZATION FUNCTION
# =============================================================================

def normalize_column_name(name):

    name = str(name).strip().lower()

    replacements = {
        " ": "_",
        "-": "_",
        "/": "_",
        "(": "",
        ")": "",
        ".": "_"
    }

    for old, new in replacements.items():
        name = name.replace(old, new)

    while "__" in name:
        name = name.replace("__", "_")

    return name


def inspect_and_normalize_excel(path):

    print()
    print("=" * 80)
    print("INSPECTING EXCEL")
    print("=" * 80)

    print("File:", path)

    try:

        excel = pd.ExcelFile(path)

        print()
        print("Sheets:")

        for sheet in excel.sheet_names:
            print(" -", sheet)

        all_tables = {}

        for sheet in excel.sheet_names:

            df = pd.read_excel(
                path,
                sheet_name=sheet
            )

            print()
            print("-" * 80)
            print("SHEET:", sheet)
            print("-" * 80)

            print(
                "Rows:",
                len(df)
            )

            print(
                "Columns:",
                len(df.columns)
            )

            print()
            print("Original columns:")

            for c in df.columns:
                print(" -", c)

            normalized = df.copy()

            normalized.columns = [
                normalize_column_name(c)
                for c in normalized.columns
            ]

            print()
            print("Normalized columns:")

            for c in normalized.columns:
                print(" -", c)

            print()
            print("Missing values:")

            missing = normalized.isna().sum()

            for c, n in missing.items():

                if n > 0:

                    print(
                        f" - {c}: {n}"
                    )

            print()
            print("Duplicate rows:")
            print(
                normalized.duplicated().sum()
            )

            display(
                normalized.head(5)
            )

            all_tables[sheet] = normalized

        return all_tables

    except Exception as e:

        print()
        print(
            "❌ Excel inspection failed:"
        )

        print(
            str(e)[:2000]
        )

        return None

# =============================================================================
# PROCESS ANY LOCALLY FOUND EXCEL FILE
# =============================================================================

normalized_tables = {}

for path in candidate_local:

    if path.suffix.lower() in [
        ".xlsx",
        ".xls"
    ]:

        result = inspect_and_normalize_excel(
            path
        )

        if result is not None:

            normalized_tables[str(path)] = result

# =============================================================================
# UNIFIED DATASET BUILDER
# =============================================================================

print()
print("=" * 80)
print("UNIFIED DATASET BUILDER")
print("=" * 80)

canonical_columns = [

    "patient_id",
    "case_id",
    "dataset",

    "age",
    "sex",

    "tumor_type",
    "WHO_grade",

    "pathological_classification",
    "clinical_phenotype",

    "cell_lineage",
    "cell_type",
    "Ki67",

    "symptoms",
    "neurological_symptoms",

    "hormone_pattern",

    "previous_treatment",
    "known_diagnosis",

    "tumor_detected",
    "tumor_area_pixels",
    "tumor_area_percent",

    "tumor_width_pixels",
    "tumor_height_pixels",

    "centroid_x",
    "centroid_y",

    "boundary_pixels",

    "recommendation_category",
    "recommended_specialist",
    "recommended_next_step",
    "follow_up_category"
]

print(
    "Canonical columns:",
    len(canonical_columns)
)

# =============================================================================
# CREATE EMPTY DATASET IF METADATA IS NOT YET AVAILABLE
# =============================================================================

empty_df = pd.DataFrame(
    columns=canonical_columns
)

empty_path = (
    PROCESSED_ROOT /
    "model5_unified_clinical_dataset_pending.csv"
)

empty_df.to_csv(
    empty_path,
    index=False
)

print()
print(
    "Placeholder schema saved:"
)

print(
    empty_path
)

# =============================================================================
# VALIDATION RULES
# =============================================================================

validation_rules = {

    "patient_id": {
        "required": True,
        "unique_within_dataset": True
    },

    "case_id": {
        "required": True
    },

    "age": {
        "range": [
            0,
            120
        ]
    },

    "sex": {
        "allowed": [
            "male",
            "female",
            "unknown"
        ]
    },

    "WHO_grade": {
        "allowed": [
            1,
            2,
            3,
            "1",
            "2",
            "3",
            "unknown"
        ]
    },

    "tumor_area_percent": {
        "range": [
            0,
            100
        ]
    }
}

# =============================================================================
# AUDIT
# =============================================================================

audit = {

    "timestamp":
        datetime.now().isoformat(),

    "step":
        "5",

    "datasets":
        datasets,

    "schema":
        schema,

    "canonical_columns":
        canonical_columns,

    "target_policy":
        target_policy,

    "validation_rules":
        validation_rules,

    "local_metadata_files":
        [
            str(x)
            for x in candidate_local
        ],

    "normalized_tables":
        list(normalized_tables.keys()),

    "unified_dataset_rows":
        0,

    "training_ready":
        False,

    "reason_not_training_ready":
        (
            "Actual case-level clinical metadata must be acquired "
            "and inspected before labels/targets can be constructed."
        )
}

audit_path = (
    AUDIT_ROOT /
    "step5_unified_clinical_dataset_audit.json"
)

with open(
    audit_path,
    "w"
) as f:

    json.dump(
        audit,
        f,
        indent=2
    )

# =============================================================================
# FINAL STATUS
# =============================================================================

print()
print("=" * 80)
print("MODEL 5 - STEP 5 COMPLETE")
print("=" * 80)

print()
print("Canonical schema:")
print("✅ CREATED")

print()
print("Clinical metadata:")
print(
    "✅ FOUND LOCALLY"
    if candidate_local
    else "⏳ STILL REQUIRED"
)

print()
print("Prescription labels:")
print("❌ NOT AVAILABLE")

print()
print("Training:")
print("❌ NOT STARTED")

print()
print("Unified dataset:")
print(
    empty_path
)

print()
print("Audit:")
print(
    audit_path
)

print()
print("=" * 80)

if candidate_local:

    print(
        "NEXT → STEP 6"
    )

    print(
        "CLINICAL TABLE NORMALIZATION + LABEL VALIDATION"
    )

else:

    print(
        "NEXT → STEP 5B"
    )

    print(
        "DOWNLOAD THE OFFICIAL SYNAPSE CLINICAL METADATA FILES"
    )

print("=" * 80)

================================================================================
MODEL 5 - STEP 5
UNIFIED CLINICAL DATASET CONSTRUCTION
================================================================================

================================================================================
STORAGE
================================================================================
Colab free : 65.42 GB
Drive free : 62.15 GB
✅ STORAGE CHECK PASSED

================================================================================
MODEL 5 INPUT SCHEMA
================================================================================

IDENTITY
 - patient_id
 - case_id
 - dataset

DEMOGRAPHICS
 - age
 - sex

TUMOR
 - tumor_type
 - WHO_grade
 - pathological_classification
 - clinical_phenotype
 - cell_lineage
 - cell_type
 - Ki67

MODEL4A_MEASUREMENTS
 - tumor_detected
 - tumor_area_pixels
 - tumor_area_percent
 - tumor_width_pixels
 - tumor_height_pixels
 - centroid_x
 - centroid_y
 - boundary_pixels

CLINICAL
 - symptoms
 - neurological_symptoms
 - hormone_pattern
 - previous_treatment
 - known_diagnosis

TARGETS
 - recommendation_category
 - recommended_specialist
 - recommended_next_step
 - follow_up_category

================================================================================
TARGET POLICY
================================================================================

recommendation_category
  status: PENDING_LABEL_VALIDATION
  description: High-level clinical management/recommendation category.

recommended_specialist
  status: PENDING_LABEL_VALIDATION
  description: Appropriate clinical specialty for further evaluation.

recommended_next_step
  status: PENDING_LABEL_VALIDATION
  description: Recommended next clinical evaluation/action category.

follow_up_category
  status: PENDING_LABEL_VALIDATION
  description: General follow-up category.

specific_medication
  status: EXCLUDED
  reason: No validated prescription labels in the current datasets.

drug_dosage
  status: EXCLUDED

drug_frequency
  status: EXCLUDED

drug_duration
  status: EXCLUDED

================================================================================
SEARCHING LOCAL FILES FOR CLINICAL METADATA
================================================================================
Files found: 1
No clinical metadata files found locally.

================================================================================
UNIFIED DATASET BUILDER
================================================================================
Canonical columns: 29

Placeholder schema saved:
/content/drive/MyDrive/Model5/data/processed/model5_unified_clinical_dataset_pending.csv

================================================================================
MODEL 5 - STEP 5 COMPLETE
================================================================================

Canonical schema:
✅ CREATED

Clinical metadata:
⏳ STILL REQUIRED

Prescription labels:
❌ NOT AVAILABLE

Training:
❌ NOT STARTED

Unified dataset:
/content/drive/MyDrive/Model5/data/processed/model5_unified_clinical_dataset_pending.csv

Audit:
/content/drive/MyDrive/Model5/audit/dataset/step5_unified_clinical_dataset_audit.json

================================================================================
NEXT → STEP 5B
DOWNLOAD THE OFFICIAL SYNAPSE CLINICAL METADATA FILES
================================================================================

In [6]:
# =============================================================================
# MODEL 5 - STEP 5B
# OFFICIAL CLINICAL METADATA ACQUISITION
# =============================================================================

import os
import json
import shutil
import requests
import pandas as pd
from pathlib import Path
from datetime import datetime

print("=" * 80)
print("MODEL 5 - STEP 5B")
print("OFFICIAL CLINICAL METADATA ACQUISITION")
print("=" * 80)

# =============================================================================
# PATHS
# =============================================================================

DRIVE_ROOT = Path("/content/drive/MyDrive/Model5")

CLINICAL_ROOT = DRIVE_ROOT / "data" / "clinical"
AUDIT_ROOT = DRIVE_ROOT / "audit" / "dataset"

CLINICAL_ROOT.mkdir(parents=True, exist_ok=True)
AUDIT_ROOT.mkdir(parents=True, exist_ok=True)

# =============================================================================
# OFFICIAL SYNAPSE FILES
# =============================================================================

FILES = {
    "brats_meningioma": {
        "synapse_id": "syn58633127",
        "name": (
            "Meningioma supplementary clinical data "
            "and imaging parameters for training and "
            "validation sets.xlsx"
        ),
        "url": (
            "https://www.synapse.org/"
            "Synapse:syn58633127"
        )
    },

    "brats_men_rt": {
        "synapse_id": "syn65415290",
        "name": (
            "Meningioma radiotherapy supplementary clinical "
            "data and imaging parameters for training and "
            "validation sets.xlsx"
        ),
        "url": (
            "https://www.synapse.org/"
            "Synapse:syn65415290"
        )
    }
}

print()
print("=" * 80)
print("OFFICIAL METADATA FILES")
print("=" * 80)

for key, info in FILES.items():

    print()
    print(key)

    print("Synapse ID :", info["synapse_id"])
    print("File       :", info["name"])
    print("Source     :", info["url"])

# =============================================================================
# TRY SYNAPSE DOWNLOAD API
# =============================================================================

def download_synapse_file(synapse_id, destination):

    destination = Path(destination)

    destination.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    # Synapse file download endpoint
    url = (
        "https://www.synapse.org/"
        f"File:{synapse_id}"
    )

    print()
    print("Attempting:")
    print(url)

    try:

        response = requests.get(
            url,
            allow_redirects=True,
            timeout=60,
            headers={
                "User-Agent":
                    "Mozilla/5.0 Model5-Clinical-Audit"
            }
        )

        print(
            "HTTP status:",
            response.status_code
        )

        content_type = response.headers.get(
            "content-type",
            ""
        )

        print(
            "Content-Type:",
            content_type
        )

        # Safety check:
        # We only want an Excel file.
        if (
            "spreadsheet" not in content_type.lower()
            and "excel" not in content_type.lower()
            and not response.url.lower().endswith(
                (".xlsx", ".xls")
            )
        ):

            print(
                "⚠️ Response does not appear to be an Excel file."
            )

            print(
                "Final URL:",
                response.url
            )

            return False

        if response.status_code != 200:

            print(
                "❌ Synapse did not provide the file."
            )

            return False

        with open(
            destination,
            "wb"
        ) as f:

            f.write(
                response.content
            )

        print()
        print("✅ File downloaded")
        print("Saved:", destination)

        print(
            "Size:",
            round(
                destination.stat().st_size
                / (1024 ** 2),
                3
            ),
            "MB"
        )

        return True

    except Exception as e:

        print()
        print("⚠️ Synapse direct download failed")
        print(str(e)[:2000])

        return False

# =============================================================================
# DOWNLOAD BOTH METADATA FILES
# =============================================================================

download_results = {}

for key, info in FILES.items():

    destination = (
        CLINICAL_ROOT /
        f"{key}_clinical_metadata.xlsx"
    )

    success = download_synapse_file(
        info["synapse_id"],
        destination
    )

    download_results[key] = {
        "success": success,
        "path": str(destination)
    }

# =============================================================================
# INSPECT DOWNLOADED EXCEL
# =============================================================================

def inspect_excel(path, dataset_name):

    path = Path(path)

    if not path.exists():

        print()
        print(
            f"❌ File missing: {path}"
        )

        return None

    print()
    print("=" * 80)
    print(
        f"INSPECTING {dataset_name.upper()}"
    )
    print("=" * 80)

    print("File:", path)

    try:

        excel = pd.ExcelFile(path)

        print()
        print("Sheets:")

        for sheet in excel.sheet_names:

            print(
                " -",
                sheet
            )

        result = {}

        for sheet in excel.sheet_names:

            print()
            print("-" * 80)
            print(
                "SHEET:",
                sheet
            )
            print("-" * 80)

            df = pd.read_excel(
                path,
                sheet_name=sheet
            )

            print(
                "Rows:",
                len(df)
            )

            print(
                "Columns:",
                len(df.columns)
            )

            print()
            print("Columns:")

            for column in df.columns:

                print(
                    " -",
                    column,
                    "|",
                    str(df[column].dtype),
                    "| missing:",
                    int(df[column].isna().sum())
                )

            print()
            print(
                "Duplicate rows:",
                int(df.duplicated().sum())
            )

            print()
            print("Preview:")

            display(
                df.head(10)
            )

            # Store compact audit information
            result[sheet] = {

                "rows":
                    int(len(df)),

                "columns":
                    [
                        str(c)
                        for c in df.columns
                    ],

                "missing":
                    {
                        str(c):
                            int(df[c].isna().sum())
                        for c in df.columns
                    },

                "duplicate_rows":
                    int(
                        df.duplicated().sum()
                    )
            }

        return result

    except Exception as e:

        print()
        print(
            "❌ Excel inspection failed"
        )

        print(
            str(e)[:3000]
        )

        return None

# =============================================================================
# INSPECT FILES
# =============================================================================

inspection_results = {}

for key, result in download_results.items():

    if result["success"]:

        inspection_results[key] = inspect_excel(
            result["path"],
            key
        )

# =============================================================================
# SEARCH FOR CLINICAL / TREATMENT VARIABLES
# =============================================================================

print()
print("=" * 80)
print("CLINICAL FIELD SEARCH")
print("=" * 80)

clinical_keywords = {

    "age": [
        "age",
        "patient_age"
    ],

    "sex": [
        "sex",
        "gender"
    ],

    "who_grade": [
        "who",
        "grade",
        "cns_who"
    ],

    "treatment": [
        "treatment",
        "therapy",
        "radiotherapy",
        "radiation",
        "surgery",
        "surgical"
    ],

    "medication": [
        "medication",
        "drug",
        "prescription",
        "medicine"
    ],

    "outcome": [
        "outcome",
        "survival",
        "follow_up",
        "followup",
        "recurrence",
        "progression"
    ]
}

field_matches = {}

for dataset_key, sheets in inspection_results.items():

    field_matches[dataset_key] = {}

    for sheet_name, info in sheets.items():

        columns = [
            str(c).lower()
            for c in info["columns"]
        ]

        matches = {}

        for field, keywords in clinical_keywords.items():

            found = []

            for column in columns:

                if any(
                    keyword in column
                    for keyword in keywords
                ):

                    found.append(
                        column
                    )

            if found:
                matches[field] = found

        field_matches[dataset_key][
            sheet_name
        ] = matches

        print()
        print(
            dataset_key,
            "→",
            sheet_name
        )

        if matches:

            for field, columns_found in matches.items():

                print(
                    f"  {field}:",
                    columns_found
                )

        else:

            print(
                "  No recognized clinical fields."
            )

# =============================================================================
# SAVE METADATA AUDIT
# =============================================================================

audit = {

    "timestamp":
        datetime.now().isoformat(),

    "official_sources":
        FILES,

    "download_results":
        download_results,

    "inspection_results":
        inspection_results,

    "field_matches":
        field_matches,

    "large_mri_downloaded":
        False,

    "prescription_model_started":
        False,

    "treatment_labels_validated":
        False
}

audit_path = (
    AUDIT_ROOT /
    "step5b_official_clinical_metadata_audit.json"
)

with open(
    audit_path,
    "w"
) as f:

    json.dump(
        audit,
        f,
        indent=2
    )

# =============================================================================
# FINAL STATUS
# =============================================================================

print()
print("=" * 80)
print("MODEL 5 - STEP 5B COMPLETE")
print("=" * 80)

for key, result in download_results.items():

    print()
    print(
        key,
        ":",
        "✅ DOWNLOADED"
        if result["success"]
        else "⚠️ NOT DOWNLOADED"
    )

print()
print("Large MRI:")
print("❌ NOT DOWNLOADED")

print()
print("Prescription labels:")
print("❌ NOT ASSUMED")

print()
print("Audit:")
print(audit_path)

print()
print("=" * 80)

if any(
    x["success"]
    for x in download_results.values()
):

    print(
        "NEXT → STEP 6"
    )

    print(
        "NORMALIZE CLINICAL TABLES + VALIDATE ACTUAL LABELS"
    )

else:

    print(
        "NEXT → STEP 5C"
    )

    print(
        "SYNAPSE AUTHENTICATION / OFFICIAL FILE ACCESS"
    )

print("=" * 80)

================================================================================
MODEL 5 - STEP 5B
OFFICIAL CLINICAL METADATA ACQUISITION
================================================================================

================================================================================
OFFICIAL METADATA FILES
================================================================================

brats_meningioma
Synapse ID : syn58633127
File       : Meningioma supplementary clinical data and imaging parameters for training and validation sets.xlsx
Source     : https://www.synapse.org/Synapse:syn58633127

brats_men_rt
Synapse ID : syn65415290
File       : Meningioma radiotherapy supplementary clinical data and imaging parameters for training and validation sets.xlsx
Source     : https://www.synapse.org/Synapse:syn65415290

Attempting:
https://www.synapse.org/File:syn58633127
HTTP status: 200
Content-Type: text/html;charset=UTF-8
⚠️ Response does not appear to be an Excel file.
Final URL: https://www.synapse.org/File:syn58633127

Attempting:
https://www.synapse.org/File:syn65415290
HTTP status: 200
Content-Type: text/html;charset=UTF-8
⚠️ Response does not appear to be an Excel file.
Final URL: https://www.synapse.org/File:syn65415290

================================================================================
CLINICAL FIELD SEARCH
================================================================================

================================================================================
MODEL 5 - STEP 5B COMPLETE
================================================================================

brats_meningioma : ⚠️ NOT DOWNLOADED

brats_men_rt : ⚠️ NOT DOWNLOADED

Large MRI:
❌ NOT DOWNLOADED

Prescription labels:
❌ NOT ASSUMED

Audit:
/content/drive/MyDrive/Model5/audit/dataset/step5b_official_clinical_metadata_audit.json

================================================================================
NEXT → STEP 5C
SYNAPSE AUTHENTICATION / OFFICIAL FILE ACCESS
================================================================================

In [7]:
!pip -q install synapseclient

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 836.8/836.8 kB 32.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.5/72.5 kB 8.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 204.6/204.6 kB 20.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 kB 6.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.2/137.2 kB 16.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.6/155.6 kB 18.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 8.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 818.2/818.2 kB 61.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.1/131.1 kB 15.8 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.
torch 2.11.0+cu128 requires setuptools<82, but you have setuptools 84.0.0 which is incompatible.
google-adk 2.7.1 requires opentelemetry-api<=1.42.1,>=1.39, but you have opentelemetry-api 1.44.0 which is incompatible.
google-adk 2.7.1 requires opentelemetry-sdk<=1.42.1,>=1.39, but you have opentelemetry-sdk 1.44.0 which is incompatible.

In [8]:
import synapseclient

syn = synapseclient.Synapse()

print("Synapse client initialized.")
print("Please authenticate using your Synapse credentials.")

Synapse client initialized.
Please authenticate using your Synapse credentials.

In [10]:
import synapseclient

syn = synapseclient.Synapse()

syn.login(
    authToken="YOUR_SYNAPSE_AUTH_TOKEN"
)

print("✅ Synapse authentication successful")

SynapseAuthenticationError: You are not logged in and do not have access to a requested resource.

In [11]:
# =============================================================================
# MODEL 5 - STEP 5C
# PUBLIC CLINICAL METADATA ACQUISITION
# =============================================================================

import requests
import hashlib
import shutil
from pathlib import Path

print("=" * 80)
print("MODEL 5 - STEP 5C")
print("BRAST-MEN-RT CLINICAL METADATA ACQUISITION")
print("=" * 80)

# -------------------------------------------------------------------------
# Paths
# -------------------------------------------------------------------------

OUT_DIR = Path(
    "/content/drive/MyDrive/Model5/data/clinical"
)

OUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

OUTPUT = (
    OUT_DIR /
    "brats_men_rt_clinical_metadata.xlsx"
)

# -------------------------------------------------------------------------
# Public verified file
# -------------------------------------------------------------------------

URL = (
    "https://huggingface.co/datasets/"
    "Spirit-26/BraTS-2024-Complete/resolve/"
    "4f7c0ae04ca93db5b7581789760e8ba54469e7b1/"
    "BraTS-MEN-RT/"
    "Meningioma%20radiotherapy%20supplementary%20clinical%20data%20and%20imaging%20parameters%20for%20training%20and%20validation%20sets%20v2.xlsx"
)

EXPECTED_SHA256 = (
    "3121bee84a9f4f0ec5dfb14d299aec8c00457336ea5c84e56b0cd1bfd04359f0"
)

print()
print("Downloading clinical metadata only...")
print("Expected size: approximately 91.4 KB")

response = requests.get(
    URL,
    timeout=120
)

response.raise_for_status()

with open(OUTPUT, "wb") as f:
    f.write(response.content)

print()
print("Downloaded:")
print(OUTPUT)

# -------------------------------------------------------------------------
# File size
# -------------------------------------------------------------------------

size_kb = OUTPUT.stat().st_size / 1024

print()
print(
    f"File size: {size_kb:.2f} KB"
)

# -------------------------------------------------------------------------
# SHA256
# -------------------------------------------------------------------------

sha256 = hashlib.sha256()

with open(OUTPUT, "rb") as f:

    for chunk in iter(
        lambda: f.read(1024 * 1024),
        b""
    ):
        sha256.update(chunk)

actual_hash = sha256.hexdigest()

print()
print("SHA256:")
print(actual_hash)

print()
if actual_hash == EXPECTED_SHA256:

    print("✅ SHA256 VERIFIED")

else:

    print("❌ SHA256 MISMATCH")
    print("Expected:", EXPECTED_SHA256)
    print("Actual  :", actual_hash)

# -------------------------------------------------------------------------
# Final
# -------------------------------------------------------------------------

print()
print("=" * 80)
print("STEP 5C COMPLETE")
print("=" * 80)

if actual_hash == EXPECTED_SHA256:

    print("✅ Clinical metadata acquired")
    print("✅ File integrity verified")
    print("✅ No MRI downloaded")
    print()
    print("NEXT → STEP 6")
    print("INSPECT EXCEL + NORMALIZE CLINICAL VARIABLES")

else:

    print("❌ DO NOT USE THIS FILE")
    print("Hash verification failed.")

print("=" * 80)

================================================================================
MODEL 5 - STEP 5C
BRAST-MEN-RT CLINICAL METADATA ACQUISITION
================================================================================

Downloading clinical metadata only...
Expected size: approximately 91.4 KB

Downloaded:
/content/drive/MyDrive/Model5/data/clinical/brats_men_rt_clinical_metadata.xlsx

File size: 89.25 KB

SHA256:
3121bee84a9f4f0ec5dfb14d299aec8c00457336ea5c84e56b0cd1bfd04359f0

✅ SHA256 VERIFIED

================================================================================
STEP 5C COMPLETE
================================================================================
✅ Clinical metadata acquired
✅ File integrity verified
✅ No MRI downloaded

NEXT → STEP 6
INSPECT EXCEL + NORMALIZE CLINICAL VARIABLES
================================================================================

In [12]:
# =============================================================================
# MODEL 5 - STEP 6
# CLINICAL METADATA INSPECTION + NORMALIZATION AUDIT
# =============================================================================

import pandas as pd
import numpy as np
import json
from pathlib import Path
from datetime import datetime

print("=" * 80)
print("MODEL 5 - STEP 6")
print("CLINICAL METADATA INSPECTION + NORMALIZATION AUDIT")
print("=" * 80)

# =============================================================================
# PATHS
# =============================================================================

FILE = Path(
    "/content/drive/MyDrive/Model5/data/clinical/"
    "brats_men_rt_clinical_metadata.xlsx"
)

AUDIT_DIR = Path(
    "/content/drive/MyDrive/Model5/audit/dataset"
)

PROCESSED_DIR = Path(
    "/content/drive/MyDrive/Model5/data/processed"
)

AUDIT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

PROCESSED_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# =============================================================================
# FILE CHECK
# =============================================================================

print()
print("=" * 80)
print("FILE CHECK")
print("=" * 80)

if not FILE.exists():
    raise FileNotFoundError(
        f"Clinical metadata file not found:\n{FILE}"
    )

print("File:", FILE)

size_kb = FILE.stat().st_size / 1024

print(
    f"Size: {size_kb:.2f} KB"
)

# =============================================================================
# LOAD EXCEL
# =============================================================================

print()
print("=" * 80)
print("EXCEL STRUCTURE")
print("=" * 80)

excel = pd.ExcelFile(FILE)

print(
    "Number of sheets:",
    len(excel.sheet_names)
)

print()
print("Sheets:")

for i, sheet in enumerate(
    excel.sheet_names,
    start=1
):
    print(
        f"{i}. {sheet}"
    )

# =============================================================================
# INSPECT EVERY SHEET
# =============================================================================

all_sheet_info = {}

for sheet in excel.sheet_names:

    print()
    print("=" * 80)
    print(f"SHEET: {sheet}")
    print("=" * 80)

    df = pd.read_excel(
        FILE,
        sheet_name=sheet
    )

    print()
    print(
        "Rows:",
        len(df)
    )

    print(
        "Columns:",
        len(df.columns)
    )

    print()
    print("COLUMN INFORMATION")
    print("-" * 80)

    column_info = []

    for col in df.columns:

        missing = int(
            df[col].isna().sum()
        )

        unique = int(
            df[col].nunique(
                dropna=True
            )
        )

        dtype = str(
            df[col].dtype
        )

        print(
            f"{str(col):45s} "
            f"dtype={dtype:12s} "
            f"unique={unique:6d} "
            f"missing={missing:6d}"
        )

        column_info.append({
            "column": str(col),
            "dtype": dtype,
            "unique": unique,
            "missing": missing
        })

    # -------------------------------------------------------------------------
    # DUPLICATES
    # -------------------------------------------------------------------------

    duplicate_rows = int(
        df.duplicated().sum()
    )

    print()
    print(
        "Duplicate rows:",
        duplicate_rows
    )

    # -------------------------------------------------------------------------
    # PREVIEW
    # -------------------------------------------------------------------------

    print()
    print("FIRST 10 ROWS")
    print("-" * 80)

    display(
        df.head(10)
    )

    # -------------------------------------------------------------------------
    # VALUE DISTRIBUTIONS
    # -------------------------------------------------------------------------

    print()
    print("CATEGORICAL VALUE DISTRIBUTIONS")
    print("-" * 80)

    categorical_info = {}

    for col in df.columns:

        # Avoid printing huge continuous columns
        nunique = df[col].nunique(
            dropna=True
        )

        if nunique <= 30:

            counts = (
                df[col]
                .value_counts(
                    dropna=False
                )
                .head(30)
            )

            categorical_info[
                str(col)
            ] = {
                str(k): int(v)
                for k, v in counts.items()
            }

            print()
            print(
                str(col)
            )

            print(
                counts.to_string()
            )

    # -------------------------------------------------------------------------
    # NUMERIC SUMMARY
    # -------------------------------------------------------------------------

    print()
    print("NUMERIC SUMMARY")
    print("-" * 80)

    numeric_df = df.select_dtypes(
        include=np.number
    )

    if len(numeric_df.columns) > 0:

        display(
            numeric_df.describe(
                include="all"
            ).T
        )

    else:

        print(
            "No numeric columns detected."
        )

    # -------------------------------------------------------------------------
    # STORE AUDIT
    # -------------------------------------------------------------------------

    all_sheet_info[sheet] = {

        "rows":
            int(len(df)),

        "columns":
            int(len(df.columns)),

        "column_info":
            column_info,

        "duplicate_rows":
            duplicate_rows,

        "categorical_values":
            categorical_info
    }

# =============================================================================
# SEARCH FOR IMPORTANT CLINICAL VARIABLES
# =============================================================================

print()
print("=" * 80)
print("CLINICAL VARIABLE SEARCH")
print("=" * 80)

keywords = {

    "patient_id": [
        "patient",
        "case",
        "subject",
        "id"
    ],

    "age": [
        "age"
    ],

    "sex": [
        "sex",
        "gender"
    ],

    "who_grade": [
        "who",
        "grade",
        "cns"
    ],

    "tumor": [
        "tumor",
        "tumour",
        "meningioma"
    ],

    "radiotherapy": [
        "radiotherapy",
        "radiation",
        "rt"
    ],

    "surgery": [
        "surgery",
        "surgical",
        "resection"
    ],

    "treatment": [
        "treatment",
        "therapy"
    ],

    "medication": [
        "medication",
        "drug",
        "prescription",
        "medicine"
    ],

    "outcome": [
        "outcome",
        "survival",
        "follow",
        "recurrence",
        "progression"
    ]
}

matches = {}

for sheet, info in all_sheet_info.items():

    matches[sheet] = {}

    columns = [
        item["column"]
        for item in info["column_info"]
    ]

    print()
    print(
        f"SHEET: {sheet}"
    )

    for category, terms in keywords.items():

        found = []

        for column in columns:

            column_lower = column.lower()

            if any(
                term in column_lower
                for term in terms
            ):

                found.append(
                    column
                )

        if found:

            matches[sheet][
                category
            ] = found

            print(
                f"  {category:18s}: {found}"
            )

# =============================================================================
# NORMALIZED COLUMN MAP
# =============================================================================

print()
print("=" * 80)
print("NORMALIZATION PREVIEW")
print("=" * 80)

def normalize_column_name(name):

    name = str(name).strip().lower()

    replacements = {
        " ": "_",
        "-": "_",
        "/": "_",
        "\\": "_",
        "(": "",
        ")": "",
        ".": "_",
        ",": ""
    }

    for old, new in replacements.items():
        name = name.replace(
            old,
            new
        )

    while "__" in name:
        name = name.replace(
            "__",
            "_"
        )

    return name.strip("_")

normalization_maps = {}

for sheet in excel.sheet_names:

    df = pd.read_excel(
        FILE,
        sheet_name=sheet
    )

    mapping = {}

    for col in df.columns:

        normalized = normalize_column_name(
            col
        )

        mapping[str(col)] = normalized

        print(
            f"{str(col):50s} → {normalized}"
        )

    normalization_maps[
        sheet
    ] = mapping

# =============================================================================
# SAFETY DECISION
# =============================================================================

print()
print("=" * 80)
print("TARGET SAFETY DECISION")
print("=" * 80)

medication_found = False
treatment_found = False
outcome_found = False

for sheet_matches in matches.values():

    if "medication" in sheet_matches:
        medication_found = True

    if "treatment" in sheet_matches:
        treatment_found = True

    if "outcome" in sheet_matches:
        outcome_found = True

print(
    "Medication-related field found:",
    "YES" if medication_found else "NO"
)

print(
    "Treatment-related field found:",
    "YES" if treatment_found else "NO"
)

print(
    "Outcome-related field found:",
    "YES" if outcome_found else "NO"
)

if medication_found:

    print()
    print(
        "⚠️ Medication-like fields detected."
    )

    print(
        "These MUST be manually verified before"
        " being treated as prescription labels."
    )

else:

    print()
    print(
        "✅ No validated medication prescription"
        " target identified."
    )

# =============================================================================
# SAVE RAW NORMALIZED TABLES
# =============================================================================

print()
print("=" * 80)
print("SAVING NORMALIZED TABLES")
print("=" * 80)

normalized_paths = {}

for sheet in excel.sheet_names:

    df = pd.read_excel(
        FILE,
        sheet_name=sheet
    )

    df = df.copy()

    df.columns = [
        normalize_column_name(c)
        for c in df.columns
    ]

    safe_sheet = normalize_column_name(
        sheet
    )

    output = (
        PROCESSED_DIR /
        f"brats_men_rt_{safe_sheet}.csv"
    )

    df.to_csv(
        output,
        index=False
    )

    normalized_paths[
        sheet
    ] = str(output)

    print(
        "Saved:",
        output
    )

# =============================================================================
# AUDIT JSON
# =============================================================================

audit = {

    "timestamp":
        datetime.now().isoformat(),

    "step":
        "6",

    "source_file":
        str(FILE),

    "file_size_kb":
        round(size_kb, 3),

    "sheets":
        all_sheet_info,

    "clinical_variable_matches":
        matches,

    "normalization_maps":
        normalization_maps,

    "normalized_tables":
        normalized_paths,

    "medication_field_found":
        medication_found,

    "treatment_field_found":
        treatment_found,

    "outcome_field_found":
        outcome_found,

    "prescription_target_validated":
        False,

    "training_ready":
        False
}

audit_path = (
    AUDIT_DIR /
    "step6_clinical_metadata_inspection_audit.json"
)

with open(
    audit_path,
    "w"
) as f:

    json.dump(
        audit,
        f,
        indent=2,
        default=str
    )

# =============================================================================
# FINAL
# =============================================================================

print()
print("=" * 80)
print("MODEL 5 - STEP 6 COMPLETE")
print("=" * 80)

print()
print(
    "Clinical metadata:"
)
print(
    "✅ INSPECTED"
)

print()
print(
    "Normalized tables:"
)
print(
    "✅ SAVED"
)

print()
print(
    "Prescription target:"
)
print(
    "❌ NOT AUTOMATICALLY CREATED"
)

print()
print(
    "Audit:"
)
print(
    audit_path
)

print()
print("=" * 80)
print("NEXT → STEP 7")
print("CLINICAL FEATURE ENGINEERING + TARGET VALIDATION")
print("=" * 80)

================================================================================
MODEL 5 - STEP 6
CLINICAL METADATA INSPECTION + NORMALIZATION AUDIT
================================================================================

================================================================================
FILE CHECK
================================================================================
File: /content/drive/MyDrive/Model5/data/clinical/brats_men_rt_clinical_metadata.xlsx
Size: 89.25 KB

================================================================================
EXCEL STRUCTURE
================================================================================
Number of sheets: 2

Sheets:
1. BraTS-MEN-RT Clinical Data
2. Data Dictionary

================================================================================
SHEET: BraTS-MEN-RT Clinical Data
================================================================================

Rows: 570
Columns: 22

COLUMN INFORMATION
--------------------------------------------------------------------------------
BraTS ID                                      dtype=object       unique=   570 missing=     0
Tumor Grade                                   dtype=float64      unique=     3 missing=   299
Age at MRI (years)                            dtype=float64      unique=    67 missing=    29
Sex                                           dtype=object       unique=     2 missing=    29
T1c x-resolution (mm)                         dtype=float64      unique=    70 missing=     0
T1c y-resolution (mm)                         dtype=float64      unique=    70 missing=     0
T1c Slice Thickness (mm)                      dtype=float64      unique=    73 missing=     0
Scanner Manufacturer                          dtype=object       unique=     6 missing=   201
Scanner Model                                 dtype=object       unique=    21 missing=   203
Magnetic Field Strength (T)                   dtype=float64      unique=     4 missing=   205
Series Description                            dtype=object       unique=    43 missing=   220
Scanning Sequence                             dtype=object       unique=     7 missing=   200
Sequence Variant                              dtype=object       unique=    18 missing=   200
Repitition Time (TR, ms)                      dtype=float64      unique=    48 missing=   375
Echo Time (TE, ms)                            dtype=float64      unique=    49 missing=   375
Inversion Time (TI, ms)                       dtype=float64      unique=    11 missing=   395
Flip Angle (degrees)                          dtype=float64      unique=    11 missing=   375
Acquisition Matrix (rows  columns)            dtype=object       unique=    21 missing=   197
Reconstruction Matrix (rows)                  dtype=float64      unique=    12 missing=   197
Reconstruction Matrix (columns)               dtype=float64      unique=    16 missing=   197
Pixel Bandwidth (Hz)                          dtype=float64      unique=    22 missing=   426
Receive Coil Name                             dtype=object       unique=    10 missing=   442

Duplicate rows: 0

FIRST 10 ROWS
--------------------------------------------------------------------------------

,BraTS ID,Tumor Grade,Age at MRI (years),Sex,T1c x-resolution (mm),T1c y-resolution (mm),T1c Slice Thickness (mm),Scanner Manufacturer,Scanner Model,Magnetic Field Strength (T),...,Sequence Variant,"Repitition Time (TR, ms)","Echo Time (TE, ms)","Inversion Time (TI, ms)",Flip Angle (degrees),Acquisition Matrix (rows columns),Reconstruction Matrix (rows),Reconstruction Matrix (columns),Pixel Bandwidth (Hz),Receive Coil Name
0,BraTS-MEN-RT-0002-1,2.0,65.0,F,1.015600,1.015600,1.500000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BraTS-MEN-RT-0003-1,NaN,60.0,F,0.812500,0.812500,1.000000,Philips Medical Systems,Ingenia,3.0,...,MP,NaN,NaN,NaN,NaN,320x320,320.0,320.0,NaN,NaN
2,BraTS-MEN-RT-0004-1,NaN,24.0,F,0.507812,0.507812,1.099998,Philips Medical Systems,Ingenia,3.0,...,MP,NaN,NaN,NaN,NaN,512x512,512.0,512.0,NaN,NaN
3,BraTS-MEN-RT-0005-1,NaN,59.0,F,0.902778,0.902778,1.000000,Philips Medical Systems,Ingenia,3.0,...,MP,NaN,NaN,NaN,NaN,288x288,288.0,288.0,NaN,NaN
4,BraTS-MEN-RT-0006-1,1.0,70.0,F,0.507800,0.507800,1.400004,GE MEDICAL SYSTEMS,Signa HDxt,1.5,...,"['SS', 'SP', 'SK', 'OSP']",11.22,4.580,400.0,25.0,224x224,512.0,512.0,61.0547,HEAD
5,BraTS-MEN-RT-0007-1,NaN,59.0,F,1.015620,1.015620,1.400004,GE MEDICAL SYSTEMS,SIGNA EXCITE,1.5,...,"['SS', 'SP']",23.00,7.000,0.0,35.0,192x256,256.0,256.0,97.6562,HEAD
6,BraTS-MEN-RT-0009-1,NaN,60.0,M,1.015625,1.015625,2.000000,Philips Medical Systems,Intera,1.5,...,MP,NaN,NaN,NaN,NaN,256x256,256.0,256.0,NaN,NaN
7,BraTS-MEN-RT-0010-1,2.0,76.0,F,0.937500,0.937500,1.000000,GE MEDICAL SYSTEMS,Signa HDxt,1.5,...,SS,7.80,3.180,400.0,14.0,512x512,512.0,512.0,NaN,NaN
8,BraTS-MEN-RT-0011-1,NaN,65.0,F,0.507800,0.507800,1.400004,GE MEDICAL SYSTEMS,Signa HDxt,1.5,...,"['SS', 'SP', 'SK']",12.26,5.124,400.0,25.0,192x256,512.0,512.0,61.0547,HEAD
9,BraTS-MEN-RT-0012-1,2.0,59.0,F,0.488281,0.488281,0.999995,GE MEDICAL SYSTEMS,SIGNA Premier,3.0,...,NONE,2515.32,2.788,1060.0,8.0,512x512,512.0,512.0,122.0700,48HAP

CATEGORICAL VALUE DISTRIBUTIONS
--------------------------------------------------------------------------------

Tumor Grade
Tumor Grade
NaN    299
1.0    169
2.0     85
3.0     17

Sex
Sex
F      360
M      181
NaN     29

Scanner Manufacturer
Scanner Manufacturer
NaN                        201
Philips Medical Systems    163
GE MEDICAL SYSTEMS         107
SIEMENS                     92
Siemens                      4
Philips Healthcare           2
CANON_MEC                    1

Scanner Model
Scanner Model
NaN                 203
Ingenia             117
Signa HDxt           55
Intera               47
SIGNA EXCITE         28
MAGNETOM TrioTim     28
TrioTim              24
Skyra                24
SIGNA Premier         8
Optima MR450w         7
Prisma_fit            5
Symphony              4
MAGNETOM Vida         3
SIGNA Voyager         3
Aera                  3
DISCOVERY MR750       2
SIGNA Artist          2
DISCOVERY MR750w      2
Avanto                2
Achieva               1
Galan 3T              1
MAGNETOM Sola         1

Magnetic Field Strength (T)
Magnetic Field Strength (T)
3.000    218
NaN      205
1.500    145
1.494      1
1.494      1

Scanning Sequence
Scanning Sequence
GR                      285
NaN                     200
['GR', 'IR']             41
Gradient Echo (GGRE)     28
['RM', 'IR']             10
SE                        3
RM                        2
['IR', 'GR']              1

Sequence Variant
Sequence Variant
NaN                              200
MP                               163
['SS', 'SP', 'SK']                61
Spoiled Gradient-Echo (SP-GR)     28
['SS', 'SP']                      28
['SP', 'MP', 'OSP']               21
SK                                20
SP                                11
NONE                              11
['SK', 'SP', 'MP', 'OSP']          6
SS                                 5
['SK', 'SP', 'MP']                 4
['SP', 'MP']                       4
['SS', 'SP', 'SK', 'OSP']          2
['MTC', 'SS', 'OSP']               2
['SP', 'SK']                       1
['SS', 'SK']                       1
['SK', 'SP', 'OSP']                1
['SK', 'SP']                       1

Inversion Time (TI, ms)
Inversion Time (TI, ms)
NaN       395
400.0      49
1100.0     44
900.0      32
0.0        30
1000.0      7
450.0       7
1060.0      2
921.0       1
909.0       1
23.0        1
935.0       1

Flip Angle (degrees)
Flip Angle (degrees)
NaN      375
8.0       49
25.0      46
9.0       32
35.0      28
10.0      13
30.0       9
14.0       5
12.0       5
20.0       5
120.0      2
15.0       1

Acquisition Matrix (rows  columns)
Acquisition Matrix (rows  columns)
NaN        197
256x256     86
512x512     84
192x256     73
672x672     37
704x704     31
288x288     25
320x320      9
768x768      9
248x256      4
224x224      3
174x256      2
352x352      1
336x336      1
256x208      1
256x224      1
512x416      1
252x250      1
512x572      1
300x300      1
720x720      1
800x800      1

Reconstruction Matrix (rows)
Reconstruction Matrix (rows)
NaN      197
512.0    139
256.0    112
672.0     37
704.0     31
288.0     25
768.0      9
320.0      7
230.0      6
352.0      4
336.0      1
800.0      1
720.0      1

Reconstruction Matrix (columns)
Reconstruction Matrix (columns)
NaN      197
512.0    137
256.0    110
672.0     37
704.0     31
288.0     25
768.0      9
320.0      7
230.0      6
352.0      4
336.0      1
224.0      1
416.0      1
208.0      1
572.0      1
800.0      1
720.0      1

Pixel Bandwidth (Hz)
Pixel Bandwidth (Hz)
NaN         426
61.0547      45
97.6562      28
179.0000     21
122.0700     10
130.0000      9
240.0000      6
244.1410      4
238.0000      3
162.7730      2
180.0000      2
250.0000      2
217.0000      2
199.0000      1
75.1172       1
244.0000      1
37.0000       1
122.0705      1
190.0000      1
177.5780      1
750.0000      1
300.0000      1
630.0000      1

Receive Coil Name
Receive Coil Name
NaN                                                    442
HEAD                                                    74
HEA; HEP (Head and Head-Phase coil elements active)     28
48HAP                                                    6
Head 24                                                  5
8HRBRAIN                                                 4
HNS Head                                                 3
MULTI COIL                                               3
HeadNeck_20_TCS                                          3
SENSE-Head-8                                             1
Atlas Head Neck                                          1

NUMERIC SUMMARY
--------------------------------------------------------------------------------

,count,mean,std,min,25%,50%,75%,max
Tumor Grade,271.0,1.439114,0.610845,1.0000,1.0000,1.000000,2.00000,3.000000
Age at MRI (years),541.0,59.168207,13.744877,13.0000,50.0000,60.000000,70.00000,90.000000
T1c x-resolution (mm),570.0,0.780958,0.256060,0.3375,0.5078,0.937500,1.01562,1.054700
T1c y-resolution (mm),570.0,0.780896,0.256049,0.3375,0.5078,0.937500,1.01562,1.054700
T1c Slice Thickness (mm),570.0,1.269181,0.320054,0.4883,1.0000,1.099998,1.50000,2.000009
Magnetic Field Strength (T),365.0,2.395858,0.736724,1.4940,1.5000,3.000000,3.00000,3.000000
"Repitition Time (TR, ms)",195.0,1001.025504,1056.462809,3.9640,12.2600,23.000000,2110.00000,3031.200000
"Echo Time (TE, ms)",195.0,4.305810,2.024670,1.2360,2.9160,3.656000,5.12400,21.000000
"Inversion Time (TI, ms)",175.0,639.188571,406.241681,0.0000,400.0000,900.000000,1080.00000,1100.000000
Flip Angle (degrees),195.0,18.948718,14.517584,8.0000,8.5000,12.000000,25.00000,120.000000
Reconstruction Matrix (rows),373.0,449.126005,170.345120,230.0000,256.0000,512.000000,512.00000,800.000000
Reconstruction Matrix (columns),373.0,448.815013,170.679983,208.0000,256.0000,512.000000,512.00000,800.000000
Pixel Bandwidth (Hz),144.0,132.683408,91.706634,37.0000,61.0547,97.656200,179.00000,750.000000

================================================================================
SHEET: Data Dictionary
================================================================================

Rows: 22
Columns: 7

COLUMN INFORMATION
--------------------------------------------------------------------------------
Variable Name                                 dtype=object       unique=    22 missing=     0
Description                                   dtype=object       unique=    22 missing=     0
Data Type                                     dtype=object       unique=     7 missing=     0
Units / Format                                dtype=object       unique=    14 missing=     0
Allowed Values / Coding                       dtype=object       unique=    20 missing=     0
Common Data Element / Standard                dtype=object       unique=    20 missing=     0
Comments                                      dtype=object       unique=     8 missing=    13

Duplicate rows: 0

FIRST 10 ROWS
--------------------------------------------------------------------------------

,Variable Name,Description,Data Type,Units / Format,Allowed Values / Coding,Common Data Element / Standard,Comments
0,BraTS ID,De-identified unique subject/scan identifier l...,"string (categorical, unique)",Free text identifier,One unique ID per row; no intrinsic ordering.,Study-specific identifier; not mapped to an ex...,Contains no directly identifying information.
1,Tumor Grade,Histopathologic meningioma grade at or closest...,integer (ordinal),WHO grade I–III,1 = WHO grade I (benign); 2 = WHO grade II (at...,WHO CNS tumour classification (2016/2021) grad...,Many entries are n/a where pathology grade was...
2,Age at MRI (years),Patient age in years at time of contrast-enhan...,numeric (continuous),Years (typically integer),Range in this dataset is 13–90 years; n/a= not...,Generic demographic element.,NaN
3,Sex,Recorded biological sex of the patient.,string (categorical),Single-character code,"F = female, M = male.",Generic demographic element.,NaN
4,T1c x-resolution (mm),In-plane voxel size in the frequency-encoding ...,numeric (continuous),Millimetres (mm),Positive real number; typical range ~0.4–1.1 mm.,"Derived from DICOM PixelSpacing (0028,0030).",NaN
5,T1c y-resolution (mm),In-plane voxel size in the phase-encoding (y) ...,numeric (continuous),Millimetres (mm),Positive real number; typical range ~0.4–1.1 mm.,"Derived from DICOM PixelSpacing (0028,0030).",NaN
6,T1c Slice Thickness (mm),Slice thickness of the T1-weighted post-contra...,numeric (continuous),Millimetres (mm),Positive real number; typical range ~1–5 mm.,"Derived from DICOM SliceThickness (0018,0050).",NaN
7,Scanner Manufacturer,Name of the MRI scanner manufacturer.,string (categorical),Free text (vendor name),"Examples include 'Philips Medical Systems', 'S...","DICOM Manufacturer (0008,0070).",Values are vendor-specific free text as stored...
8,Scanner Model,Vendor-specific MRI scanner model name.,string (categorical),Free text,"Examples include 'Ingenia', 'Signa HDxt', 'MAG...","DICOM ManufacturerModelName (0008,1090).",NaN
9,Magnetic Field Strength (T),Static magnetic field strength of the MRI scan...,numeric (continuous),Tesla (T),Values typically 1.5 or 3.0; some vendors repo...,"DICOM MagneticFieldStrength (0018,0087).",NaN

CATEGORICAL VALUE DISTRIBUTIONS
--------------------------------------------------------------------------------

Variable Name
Variable Name
BraTS ID                              1
Tumor Grade                           1
Age at MRI (years)                    1
Sex                                   1
T1c x-resolution (mm)                 1
T1c y-resolution (mm)                 1
T1c Slice Thickness (mm)              1
Scanner Manufacturer                  1
Scanner Model                         1
Magnetic Field Strength (T)           1
Series Description                    1
Scanning Sequence                     1
Sequence Variant                      1
Repitition Time (TR, ms)              1
Echo Time (TE, ms)                    1
Inversion Time (TI, ms)               1
Flip Angle (degrees)                  1
Acquisition Matrix (rows  columns)    1
Reconstruction Matrix (rows)          1
Reconstruction Matrix (columns)       1
Pixel Bandwidth (Hz)                  1
Receive Coil Name                     1

Description
Description
De-identified unique subject/scan identifier linking to imaging data in the BraTS-MEN-RT-2024 meningioma radiotherapy dataset. Format 'BraTS-MEN-RT-XXXX-Y'.    1
Histopathologic meningioma grade at or closest to the time of radiotherapy.                                                                                     1
Patient age in years at time of contrast-enhanced T1-weighted MRI acquisition used for radiotherapy planning / modeling.                                        1
Recorded biological sex of the patient.                                                                                                                         1
In-plane voxel size in the frequency-encoding (x) direction for the post-contrast T1-weighted (T1c) sequence.                                                   1
In-plane voxel size in the phase-encoding (y) direction for the post-contrast T1-weighted (T1c) sequence.                                                       1
Slice thickness of the T1-weighted post-contrast volume.                                                                                                        1
Name of the MRI scanner manufacturer.                                                                                                                           1
Vendor-specific MRI scanner model name.                                                                                                                         1
Static magnetic field strength of the MRI scanner.                                                                                                              1
Free-text description of the image series as stored in the DICOM header for the T1-weighted post-contrast sequence.                                             1
Sequence type / class as reported in the DICOM header (e.g. spin echo, gradient echo, inversion-recovery).                                                      1
Sequence variant flags (e.g., spoiled gradient echo, magnetization-prepared) as reported in the DICOM header.                                                   1
Repetition time (TR) of the T1-weighted sequence in milliseconds. Column header contains a typographical error; should read 'Repetition Time'.                  1
Echo time (TE) of the T1-weighted sequence in milliseconds.                                                                                                     1
Inversion time (TI) for inversion-prepared sequences, in milliseconds.                                                                                          1
Nominal excitation flip angle for the T1-weighted sequence.                                                                                                     1
In-plane acquisition matrix, encoded as 'rowsxcolumns'.                                                                                                         1
Number of rows in the reconstructed in-plane image matrix.                                                                                                      1
Number of columns in the reconstructed in-plane image matrix.                                                                                                   1
Pixel bandwidth in Hertz per pixel.                                                                                                                             1
Name of the RF receive coil configuration used for image acquisition.                                                                                           1

Data Type
Data Type
numeric (continuous)               10
string (categorical)                6
numeric (integer)                   2
integer (ordinal)                   1
string (categorical, unique)        1
string (categorical, free text)     1
string (semi-structured)            1

Units / Format
Units / Format
Millimetres (mm)                   3
Free text                          3
Milliseconds (ms)                  3
Free text or list-like encoding    2
Number of pixels                   2
Free text identifier               1
Free text (vendor name)            1
Single-character code              1
Years (typically integer)          1
WHO grade I–III                    1
Tesla (T)                          1
Degrees (°)                        1
Rows x columns                     1
Hertz (Hz)                         1

Allowed Values / Coding
Allowed Values / Coding
Typical values include 224, 256, 288, 320, 512, etc.; n/a = not available.                                                                2
Positive real number; typical range ~0.4–1.1 mm.                                                                                          2
One unique ID per row; no intrinsic ordering.                                                                                             1
1 = WHO grade I (benign); 2 = WHO grade II (atypical); 3 = WHO grade III (anaplastic/malignant); n/a = not available.                     1
F = female, M = male.                                                                                                                     1
Range in this dataset is 13–90 years; n/a= not available.                                                                                 1
Examples include 'Philips Medical Systems', 'Siemens', 'GE MEDICAL SYSTEMS', 'CANON_MEC'.                                                 1
Positive real number; typical range ~1–5 mm.                                                                                              1
Values typically 1.5 or 3.0; some vendors report 1.494 T etc.; n/a = not available.                                                       1
Examples include 'AX T1 3D MPRAGE (GAD)', 'AX SPGR 3D POST', etc.                                                                         1
Examples include 'GR', 'SE', 'RM', and list-like encodings such as "['RM', 'IR']".                                                        1
Examples include 'Ingenia', 'Signa HDxt', 'MAGNETOM TrioTim', 'Aera', 'Galan 3T'.                                                         1
Examples include 'SS', 'SP', 'MP', 'SK', 'Spoiled Gradient-Echo (SP-GR)', and list-like encodings such as "['SS', 'SP', 'SK', 'OSP']".    1
Positive real number; typical range ~5–2500 ms, depending on sequence.                                                                    1
Non-negative real number; present for inversion-recovery sequences and n/a otherwise.                                                     1
Positive real number; typical range ~1–20 ms for T1-weighted gradient-echo sequences.                                                     1
Positive real number; typical range ~5–30° for T1-weighted 3D gradient-echo sequences.                                                    1
Examples include '320x320', '256x256', '512x512', etc.                                                                                    1
Positive real number when present; n/a = not available.                                                                                   1
Examples include 'HEAD', '48HAP', 'HNS Head', '8HRBRAIN', 'SENSE-Head-8'.                                                                 1

Common Data Element / Standard
Common Data Element / Standard
Derived from DICOM PixelSpacing (0028,0030).                           2
Generic demographic element.                                           2
WHO CNS tumour classification (2016/2021) grading scheme.              1
Study-specific identifier; not mapped to an external CDE.              1
Derived from DICOM SliceThickness (0018,0050).                         1
DICOM Manufacturer (0008,0070).                                        1
DICOM ManufacturerModelName (0008,1090).                               1
DICOM MagneticFieldStrength (0018,0087).                               1
DICOM SeriesDescription (0008,103E).                                   1
DICOM ScanningSequence (0018,0020).                                    1
DICOM SequenceVariant (0018,0021).                                     1
DICOM RepetitionTime (0018,0080).                                      1
DICOM EchoTime (0018,0081).                                            1
DICOM InversionTime (0018,0082).                                       1
DICOM FlipAngle (0018,1314).                                           1
Derived from DICOM AcquisitionMatrix (0018,1310).                      1
Derived from DICOM Rows (0028,0010) / reconstruction parameters.       1
Derived from DICOM Columns (0028,0011) / reconstruction parameters.    1
DICOM PixelBandwidth (0018,0095).                                      1
DICOM ReceiveCoilName / CoilString (0018,1250 / vendor-specific).      1

Comments
Comments
NaN                                                                                                 13
Some entries appear as list strings representing combinations of flags.                              2
Contains no directly identifying information.                                                        1
Values are vendor-specific free text as stored in DICOM.                                             1
Many entries are n/a where pathology grade was not available in source data.                         1
Often reflects local protocol naming conventions; not standardized.                                  1
Zero values may indicate non-inversion-prepared sequences or vendor-specific encoding.               1
Note that these are acquisition matrix dimensions and may differ from reconstructed matrix size.     1
Free-text vendor-specific descriptions of the active receive coil elements.                          1

NUMERIC SUMMARY
--------------------------------------------------------------------------------
No numeric columns detected.

================================================================================
CLINICAL VARIABLE SEARCH
================================================================================

SHEET: BraTS-MEN-RT Clinical Data
  patient_id        : ['BraTS ID', 'Pixel Bandwidth (Hz)']
  age               : ['Age at MRI (years)']
  sex               : ['Sex']
  who_grade         : ['Tumor Grade']
  tumor             : ['Tumor Grade']

SHEET: Data Dictionary

================================================================================
NORMALIZATION PREVIEW
================================================================================
BraTS ID                                           → brats_id
Tumor Grade                                        → tumor_grade
Age at MRI (years)                                 → age_at_mri_years
Sex                                                → sex
T1c x-resolution (mm)                              → t1c_x_resolution_mm
T1c y-resolution (mm)                              → t1c_y_resolution_mm
T1c Slice Thickness (mm)                           → t1c_slice_thickness_mm
Scanner Manufacturer                               → scanner_manufacturer
Scanner Model                                      → scanner_model
Magnetic Field Strength (T)                        → magnetic_field_strength_t
Series Description                                 → series_description
Scanning Sequence                                  → scanning_sequence
Sequence Variant                                   → sequence_variant
Repitition Time (TR, ms)                           → repitition_time_tr_ms
Echo Time (TE, ms)                                 → echo_time_te_ms
Inversion Time (TI, ms)                            → inversion_time_ti_ms
Flip Angle (degrees)                               → flip_angle_degrees
Acquisition Matrix (rows  columns)                 → acquisition_matrix_rows_columns
Reconstruction Matrix (rows)                       → reconstruction_matrix_rows
Reconstruction Matrix (columns)                    → reconstruction_matrix_columns
Pixel Bandwidth (Hz)                               → pixel_bandwidth_hz
Receive Coil Name                                  → receive_coil_name
Variable Name                                      → variable_name
Description                                        → description
Data Type                                          → data_type
Units / Format                                     → units_format
Allowed Values / Coding                            → allowed_values_coding
Common Data Element / Standard                     → common_data_element_standard
Comments                                           → comments

================================================================================
TARGET SAFETY DECISION
================================================================================
Medication-related field found: NO
Treatment-related field found: NO
Outcome-related field found: NO

✅ No validated medication prescription target identified.

================================================================================
SAVING NORMALIZED TABLES
================================================================================
Saved: /content/drive/MyDrive/Model5/data/processed/brats_men_rt_brats_men_rt_clinical_data.csv
Saved: /content/drive/MyDrive/Model5/data/processed/brats_men_rt_data_dictionary.csv

================================================================================
MODEL 5 - STEP 6 COMPLETE
================================================================================

Clinical metadata:
✅ INSPECTED

Normalized tables:
✅ SAVED

Prescription target:
❌ NOT AUTOMATICALLY CREATED

Audit:
/content/drive/MyDrive/Model5/audit/dataset/step6_clinical_metadata_inspection_audit.json

================================================================================
NEXT → STEP 7
CLINICAL FEATURE ENGINEERING + TARGET VALIDATION
================================================================================

In [13]:
# =============================================================================
# MODEL 5 - STEP 7
# CLINICAL FEATURE ENGINEERING + TARGET VALIDATION
# =============================================================================

import pandas as pd
import numpy as np
import json
from pathlib import Path
from datetime import datetime

print("=" * 80)
print("MODEL 5 - STEP 7")
print("CLINICAL FEATURE ENGINEERING + TARGET VALIDATION")
print("=" * 80)

# =============================================================================
# PATHS
# =============================================================================

INPUT = Path(
    "/content/drive/MyDrive/Model5/data/processed/"
    "brats_men_rt_brats_men_rt_clinical_data.csv"
)

OUT_DIR = Path(
    "/content/drive/MyDrive/Model5/data/processed"
)

AUDIT_DIR = Path(
    "/content/drive/MyDrive/Model5/audit/dataset"
)

OUT_DIR.mkdir(parents=True, exist_ok=True)
AUDIT_DIR.mkdir(parents=True, exist_ok=True)

# =============================================================================
# LOAD
# =============================================================================

print()
print("=" * 80)
print("LOADING NORMALIZED CLINICAL DATA")
print("=" * 80)

df = pd.read_csv(INPUT)

print("Rows   :", len(df))
print("Columns:", len(df.columns))

# =============================================================================
# BASIC CLEANING
# =============================================================================

df = df.copy()

# Remove accidental unnamed columns if present
df = df[
    [
        c for c in df.columns
        if not str(c).lower().startswith("unnamed")
    ]
]

# Rename fields into canonical Model 5 names
rename_map = {
    "brats_id": "patient_id",
    "age_at_mri_years": "age",
    "tumor_grade": "who_grade",
    "t1c_x_resolution_mm": "voxel_x_mm",
    "t1c_y_resolution_mm": "voxel_y_mm",
    "t1c_slice_thickness_mm": "slice_thickness_mm",
    "magnetic_field_strength_t": "field_strength_t",
}

df = df.rename(columns=rename_map)

# =============================================================================
# FIX DATA TYPES
# =============================================================================

numeric_columns = [
    "age",
    "who_grade",
    "voxel_x_mm",
    "voxel_y_mm",
    "slice_thickness_mm",
    "field_strength_t",
]

for col in numeric_columns:
    if col in df.columns:
        df[col] = pd.to_numeric(
            df[col],
            errors="coerce"
        )

if "sex" in df.columns:
    df["sex"] = (
        df["sex"]
        .astype("string")
        .str.upper()
        .str.strip()
    )

# =============================================================================
# CONSTANT DATASET LABEL
# =============================================================================

df["dataset"] = "BraTS-MEN-RT"

df["tumor_type"] = "meningioma"

# =============================================================================
# AGE GROUP
# =============================================================================

def age_group(age):

    if pd.isna(age):
        return "unknown"

    if age < 18:
        return "pediatric"

    if age < 40:
        return "young_adult"

    if age < 60:
        return "middle_adult"

    if age < 75:
        return "older_adult"

    return "elderly"


df["age_group"] = df["age"].apply(age_group)

# =============================================================================
# SEX NORMALIZATION
# =============================================================================

def normalize_sex(value):

    if pd.isna(value):
        return "unknown"

    value = str(value).upper().strip()

    if value == "F":
        return "female"

    if value == "M":
        return "male"

    return "unknown"


df["sex_category"] = df["sex"].apply(
    normalize_sex
)

# =============================================================================
# WHO GRADE CATEGORY
# =============================================================================

def who_grade_category(value):

    if pd.isna(value):
        return "unknown"

    value = float(value)

    if value == 1:
        return "WHO_grade_I"

    if value == 2:
        return "WHO_grade_II"

    if value == 3:
        return "WHO_grade_III"

    return "unknown"


df["who_grade_category"] = (
    df["who_grade"]
    .apply(who_grade_category)
)

# =============================================================================
# MRI FIELD STRENGTH CATEGORY
# =============================================================================

def field_strength_category(value):

    if pd.isna(value):
        return "unknown"

    value = float(value)

    if value < 2:
        return "low_field"

    return "high_field"


df["field_strength_category"] = (
    df["field_strength_t"]
    .apply(field_strength_category)
)

# =============================================================================
# IMAGE RESOLUTION CATEGORY
# =============================================================================

def resolution_category(row):

    x = row.get("voxel_x_mm")
    y = row.get("voxel_y_mm")

    if pd.isna(x) or pd.isna(y):
        return "unknown"

    mean_resolution = (
        float(x) + float(y)
    ) / 2

    if mean_resolution <= 0.6:
        return "high_resolution"

    if mean_resolution <= 0.9:
        return "moderate_resolution"

    return "lower_resolution"


df["resolution_category"] = df.apply(
    resolution_category,
    axis=1
)

# =============================================================================
# SLICE THICKNESS CATEGORY
# =============================================================================

def slice_thickness_category(value):

    if pd.isna(value):
        return "unknown"

    value = float(value)

    if value <= 1.0:
        return "thin"

    if value <= 1.5:
        return "moderate"

    return "thick"


df["slice_thickness_category"] = (
    df["slice_thickness_mm"]
    .apply(slice_thickness_category)
)

# =============================================================================
# CLINICAL DATA COMPLETENESS
# =============================================================================

clinical_columns = [
    "age",
    "sex_category",
    "who_grade"
]

df["clinical_missing_count"] = (
    df[clinical_columns]
    .isna()
    .sum(axis=1)
)

df["clinical_completeness"] = (
    1 -
    df["clinical_missing_count"] /
    len(clinical_columns)
)

# =============================================================================
# DATA QUALITY CATEGORY
# =============================================================================

def quality_category(value):

    if value >= 0.999:
        return "complete"

    if value >= 0.666:
        return "mostly_complete"

    if value >= 0.333:
        return "partially_complete"

    return "limited"


df["clinical_data_quality"] = (
    df["clinical_completeness"]
    .apply(quality_category)
)

# =============================================================================
# MODEL 4A PLACEHOLDERS
# =============================================================================
#
# Model 4A measurements will be joined later using patient_id / image ID.
#
# We deliberately do NOT invent these values here.

model4a_columns = [
    "tumor_detected",
    "tumor_area_pixels",
    "tumor_area_percent",
    "tumor_width_pixels",
    "tumor_height_pixels",
    "centroid_x",
    "centroid_y",
    "boundary_pixels",
]

for col in model4a_columns:
    if col not in df.columns:
        df[col] = np.nan

# =============================================================================
# TARGET VALIDATION
# =============================================================================

print()
print("=" * 80)
print("TARGET VALIDATION")
print("=" * 80)

target_columns = [
    "recommendation_category",
    "recommended_specialist",
    "recommended_next_step",
    "follow_up_category",
    "specific_medication",
    "drug_dosage",
    "drug_frequency",
    "drug_duration",
]

target_status = {}

for target in target_columns:

    exists = target in df.columns

    if exists:

        non_null = int(
            df[target].notna().sum()
        )

        target_status[target] = {
            "column_exists": True,
            "non_null_rows": non_null,
            "validated": False
        }

        print(
            f"{target:30s}: "
            f"FOUND but NOT VALIDATED "
            f"({non_null} non-null)"
        )

    else:

        target_status[target] = {
            "column_exists": False,
            "non_null_rows": 0,
            "validated": False
        }

        print(
            f"{target:30s}: NOT AVAILABLE"
        )

# =============================================================================
# PRESCRIPTION SAFETY CHECK
# =============================================================================

prescription_columns = [
    "specific_medication",
    "drug_dosage",
    "drug_frequency",
    "drug_duration",
]

prescription_available = any(
    c in df.columns
    and df[c].notna().any()
    for c in prescription_columns
)

print()
print(
    "Validated prescription target:",
    "YES" if prescription_available else "NO"
)

if not prescription_available:

    print(
        "✅ Prescription prediction remains DISABLED."
    )

# =============================================================================
# FEATURE SET
# =============================================================================

feature_columns = [
    "patient_id",
    "dataset",
    "tumor_type",

    "age",
    "age_group",

    "sex",
    "sex_category",

    "who_grade",
    "who_grade_category",

    "voxel_x_mm",
    "voxel_y_mm",
    "slice_thickness_mm",

    "field_strength_t",
    "field_strength_category",

    "resolution_category",
    "slice_thickness_category",

    "clinical_missing_count",
    "clinical_completeness",
    "clinical_data_quality",

    # Model 4A integration fields
    "tumor_detected",
    "tumor_area_pixels",
    "tumor_area_percent",
    "tumor_width_pixels",
    "tumor_height_pixels",
    "centroid_x",
    "centroid_y",
    "boundary_pixels",
]

feature_columns = [
    c for c in feature_columns
    if c in df.columns
]

model5_df = df[feature_columns].copy()

# =============================================================================
# DUPLICATE CHECK
# =============================================================================

duplicate_ids = int(
    model5_df["patient_id"].duplicated().sum()
)

print()
print("=" * 80)
print("DATA QUALITY")
print("=" * 80)

print(
    "Total records       :",
    len(model5_df)
)

print(
    "Unique patient IDs  :",
    model5_df["patient_id"].nunique()
)

print(
    "Duplicate IDs       :",
    duplicate_ids
)

# =============================================================================
# MISSING VALUE REPORT
# =============================================================================

print()
print("MISSING VALUE REPORT")
print("-" * 80)

missing_report = []

for col in model5_df.columns:

    missing = int(
        model5_df[col].isna().sum()
    )

    percentage = (
        missing /
        len(model5_df) *
        100
    )

    missing_report.append({
        "column": col,
        "missing": missing,
        "missing_percent": round(
            percentage,
            2
        )
    })

missing_df = pd.DataFrame(
    missing_report
)

display(
    missing_df
    .sort_values(
        "missing_percent",
        ascending=False
    )
    .head(30)
)

# =============================================================================
# DISTRIBUTIONS
# =============================================================================

print()
print("=" * 80)
print("ENGINEERED FEATURE DISTRIBUTIONS")
print("=" * 80)

for col in [
    "age_group",
    "sex_category",
    "who_grade_category",
    "field_strength_category",
    "resolution_category",
    "slice_thickness_category",
    "clinical_data_quality",
]:

    if col in model5_df.columns:

        print()
        print(col)

        print(
            model5_df[col]
            .value_counts(
                dropna=False
            )
            .to_string()
        )

# =============================================================================
# SAVE CLEAN DATASET
# =============================================================================

OUTPUT = (
    OUT_DIR /
    "model5_clinical_features_v1.csv"
)

model5_df.to_csv(
    OUTPUT,
    index=False
)

print()
print("=" * 80)
print("DATASET SAVED")
print("=" * 80)

print(
    OUTPUT
)

# =============================================================================
# SAVE AUDIT
# =============================================================================

audit = {

    "timestamp":
        datetime.now().isoformat(),

    "step":
        "7",

    "input":
        str(INPUT),

    "output":
        str(OUTPUT),

    "records":
        int(len(model5_df)),

    "columns":
        list(model5_df.columns),

    "unique_patient_ids":
        int(
            model5_df["patient_id"].nunique()
        ),

    "duplicate_patient_ids":
        duplicate_ids,

    "target_validation":
        target_status,

    "prescription_target_available":
        prescription_available,

    "prescription_training_enabled":
        False,

    "model4a_measurements":
        "reserved_for_later_join",

    "clinical_features_engineered": [
        "age_group",
        "sex_category",
        "who_grade_category",
        "field_strength_category",
        "resolution_category",
        "slice_thickness_category",
        "clinical_data_quality"
    ]
}

AUDIT = (
    AUDIT_DIR /
    "step7_clinical_feature_engineering_audit.json"
)

with open(AUDIT, "w") as f:

    json.dump(
        audit,
        f,
        indent=2,
        default=str
    )

# =============================================================================
# FINAL STATUS
# =============================================================================

print()
print("=" * 80)
print("MODEL 5 - STEP 7 COMPLETE")
print("=" * 80)

print()
print("Clinical features:")
print("✅ ENGINEERED")

print()
print("Prescription labels:")
print("❌ NOT AVAILABLE")

print()
print("Prescription model:")
print("❌ DISABLED")

print()
print("Clean feature dataset:")
print("✅ CREATED")

print()
print("Audit:")
print(AUDIT)

print()
print("=" * 80)
print("NEXT → STEP 8")
print("MODEL 4A → MODEL 5 DATA INTEGRATION")
print("=" * 80)

================================================================================
MODEL 5 - STEP 7
CLINICAL FEATURE ENGINEERING + TARGET VALIDATION
================================================================================

================================================================================
LOADING NORMALIZED CLINICAL DATA
================================================================================
Rows   : 570
Columns: 22

================================================================================
TARGET VALIDATION
================================================================================
recommendation_category       : NOT AVAILABLE
recommended_specialist        : NOT AVAILABLE
recommended_next_step         : NOT AVAILABLE
follow_up_category            : NOT AVAILABLE
specific_medication           : NOT AVAILABLE
drug_dosage                   : NOT AVAILABLE
drug_frequency                : NOT AVAILABLE
drug_duration                 : NOT AVAILABLE

Validated prescription target: NO
✅ Prescription prediction remains DISABLED.

================================================================================
DATA QUALITY
================================================================================
Total records       : 570
Unique patient IDs  : 570
Duplicate IDs       : 0

MISSING VALUE REPORT
--------------------------------------------------------------------------------

                      column  missing  missing_percent
24                centroid_x      570           100.00
25                centroid_y      570           100.00
26           boundary_pixels      570           100.00
19            tumor_detected      570           100.00
20         tumor_area_pixels      570           100.00
21        tumor_area_percent      570           100.00
22        tumor_width_pixels      570           100.00
23       tumor_height_pixels      570           100.00
7                  who_grade      299            52.46
12          field_strength_t      205            35.96
3                        age       29             5.09
5                        sex       29             5.09
9                 voxel_x_mm        0             0.00
8         who_grade_category        0             0.00
6               sex_category        0             0.00
4                  age_group        0             0.00
0                 patient_id        0             0.00
1                    dataset        0             0.00
2                 tumor_type        0             0.00
10                voxel_y_mm        0             0.00
18     clinical_data_quality        0             0.00
16    clinical_missing_count        0             0.00
17     clinical_completeness        0             0.00
14       resolution_category        0             0.00
13   field_strength_category        0             0.00
11        slice_thickness_mm        0             0.00
15  slice_thickness_category        0             0.00

================================================================================
ENGINEERED FEATURE DISTRIBUTIONS
================================================================================

age_group
age_group
older_adult     212
middle_adult    210
elderly          70
young_adult      48
unknown          29
pediatric         1

sex_category
sex_category
female     360
male       181
unknown     29

who_grade_category
who_grade_category
unknown          299
WHO_grade_I      169
WHO_grade_II      85
WHO_grade_III     17

field_strength_category
field_strength_category
high_field    218
unknown       205
low_field     147

resolution_category
resolution_category
lower_resolution       302
high_resolution        193
moderate_resolution     75

slice_thickness_category
slice_thickness_category
moderate    304
thin        213
thick        53

clinical_data_quality
clinical_data_quality
complete              271
mostly_complete       270
partially_complete     29

================================================================================
DATASET SAVED
================================================================================
/content/drive/MyDrive/Model5/data/processed/model5_clinical_features_v1.csv

================================================================================
MODEL 5 - STEP 7 COMPLETE
================================================================================

Clinical features:
✅ ENGINEERED

Prescription labels:
❌ NOT AVAILABLE

Prescription model:
❌ DISABLED

Clean feature dataset:
✅ CREATED

Audit:
/content/drive/MyDrive/Model5/audit/dataset/step7_clinical_feature_engineering_audit.json

================================================================================
NEXT → STEP 8
MODEL 4A → MODEL 5 DATA INTEGRATION
================================================================================

In [15]:
# =============================================================================
# MODEL 5 - STEP 8A
# CLINICAL CLASSIFICATION MODEL TRAINING
# =============================================================================

import pandas as pd
import numpy as np
import json
import joblib

from pathlib import Path
from datetime import datetime

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    classification_report,
    confusion_matrix
)

print("=" * 80)
print("MODEL 5 - STEP 8A")
print("CLINICAL CLASSIFICATION MODEL TRAINING")
print("=" * 80)

# =============================================================================
# PATHS
# =============================================================================

INPUT = Path(
    "/content/drive/MyDrive/Model5/data/processed/"
    "model5_clinical_features_v1.csv"
)

MODEL_DIR = Path(
    "/content/drive/MyDrive/Model5/models"
)

RESULT_DIR = Path(
    "/content/drive/MyDrive/Model5/results"
)

AUDIT_DIR = Path(
    "/content/drive/MyDrive/Model5/audit/training"
)

MODEL_DIR.mkdir(
    parents=True,
    exist_ok=True
)

RESULT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

AUDIT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# =============================================================================
# LOAD DATA
# =============================================================================

print()
print("=" * 80)
print("LOADING DATASET")
print("=" * 80)

df = pd.read_csv(INPUT)

print(
    "Total rows:",
    len(df)
)

# =============================================================================
# TARGET
# =============================================================================

TARGET = "who_grade"

if TARGET not in df.columns:
    raise ValueError(
        f"Target column '{TARGET}' not found."
    )

# Only cases with actual WHO grade
model_df = df[
    df[TARGET].notna()
].copy()

print(
    "Rows with WHO grade:",
    len(model_df)
)

print()
print("Target distribution:")

print(
    model_df[TARGET]
    .value_counts()
    .sort_index()
)

# =============================================================================
# REMOVE UNSUITABLE / LEAKY COLUMNS
# =============================================================================

excluded_columns = [
    "patient_id",
    "dataset",
    "tumor_type",

    # Target-derived category
    "who_grade_category",

    # Model 4A fields — currently empty and will be
    # integrated later through the real pipeline.
    "tumor_detected",
    "tumor_area_pixels",
    "tumor_area_percent",
    "tumor_width_pixels",
    "tumor_height_pixels",
    "centroid_x",
    "centroid_y",
    "boundary_pixels",

    # Derived from target/clinical completeness
    "clinical_missing_count",
    "clinical_completeness",
    "clinical_data_quality",

    # Do not use redundant categorical versions
    "age_group",
    "sex",
]

feature_candidates = [
    "age",
    "sex_category",
    "voxel_x_mm",
    "voxel_y_mm",
    "slice_thickness_mm",
    "field_strength_t",
    "field_strength_category",
    "resolution_category",
    "slice_thickness_category",
]

features = [
    c for c in feature_candidates
    if c in model_df.columns
]

print()
print("=" * 80)
print("FEATURES")
print("=" * 80)

for feature in features:
    print(
        " -",
        feature
    )

X = model_df[features].copy()
y = model_df[TARGET].astype(int)

# =============================================================================
# CHECK CLASS COUNTS
# =============================================================================

print()
print("=" * 80)
print("CLASS DISTRIBUTION")
print("=" * 80)

class_counts = y.value_counts().sort_index()

for cls, count in class_counts.items():

    print(
        f"WHO Grade {cls}: {count}"
    )

# =============================================================================
# TRAIN / TEST SPLIT
# =============================================================================

print()
print("=" * 80)
print("TRAIN / TEST SPLIT")
print("=" * 80)

# Grade III has only 17 samples, so stratification is still
# possible but evaluation will have very small support.

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print(
    "Training samples:",
    len(X_train)
)

print(
    "Testing samples:",
    len(X_test)
)

print()
print("Training distribution:")

print(
    y_train.value_counts()
    .sort_index()
)

print()
print("Testing distribution:")

print(
    y_test.value_counts()
    .sort_index()
)

# =============================================================================
# COLUMN TYPES
# =============================================================================

categorical_features = [
    c for c in features
    if X[c].dtype == "object"
    or str(X[c].dtype).startswith("string")
]

numeric_features = [
    c for c in features
    if c not in categorical_features
]

# =============================================================================
# PREPROCESSING
# =============================================================================

numeric_pipeline = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(
                strategy="median"
            )
        ),
        (
            "scaler",
            StandardScaler()
        )
    ]
)

categorical_pipeline = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(
                strategy="most_frequent"
            )
        ),
        (
            "encoder",
            OneHotEncoder(
                handle_unknown="ignore"
            )
        )
    ]
)

preprocessor = ColumnTransformer(
    transformers=[
        (
            "numeric",
            numeric_pipeline,
            numeric_features
        ),
        (
            "categorical",
            categorical_pipeline,
            categorical_features
        )
    ]
)

# =============================================================================
# MODEL
# =============================================================================

classifier = RandomForestClassifier(
    n_estimators=400,
    max_depth=None,
    min_samples_leaf=2,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

model = Pipeline(
    steps=[
        (
            "preprocessor",
            preprocessor
        ),
        (
            "classifier",
            classifier
        )
    ]
)

# =============================================================================
# TRAIN
# =============================================================================

print()
print("=" * 80)
print("TRAINING")
print("=" * 80)

model.fit(
    X_train,
    y_train
)

print(
    "✅ Training complete"
)

# =============================================================================
# EVALUATION
# =============================================================================

print()
print("=" * 80)
print("EVALUATION")
print("=" * 80)

y_pred = model.predict(
    X_test
)

accuracy = accuracy_score(
    y_test,
    y_pred
)

balanced_accuracy = balanced_accuracy_score(
    y_test,
    y_pred
)

print(
    f"Accuracy          : {accuracy:.4f}"
)

print(
    f"Balanced accuracy : {balanced_accuracy:.4f}"
)

print()
print("Classification report:")
print(
    classification_report(
        y_test,
        y_pred,
        zero_division=0
    )
)

print()
print("Confusion matrix:")

cm = confusion_matrix(
    y_test,
    y_pred
)

print(cm)

# =============================================================================
# SAVE MODEL
# =============================================================================

MODEL_PATH = (
    MODEL_DIR /
    "Model5_WHO_Grade_Classifier.joblib"
)

joblib.dump(
    model,
    MODEL_PATH
)

print()
print("=" * 80)
print("MODEL SAVED")
print("=" * 80)

print(
    MODEL_PATH
)

# =============================================================================
# SAVE TEST RESULTS
# =============================================================================

results_df = X_test.copy()

results_df["actual_who_grade"] = (
    y_test.values
)

results_df["predicted_who_grade"] = (
    y_pred
)

RESULT_PATH = (
    RESULT_DIR /
    "model5_who_grade_test_predictions.csv"
)

results_df.to_csv(
    RESULT_PATH,
    index=False
)

# =============================================================================
# FEATURE IMPORTANCE
# =============================================================================

print()
print("=" * 80)
print("FEATURE IMPORTANCE")
print("=" * 80)

try:

    fitted_preprocessor = (
        model
        .named_steps["preprocessor"]
    )

    fitted_classifier = (
        model
        .named_steps["classifier"]
    )

    feature_names = (
        fitted_preprocessor
        .get_feature_names_out()
    )

    importances = (
        fitted_classifier
        .feature_importances_
    )

    importance_df = pd.DataFrame({
        "feature": feature_names,
        "importance": importances
    })

    importance_df = (
        importance_df
        .sort_values(
            "importance",
            ascending=False
        )
    )

    display(
        importance_df.head(20)
    )

    importance_path = (
        RESULT_DIR /
        "model5_feature_importance.csv"
    )

    importance_df.to_csv(
        importance_path,
        index=False
    )

except Exception as e:

    print(
        "⚠️ Feature importance unavailable:",
        e
    )

# =============================================================================
# SAVE TRAINING AUDIT
# =============================================================================

audit = {

    "timestamp":
        datetime.now().isoformat(),

    "input":
        str(INPUT),

    "target":
        TARGET,

    "total_dataset_rows":
        int(len(df)),

    "rows_with_target":
        int(len(model_df)),

    "training_rows":
        int(len(X_train)),

    "testing_rows":
        int(len(X_test)),

    "features":
        features,

    "numeric_features":
        numeric_features,

    "categorical_features":
        categorical_features,

    "class_distribution":
        {
            str(k): int(v)
            for k, v in class_counts.items()
        },

    "accuracy":
        float(accuracy),

    "balanced_accuracy":
        float(balanced_accuracy),

    "prescription_prediction":
        False,

    "model_type":
        "RandomForestClassifier",

    "random_state":
        42,

    "model_path":
        str(MODEL_PATH),

    "test_results":
        str(RESULT_PATH)
}

AUDIT_PATH = (
    AUDIT_DIR /
    "step8a_who_grade_training_audit.json"
)

with open(
    AUDIT_PATH,
    "w"
) as f:

    json.dump(
        audit,
        f,
        indent=2,
        default=str
    )

# =============================================================================
# FINAL
# =============================================================================

print()
print("=" * 80)
print("MODEL 5 - STEP 8A COMPLETE")
print("=" * 80)

print()
print("Clinical classifier:")
print("✅ TRAINED")

print()
print("Target:")
print("WHO grade")

print()
print("Prescription prediction:")
print("❌ NOT INCLUDED")

print()
print("Model:")
print(MODEL_PATH)

print()
print("Test predictions:")
print(RESULT_PATH)

print()
print("Audit:")
print(AUDIT_PATH)

print()
print("=" * 80)
print("NEXT → STEP 8B")
print("CROSS-VALIDATION + MODEL ROBUSTNESS CHECK")
print("=" * 80)

================================================================================
MODEL 5 - STEP 8A
CLINICAL CLASSIFICATION MODEL TRAINING
================================================================================

================================================================================
LOADING DATASET
================================================================================
Total rows: 570
Rows with WHO grade: 271

Target distribution:
who_grade
1.0    169
2.0     85
3.0     17
Name: count, dtype: int64

================================================================================
FEATURES
================================================================================
 - age
 - sex_category
 - voxel_x_mm
 - voxel_y_mm
 - slice_thickness_mm
 - field_strength_t
 - field_strength_category
 - resolution_category
 - slice_thickness_category

================================================================================
CLASS DISTRIBUTION
================================================================================
WHO Grade 1: 169
WHO Grade 2: 85
WHO Grade 3: 17

================================================================================
TRAIN / TEST SPLIT
================================================================================
Training samples: 216
Testing samples: 55

Training distribution:
who_grade
1    135
2     68
3     13
Name: count, dtype: int64

Testing distribution:
who_grade
1    34
2    17
3     4
Name: count, dtype: int64

================================================================================
TRAINING
================================================================================
✅ Training complete

================================================================================
EVALUATION
================================================================================
Accuracy          : 0.5818
Balanced accuracy : 0.4559

Classification report:
              precision    recall  f1-score   support

           1       0.73      0.71      0.72        34
           2       0.44      0.41      0.42        17
           3       0.17      0.25      0.20         4

    accuracy                           0.58        55
   macro avg       0.44      0.46      0.45        55
weighted avg       0.60      0.58      0.59        55


Confusion matrix:
[[24  7  3]
 [ 8  7  2]
 [ 1  2  1]]

================================================================================
MODEL SAVED
================================================================================
/content/drive/MyDrive/Model5/models/Model5_WHO_Grade_Classifier.joblib

================================================================================
FEATURE IMPORTANCE
================================================================================

                                              feature  importance
0                                        numeric__age    0.379886
3                         numeric__slice_thickness_mm    0.121043
1                                 numeric__voxel_x_mm    0.108202
2                                 numeric__voxel_y_mm    0.106686
5                    categorical__sex_category_female    0.056133
6                      categorical__sex_category_male    0.045463
15         categorical__slice_thickness_category_thin    0.041254
13     categorical__slice_thickness_category_moderate    0.032842
7     categorical__field_strength_category_high_field    0.019344
9        categorical__field_strength_category_unknown    0.016247
4                           numeric__field_strength_t    0.015462
8      categorical__field_strength_category_low_field    0.014648
11  categorical__resolution_category_lower_resolution    0.014075
12  categorical__resolution_category_moderate_reso...    0.012426
10   categorical__resolution_category_high_resolution    0.011039
14        categorical__slice_thickness_category_thick    0.005249

================================================================================
MODEL 5 - STEP 8A COMPLETE
================================================================================

Clinical classifier:
✅ TRAINED

Target:
WHO grade

Prescription prediction:
❌ NOT INCLUDED

Model:
/content/drive/MyDrive/Model5/models/Model5_WHO_Grade_Classifier.joblib

Test predictions:
/content/drive/MyDrive/Model5/results/model5_who_grade_test_predictions.csv

Audit:
/content/drive/MyDrive/Model5/audit/training/step8a_who_grade_training_audit.json

================================================================================
NEXT → STEP 8B
CROSS-VALIDATION + MODEL ROBUSTNESS CHECK
================================================================================

In [16]:
# =============================================================================
# MODEL 5 - STEP 8B
# CROSS-VALIDATION + MODEL ROBUSTNESS CHECK
# =============================================================================

import pandas as pd
import numpy as np
import json
import joblib

from pathlib import Path
from datetime import datetime

from sklearn.model_selection import StratifiedKFold, cross_validate
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.dummy import DummyClassifier

from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    f1_score,
    precision_score,
    recall_score,
    confusion_matrix,
    classification_report
)

print("=" * 80)
print("MODEL 5 - STEP 8B")
print("CROSS-VALIDATION + MODEL ROBUSTNESS CHECK")
print("=" * 80)

# =============================================================================
# PATHS
# =============================================================================

INPUT = Path(
    "/content/drive/MyDrive/Model5/data/processed/"
    "model5_clinical_features_v1.csv"
)

RESULT_DIR = Path(
    "/content/drive/MyDrive/Model5/results"
)

AUDIT_DIR = Path(
    "/content/drive/MyDrive/Model5/audit/training"
)

RESULT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

AUDIT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# =============================================================================
# LOAD
# =============================================================================

print()
print("=" * 80)
print("LOADING DATA")
print("=" * 80)

df = pd.read_csv(INPUT)

TARGET = "who_grade"

df = df[
    df[TARGET].notna()
].copy()

print(
    "Cases with WHO grade:",
    len(df)
)

# =============================================================================
# FEATURES
# =============================================================================

features = [
    "age",
    "sex_category",
    "voxel_x_mm",
    "voxel_y_mm",
    "slice_thickness_mm",
    "field_strength_t",
    "field_strength_category",
    "resolution_category",
    "slice_thickness_category"
]

features = [
    c for c in features
    if c in df.columns
]

X = df[features].copy()
y = df[TARGET].astype(int)

categorical_features = [
    c for c in features
    if X[c].dtype == "object"
    or str(X[c].dtype).startswith("string")
]

numeric_features = [
    c for c in features
    if c not in categorical_features
]

print()
print("Features:")
for feature in features:
    print(" -", feature)

# =============================================================================
# PREPROCESSOR
# =============================================================================

numeric_pipeline = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(
                strategy="median"
            )
        ),
        (
            "scaler",
            StandardScaler()
        )
    ]
)

categorical_pipeline = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(
                strategy="most_frequent"
            )
        ),
        (
            "encoder",
            OneHotEncoder(
                handle_unknown="ignore"
            )
        )
    ]
)

preprocessor = ColumnTransformer(
    transformers=[
        (
            "numeric",
            numeric_pipeline,
            numeric_features
        ),
        (
            "categorical",
            categorical_pipeline,
            categorical_features
        )
    ]
)

# =============================================================================
# MODEL
# =============================================================================

classifier = RandomForestClassifier(
    n_estimators=400,
    min_samples_leaf=2,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

model = Pipeline(
    steps=[
        (
            "preprocessor",
            preprocessor
        ),
        (
            "classifier",
            classifier
        )
    ]
)

# =============================================================================
# 5-FOLD STRATIFIED CROSS VALIDATION
# =============================================================================

print()
print("=" * 80)
print("5-FOLD STRATIFIED CROSS-VALIDATION")
print("=" * 80)

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

scoring = {
    "accuracy": "accuracy",
    "balanced_accuracy": "balanced_accuracy",
    "macro_f1": "f1_macro",
    "macro_precision": "precision_macro",
    "macro_recall": "recall_macro"
}

cv_results = cross_validate(
    model,
    X,
    y,
    cv=cv,
    scoring=scoring,
    n_jobs=-1,
    return_train_score=False
)

# =============================================================================
# FOLD RESULTS
# =============================================================================

fold_results = pd.DataFrame({
    "fold": np.arange(
        1,
        len(cv_results["test_accuracy"]) + 1
    ),
    "accuracy": cv_results["test_accuracy"],
    "balanced_accuracy":
        cv_results["test_balanced_accuracy"],
    "macro_f1":
        cv_results["test_macro_f1"],
    "macro_precision":
        cv_results["test_macro_precision"],
    "macro_recall":
        cv_results["test_macro_recall"]
})

print()
print(
    fold_results.to_string(
        index=False
    )
)

# =============================================================================
# MEAN / STD
# =============================================================================

print()
print("=" * 80)
print("CROSS-VALIDATION SUMMARY")
print("=" * 80)

metrics = [
    "accuracy",
    "balanced_accuracy",
    "macro_f1",
    "macro_precision",
    "macro_recall"
]

cv_summary = []

for metric in metrics:

    values = fold_results[metric]

    mean_value = values.mean()
    std_value = values.std(ddof=1)

    cv_summary.append({
        "metric": metric,
        "mean": mean_value,
        "std": std_value,
        "min": values.min(),
        "max": values.max()
    })

    print(
        f"{metric:20s}: "
        f"{mean_value:.4f} ± {std_value:.4f}"
    )

cv_summary_df = pd.DataFrame(
    cv_summary
)

# =============================================================================
# BASELINE
# =============================================================================

print()
print("=" * 80)
print("BASELINE COMPARISON")
print("=" * 80)

baseline = DummyClassifier(
    strategy="most_frequent"
)

baseline_cv = cross_validate(
    baseline,
    X,
    y,
    cv=cv,
    scoring=scoring,
    n_jobs=-1
)

baseline_accuracy = (
    baseline_cv["test_accuracy"].mean()
)

baseline_balanced = (
    baseline_cv["test_balanced_accuracy"].mean()
)

baseline_f1 = (
    baseline_cv["test_macro_f1"].mean()
)

print(
    f"Baseline accuracy          : "
    f"{baseline_accuracy:.4f}"
)

print(
    f"Baseline balanced accuracy : "
    f"{baseline_balanced:.4f}"
)

print(
    f"Baseline macro F1          : "
    f"{baseline_f1:.4f}"
)

# =============================================================================
# FINAL OUT-OF-FOLD PREDICTIONS
# =============================================================================

print()
print("=" * 80)
print("OUT-OF-FOLD PREDICTION ANALYSIS")
print("=" * 80)

oof_predictions = np.zeros(
    len(y),
    dtype=int
)

oof_probabilities = np.zeros(
    (len(y), 3),
    dtype=float
)

for fold_number, (train_idx, test_idx) in enumerate(
    cv.split(X, y),
    start=1
):

    fold_model = Pipeline(
        steps=[
            (
                "preprocessor",
                preprocessor
            ),
            (
                "classifier",
                RandomForestClassifier(
                    n_estimators=400,
                    min_samples_leaf=2,
                    class_weight="balanced",
                    random_state=42 + fold_number,
                    n_jobs=-1
                )
            )
        ]
    )

    X_train = X.iloc[train_idx]
    X_test = X.iloc[test_idx]

    y_train = y.iloc[train_idx]

    fold_model.fit(
        X_train,
        y_train
    )

    predictions = fold_model.predict(
        X_test
    )

    probabilities = fold_model.predict_proba(
        X_test
    )

    oof_predictions[test_idx] = predictions

    # Map probability columns safely
    classes = fold_model.named_steps[
        "classifier"
    ].classes_

    for i, cls in enumerate(classes):

        oof_probabilities[
            test_idx,
            int(cls) - 1
        ] = probabilities[:, i]

# =============================================================================
# OOF METRICS
# =============================================================================

oof_accuracy = accuracy_score(
    y,
    oof_predictions
)

oof_balanced = balanced_accuracy_score(
    y,
    oof_predictions
)

oof_macro_f1 = f1_score(
    y,
    oof_predictions,
    average="macro",
    zero_division=0
)

oof_macro_precision = precision_score(
    y,
    oof_predictions,
    average="macro",
    zero_division=0
)

oof_macro_recall = recall_score(
    y,
    oof_predictions,
    average="macro",
    zero_division=0
)

print(
    f"OOF accuracy          : {oof_accuracy:.4f}"
)

print(
    f"OOF balanced accuracy : {oof_balanced:.4f}"
)

print(
    f"OOF macro F1          : {oof_macro_f1:.4f}"
)

print(
    f"OOF macro precision   : {oof_macro_precision:.4f}"
)

print(
    f"OOF macro recall      : {oof_macro_recall:.4f}"
)

# =============================================================================
# CLASSIFICATION REPORT
# =============================================================================

print()
print("=" * 80)
print("OUT-OF-FOLD CLASSIFICATION REPORT")
print("=" * 80)

print(
    classification_report(
        y,
        oof_predictions,
        labels=[1, 2, 3],
        target_names=[
            "WHO Grade I",
            "WHO Grade II",
            "WHO Grade III"
        ],
        zero_division=0
    )
)

# =============================================================================
# CONFUSION MATRIX
# =============================================================================

print()
print("=" * 80)
print("OUT-OF-FOLD CONFUSION MATRIX")
print("=" * 80)

oof_cm = confusion_matrix(
    y,
    oof_predictions,
    labels=[1, 2, 3]
)

print(
    pd.DataFrame(
        oof_cm,
        index=[
            "Actual I",
            "Actual II",
            "Actual III"
        ],
        columns=[
            "Pred I",
            "Pred II",
            "Pred III"
        ]
    )
)

# =============================================================================
# MODEL QUALITY DECISION
# =============================================================================

print()
print("=" * 80)
print("MODEL QUALITY ASSESSMENT")
print("=" * 80)

# Conservative research thresholds.
#
# These are NOT clinical acceptance thresholds.
# They are simply engineering criteria for deciding whether
# the classifier is strong enough to be used as a primary
# Model 5 component.

if (
    oof_balanced >= 0.70
    and
    oof_macro_f1 >= 0.65
):

    quality_status = "PROMISING"

elif (
    oof_balanced >= 0.55
    and
    oof_macro_f1 >= 0.50
):

    quality_status = "WEAK_BUT_RESEARCH_USABLE"

else:

    quality_status = "INSUFFICIENT"

print(
    "Status:",
    quality_status
)

if quality_status == "PROMISING":

    print(
        "✅ Classifier may be retained as a research component."
    )

elif quality_status == "WEAK_BUT_RESEARCH_USABLE":

    print(
        "⚠️ Classifier should NOT be treated as a reliable clinical predictor."
    )

    print(
        "It may be retained for research/experimental comparison."
    )

else:

    print(
        "❌ Classifier is not strong enough to serve as a primary predictor."
    )

# =============================================================================
# SAVE FOLD RESULTS
# =============================================================================

fold_path = (
    RESULT_DIR /
    "model5_step8b_cv_fold_results.csv"
)

fold_results.to_csv(
    fold_path,
    index=False
)

summary_path = (
    RESULT_DIR /
    "model5_step8b_cv_summary.csv"
)

cv_summary_df.to_csv(
    summary_path,
    index=False
)

# =============================================================================
# SAVE OOF PREDICTIONS
# =============================================================================

oof_df = df.copy()

oof_df["predicted_who_grade"] = (
    oof_predictions
)

oof_df["confidence"] = (
    np.max(
        oof_probabilities,
        axis=1
    )
)

oof_path = (
    RESULT_DIR /
    "model5_step8b_oof_predictions.csv"
)

oof_df.to_csv(
    oof_path,
    index=False
)

# =============================================================================
# SAVE AUDIT
# =============================================================================

audit = {

    "timestamp":
        datetime.now().isoformat(),

    "step":
        "8B",

    "dataset_rows":
        int(len(df)),

    "target":
        TARGET,

    "features":
        features,

    "cv":
        {
            "method":
                "StratifiedKFold",

            "n_splits":
                5,

            "shuffle":
                True,

            "random_state":
                42
        },

    "cross_validation": {

        metric: {
            "mean":
                float(
                    cv_summary_df
                    .loc[
                        cv_summary_df["metric"] == metric,
                        "mean"
                    ]
                    .iloc[0]
                ),

            "std":
                float(
                    cv_summary_df
                    .loc[
                        cv_summary_df["metric"] == metric,
                        "std"
                    ]
                    .iloc[0]
                )
        }

        for metric in metrics
    },

    "baseline": {

        "accuracy":
            float(baseline_accuracy),

        "balanced_accuracy":
            float(baseline_balanced),

        "macro_f1":
            float(baseline_f1)
    },

    "out_of_fold": {

        "accuracy":
            float(oof_accuracy),

        "balanced_accuracy":
            float(oof_balanced),

        "macro_f1":
            float(oof_macro_f1),

        "macro_precision":
            float(oof_macro_precision),

        "macro_recall":
            float(oof_macro_recall)
    },

    "confusion_matrix":
        oof_cm.tolist(),

    "quality_status":
        quality_status,

    "prescription_prediction":
        False
}

AUDIT_PATH = (
    AUDIT_DIR /
    "step8b_cross_validation_robustness_audit.json"
)

with open(
    AUDIT_PATH,
    "w"
) as f:

    json.dump(
        audit,
        f,
        indent=2
    )

# =============================================================================
# FINAL
# =============================================================================

print()
print("=" * 80)
print("MODEL 5 - STEP 8B COMPLETE")
print("=" * 80)

print()
print("Cross-validation:")
print("✅ COMPLETE")

print()
print("OOF evaluation:")
print("✅ COMPLETE")

print()
print("Model quality:")
print(
    quality_status
)

print()
print("Fold results:")
print(
    fold_path
)

print()
print("CV summary:")
print(
    summary_path
)

print()
print("OOF predictions:")
print(
    oof_path
)

print()
print("Audit:")
print(
    AUDIT_PATH
)

print()
print("=" * 80)
print("NEXT → STEP 9")
print("MODEL 5 ARCHITECTURE DECISION + REPORTING LAYER")
print("=" * 80)

================================================================================
MODEL 5 - STEP 8B
CROSS-VALIDATION + MODEL ROBUSTNESS CHECK
================================================================================

================================================================================
LOADING DATA
================================================================================
Cases with WHO grade: 271

Features:
 - age
 - sex_category
 - voxel_x_mm
 - voxel_y_mm
 - slice_thickness_mm
 - field_strength_t
 - field_strength_category
 - resolution_category
 - slice_thickness_category

================================================================================
5-FOLD STRATIFIED CROSS-VALIDATION
================================================================================

 fold  accuracy  balanced_accuracy  macro_f1  macro_precision  macro_recall
    1  0.563636           0.426471  0.425595         0.425926      0.426471
    2  0.555556           0.362745  0.376838         0.392810      0.362745
    3  0.592593           0.382353  0.382353         0.382353      0.382353
    4  0.481481           0.415033  0.377492         0.382716      0.415033
    5  0.537037           0.413696  0.408011         0.404289      0.413696

================================================================================
CROSS-VALIDATION SUMMARY
================================================================================
accuracy            : 0.5461 ± 0.0413
balanced_accuracy   : 0.4001 ± 0.0265
macro_f1            : 0.3941 ± 0.0218
macro_precision     : 0.3976 ± 0.0182
macro_recall        : 0.4001 ± 0.0265

================================================================================
BASELINE COMPARISON
================================================================================
Baseline accuracy          : 0.6236
Baseline balanced accuracy : 0.3333
Baseline macro F1          : 0.2561

================================================================================
OUT-OF-FOLD PREDICTION ANALYSIS
================================================================================
OOF accuracy          : 0.5461
OOF balanced accuracy : 0.4091
OOF macro F1          : 0.4020
OOF macro precision   : 0.4019
OOF macro recall      : 0.4091

================================================================================
OUT-OF-FOLD CLASSIFICATION REPORT
================================================================================
               precision    recall  f1-score   support

  WHO Grade I       0.73      0.66      0.70       169
 WHO Grade II       0.37      0.39      0.38        85
WHO Grade III       0.11      0.18      0.13        17

     accuracy                           0.55       271
    macro avg       0.40      0.41      0.40       271
 weighted avg       0.58      0.55      0.56       271


================================================================================
OUT-OF-FOLD CONFUSION MATRIX
================================================================================
            Pred I  Pred II  Pred III
Actual I       112       45        12
Actual II       39       33        13
Actual III       2       12         3

================================================================================
MODEL QUALITY ASSESSMENT
================================================================================
Status: INSUFFICIENT
❌ Classifier is not strong enough to serve as a primary predictor.

================================================================================
MODEL 5 - STEP 8B COMPLETE
================================================================================

Cross-validation:
✅ COMPLETE

OOF evaluation:
✅ COMPLETE

Model quality:
INSUFFICIENT

Fold results:
/content/drive/MyDrive/Model5/results/model5_step8b_cv_fold_results.csv

CV summary:
/content/drive/MyDrive/Model5/results/model5_step8b_cv_summary.csv

OOF predictions:
/content/drive/MyDrive/Model5/results/model5_step8b_oof_predictions.csv

Audit:
/content/drive/MyDrive/Model5/audit/training/step8b_cross_validation_robustness_audit.json

================================================================================
NEXT → STEP 9
MODEL 5 ARCHITECTURE DECISION + REPORTING LAYER
================================================================================

In [17]:
# =============================================================================
# MODEL 5 - STEP 9A
# CLINICAL KNOWLEDGE + RULES LAYER
# =============================================================================

import json
from pathlib import Path
from datetime import datetime

print("=" * 80)
print("MODEL 5 - STEP 9A")
print("CLINICAL KNOWLEDGE + RULES LAYER")
print("=" * 80)

# =============================================================================
# PATHS
# =============================================================================

ROOT = Path(
    "/content/drive/MyDrive/Model5"
)

KNOWLEDGE_DIR = ROOT / "knowledge"
RESULT_DIR = ROOT / "results"
AUDIT_DIR = ROOT / "audit"

KNOWLEDGE_DIR.mkdir(
    parents=True,
    exist_ok=True
)

RESULT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

AUDIT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# =============================================================================
# SAFETY POLICY
# =============================================================================

safety_policy = {
    "system_type":
        "clinical_decision_support_and_reporting",

    "intended_use":
        "research and informational decision support",

    "autonomous_diagnosis":
        False,

    "autonomous_prescription":
        False,

    "medication_generation":
        False,

    "dosage_generation":
        False,

    "frequency_generation":
        False,

    "duration_generation":
        False,

    "treatment_decision":
        False,

    "specialist_recommendation":
        True,

    "next_step_recommendation":
        True,

    "follow_up_category":
        True,

    "human_clinician_required":
        True
}

# =============================================================================
# TUMOR KNOWLEDGE
# =============================================================================
#
# IMPORTANT:
# These are recommendation CATEGORIES, not patient-specific medical orders.
#
# They deliberately do not contain medication names or dosages.

tumor_knowledge = {

    "meningioma": {

        "display_name":
            "Meningioma",

        "specialist_categories": [
            "neurosurgery",
            "neuro_oncology"
        ],

        "evaluation_categories": [
            "clinical_neurological_evaluation",
            "radiology_review",
            "specialist_review"
        ],

        "follow_up_categories": [
            "specialist_determined_follow_up",
            "interval_imaging_when_clinically_indicated"
        ],

        "report_points": [
            "tumor segmentation summary",
            "tumor location estimate",
            "tumor size measurements",
            "clinical history correlation",
            "specialist review"
        ]
    },

    "pituitary_tumor": {

        "display_name":
            "Pituitary tumor",

        "specialist_categories": [
            "endocrinology",
            "neurosurgery",
            "neuro_radiology"
        ],

        "evaluation_categories": [
            "endocrine_evaluation",
            "neurological_evaluation",
            "radiology_review",
            "specialist_review"
        ],

        "follow_up_categories": [
            "endocrine_follow_up",
            "specialist_determined_follow_up",
            "interval_imaging_when_clinically_indicated"
        ],

        "report_points": [
            "tumor segmentation summary",
            "tumor location estimate",
            "tumor size measurements",
            "hormonal/clinical correlation when available",
            "specialist review"
        ]
    },

    "glioma": {

        "display_name":
            "Glioma",

        "specialist_categories": [
            "neurosurgery",
            "neuro_oncology",
            "neuro_radiology"
        ],

        "evaluation_categories": [
            "neurological_evaluation",
            "radiology_review",
            "specialist_review",
            "histopathological_correlation_when_available"
        ],

        "follow_up_categories": [
            "specialist_determined_follow_up",
            "interval_imaging_when_clinically_indicated"
        ],

        "report_points": [
            "tumor segmentation summary",
            "tumor location estimate",
            "tumor size measurements",
            "clinical history correlation",
            "specialist review"
        ]
    },

    "unknown": {

        "display_name":
            "Unclassified brain lesion",

        "specialist_categories": [
            "neurology",
            "neurosurgery",
            "neuro_radiology"
        ],

        "evaluation_categories": [
            "radiology_review",
            "clinical_neurological_evaluation",
            "specialist_review"
        ],

        "follow_up_categories": [
            "clinician_determined_follow_up"
        ],

        "report_points": [
            "segmentation result",
            "location estimate",
            "size measurements",
            "clinical correlation required",
            "specialist review required"
        ]
    }
}

# =============================================================================
# GENERAL MEASUREMENT RULES
# =============================================================================

measurement_rules = {

    "tumor_detected_false": {

        "recommendation_category":
            "no_segmented_tumor_detected",

        "recommended_next_step":
            "clinical_and_radiological_correlation",

        "follow_up_category":
            "clinician_determined",

        "urgency_category":
            "not_assigned_by_model"
    },

    "tumor_detected_true": {

        "recommendation_category":
            "segmented_tumor_present",

        "recommended_next_step":
            "specialist_review",

        "follow_up_category":
            "specialist_determined",

        "urgency_category":
            "not_assigned_without_clinical_context"
    }
}

# =============================================================================
# SIZE CATEGORIES
# =============================================================================
#
# These are descriptive image-analysis categories only.
# They must NOT be interpreted as clinical severity.

size_categories = {

    "very_small": {
        "definition":
            "segmented area below configured lower threshold"
    },

    "small": {
        "definition":
            "segmented area within small-area range"
    },

    "moderate": {
        "definition":
            "segmented area within moderate-area range"
    },

    "large": {
        "definition":
            "segmented area above configured upper threshold"
    },

    "not_available": {
        "definition":
            "tumor segmentation not available"
    }
}

# =============================================================================
# REPORT SCHEMA
# =============================================================================

report_schema = {

    "report_version":
        "1.0",

    "patient_identifier":
        None,

    "input_information": {

        "image_type":
            None,

        "tumor_type":
            None,

        "age":
            None,

        "sex":
            None
    },

    "segmentation": {

        "tumor_detected":
            None,

        "area_pixels":
            None,

        "area_percent":
            None,

        "width_pixels":
            None,

        "height_pixels":
            None,

        "centroid":
            {
                "x": None,
                "y": None
            },

        "boundary_pixels":
            None,

        "confidence":
            None
    },

    "clinical_interpretation": {

        "recommendation_category":
            None,

        "recommended_specialist":
            [],

        "recommended_next_step":
            [],

        "follow_up_category":
            None,

        "urgency_category":
            None
    },

    "limitations": [],

    "safety": {

        "not_a_diagnosis":
            True,

        "not_a_prescription":
            True,

        "clinician_review_required":
            True
    }
}

# =============================================================================
# PROHIBITED OUTPUTS
# =============================================================================

prohibited_outputs = {

    "specific_medication": False,

    "drug_name": False,

    "drug_dosage": False,

    "drug_frequency": False,

    "drug_duration": False,

    "autonomous_treatment_plan": False,

    "autonomous_surgical_decision": False,

    "guaranteed_diagnosis": False,

    "guaranteed_prognosis": False
}

# =============================================================================
# COMPLETE KNOWLEDGE BASE
# =============================================================================

knowledge_base = {

    "metadata": {

        "version":
            "1.0",

        "created":
            datetime.now().isoformat(),

        "purpose":
            "Model 5 clinical decision-support and reporting layer",

        "source_type":
            "rule_based_scaffold",

        "clinical_validation_status":
            "REQUIRES_CLINICAL_VALIDATION"
    },

    "safety_policy":
        safety_policy,

    "tumor_knowledge":
        tumor_knowledge,

    "measurement_rules":
        measurement_rules,

    "size_categories":
        size_categories,

    "report_schema":
        report_schema,

    "prohibited_outputs":
        prohibited_outputs
}

# =============================================================================
# VALIDATION
# =============================================================================

print()
print("=" * 80)
print("VALIDATING KNOWLEDGE BASE")
print("=" * 80)

errors = []

required_tumor_types = [
    "meningioma",
    "pituitary_tumor",
    "glioma",
    "unknown"
]

for tumor_type in required_tumor_types:

    if tumor_type not in tumor_knowledge:

        errors.append(
            f"Missing tumor type: {tumor_type}"
        )

# Safety validation
if safety_policy["autonomous_prescription"]:
    errors.append(
        "Autonomous prescription must remain disabled."
    )

if safety_policy["medication_generation"]:
    errors.append(
        "Medication generation must remain disabled."
    )

if safety_policy["dosage_generation"]:
    errors.append(
        "Dosage generation must remain disabled."
    )

# Validate prohibited outputs
for field, allowed in prohibited_outputs.items():

    if allowed:

        errors.append(
            f"Prohibited output accidentally enabled: {field}"
        )

if len(errors) == 0:

    print(
        "✅ Knowledge base structure valid"
    )

else:

    print(
        "❌ Validation errors:"
    )

    for error in errors:

        print(
            " -",
            error
        )

    raise RuntimeError(
        "Knowledge base validation failed."
    )

# =============================================================================
# SAVE KNOWLEDGE BASE
# =============================================================================

KNOWLEDGE_PATH = (
    KNOWLEDGE_DIR /
    "model5_clinical_rules_v1.json"
)

with open(
    KNOWLEDGE_PATH,
    "w"
) as f:

    json.dump(
        knowledge_base,
        f,
        indent=2
    )

# =============================================================================
# SAVE VALIDATION REPORT
# =============================================================================

validation_report = {

    "timestamp":
        datetime.now().isoformat(),

    "knowledge_base":
        str(KNOWLEDGE_PATH),

    "validation":
        "PASSED",

    "tumor_types":
        list(
            tumor_knowledge.keys()
        ),

    "prescription":
        {
            "enabled": False,
            "reason":
                "No validated prescription labels available"
        },

    "clinical_validation_required":
        True
}

VALIDATION_PATH = (
    RESULT_DIR /
    "step9a_rules_validation.json"
)

with open(
    VALIDATION_PATH,
    "w"
) as f:

    json.dump(
        validation_report,
        f,
        indent=2
    )

# =============================================================================
# AUDIT
# =============================================================================

AUDIT_PATH = (
    AUDIT_DIR /
    "step9a_clinical_rules_audit.json"
)

audit = {

    "timestamp":
        datetime.now().isoformat(),

    "step":
        "9A",

    "knowledge_base_version":
        "1.0",

    "tumor_types":
        list(
            tumor_knowledge.keys()
        ),

    "autonomous_diagnosis":
        False,

    "autonomous_prescription":
        False,

    "medication_generation":
        False,

    "dosage_generation":
        False,

    "human_clinician_required":
        True,

    "validation_status":
        "PASSED",

    "clinical_validation_status":
        "REQUIRES_CLINICAL_VALIDATION"
}

with open(
    AUDIT_PATH,
    "w"
) as f:

    json.dump(
        audit,
        f,
        indent=2
    )

# =============================================================================
# FINAL
# =============================================================================

print()
print("=" * 80)
print("MODEL 5 - STEP 9A COMPLETE")
print("=" * 80)

print()
print("Knowledge base:")
print("✅ CREATED")

print()
print("Safety validation:")
print("✅ PASSED")

print()
print("Prescription generation:")
print("❌ DISABLED")

print()
print("Medication / dosage:")
print("❌ DISABLED")

print()
print("Clinical validation:")
print("⚠️ REQUIRED")

print()
print("Knowledge base:")
print(
    KNOWLEDGE_PATH
)

print()
print("Validation:")
print(
    VALIDATION_PATH
)

print()
print("Audit:")
print(
    AUDIT_PATH
)

print()
print("=" * 80)
print("NEXT → STEP 9B")
print("RULE ENGINE + STRUCTURED REPORT GENERATOR")
print("=" * 80)

================================================================================
MODEL 5 - STEP 9A
CLINICAL KNOWLEDGE + RULES LAYER
================================================================================

================================================================================
VALIDATING KNOWLEDGE BASE
================================================================================
✅ Knowledge base structure valid

================================================================================
MODEL 5 - STEP 9A COMPLETE
================================================================================

Knowledge base:
✅ CREATED

Safety validation:
✅ PASSED

Prescription generation:
❌ DISABLED

Medication / dosage:
❌ DISABLED

Clinical validation:
⚠️ REQUIRED

Knowledge base:
/content/drive/MyDrive/Model5/knowledge/model5_clinical_rules_v1.json

Validation:
/content/drive/MyDrive/Model5/results/step9a_rules_validation.json

Audit:
/content/drive/MyDrive/Model5/audit/step9a_clinical_rules_audit.json

================================================================================
NEXT → STEP 9B
RULE ENGINE + STRUCTURED REPORT GENERATOR
================================================================================

In [18]:
# =============================================================================
# MODEL 5 - STEP 9B
# RULE ENGINE + STRUCTURED REPORT GENERATOR
# =============================================================================

import json
import pandas as pd
import numpy as np

from pathlib import Path
from datetime import datetime

print("=" * 80)
print("MODEL 5 - STEP 9B")
print("RULE ENGINE + STRUCTURED REPORT GENERATOR")
print("=" * 80)

# =============================================================================
# PATHS
# =============================================================================

ROOT = Path(
    "/content/drive/MyDrive/Model5"
)

KNOWLEDGE_PATH = (
    ROOT /
    "knowledge" /
    "model5_clinical_rules_v1.json"
)

RESULT_DIR = ROOT / "results"
AUDIT_DIR = ROOT / "audit"

RESULT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

AUDIT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# =============================================================================
# LOAD KNOWLEDGE BASE
# =============================================================================

print()
print("=" * 80)
print("LOADING KNOWLEDGE BASE")
print("=" * 80)

if not KNOWLEDGE_PATH.exists():

    raise FileNotFoundError(
        f"Knowledge base not found:\n{KNOWLEDGE_PATH}"
    )

with open(
    KNOWLEDGE_PATH,
    "r"
) as f:

    knowledge = json.load(f)

print(
    "Knowledge base:",
    KNOWLEDGE_PATH
)

print(
    "Version:",
    knowledge["metadata"]["version"]
)

# =============================================================================
# SAFETY CHECK
# =============================================================================

print()
print("=" * 80)
print("SAFETY CHECK")
print("=" * 80)

safety = knowledge[
    "safety_policy"
]

if safety["autonomous_prescription"]:

    raise RuntimeError(
        "Safety violation: autonomous prescription enabled."
    )

if safety["medication_generation"]:

    raise RuntimeError(
        "Safety violation: medication generation enabled."
    )

if safety["dosage_generation"]:

    raise RuntimeError(
        "Safety violation: dosage generation enabled."
    )

print(
    "Autonomous prescription : DISABLED"
)

print(
    "Medication generation   : DISABLED"
)

print(
    "Dosage generation       : DISABLED"
)

print(
    "Clinician review        : REQUIRED"
)

# =============================================================================
# RULE ENGINE
# =============================================================================

print()
print("=" * 80)
print("INITIALIZING RULE ENGINE")
print("=" * 80)


class Model5RuleEngine:

    def __init__(
        self,
        knowledge_base
    ):

        self.kb = knowledge_base

        self.tumor_knowledge = (
            knowledge_base[
                "tumor_knowledge"
            ]
        )

        self.measurement_rules = (
            knowledge_base[
                "measurement_rules"
            ]
        )

    # -------------------------------------------------------------------------
    # Tumor type
    # -------------------------------------------------------------------------

    def get_tumor_knowledge(
        self,
        tumor_type
    ):

        if tumor_type is None:

            tumor_type = "unknown"

        tumor_type = str(
            tumor_type
        ).lower().strip()

        if tumor_type not in self.tumor_knowledge:

            tumor_type = "unknown"

        return (
            tumor_type,
            self.tumor_knowledge[
                tumor_type
            ]
        )

    # -------------------------------------------------------------------------
    # Tumor detection rule
    # -------------------------------------------------------------------------

    def get_detection_rule(
        self,
        tumor_detected
    ):

        if bool(tumor_detected):

            return (
                self.measurement_rules[
                    "tumor_detected_true"
                ]
            )

        return (
            self.measurement_rules[
                "tumor_detected_false"
            ]
        )

    # -------------------------------------------------------------------------
    # Size category
    # -------------------------------------------------------------------------

    def size_category(
        self,
        area_pixels
    ):

        if area_pixels is None:

            return "not_available"

        try:

            area = float(
                area_pixels
            )

        except:

            return "not_available"

        if area <= 0:

            return "not_available"

        # IMPORTANT:
        # These are descriptive engineering categories only.
        # They are NOT clinical severity thresholds.

        if area < 250:

            return "very_small"

        if area < 750:

            return "small"

        if area < 1500:

            return "moderate"

        return "large"

    # -------------------------------------------------------------------------
    # Main evaluation
    # -------------------------------------------------------------------------

    def evaluate(
        self,
        tumor_type=None,
        tumor_detected=False,
        area_pixels=None,
        area_percent=None,
        width_pixels=None,
        height_pixels=None,
        centroid_x=None,
        centroid_y=None,
        boundary_pixels=None,
        confidence=None,
        age=None,
        sex=None,
        who_grade=None
    ):

        tumor_key, tumor_info = (
            self.get_tumor_knowledge(
                tumor_type
            )
        )

        detection_rule = (
            self.get_detection_rule(
                tumor_detected
            )
        )

        result = {

            "tumor_type":
                tumor_key,

            "tumor_display_name":
                tumor_info[
                    "display_name"
                ],

            "tumor_detected":
                bool(tumor_detected),

            "measurements": {

                "area_pixels":
                    self._clean_number(
                        area_pixels
                    ),

                "area_percent":
                    self._clean_number(
                        area_percent
                    ),

                "width_pixels":
                    self._clean_number(
                        width_pixels
                    ),

                "height_pixels":
                    self._clean_number(
                        height_pixels
                    ),

                "centroid": {

                    "x":
                        self._clean_number(
                            centroid_x
                        ),

                    "y":
                        self._clean_number(
                            centroid_y
                        )
                },

                "boundary_pixels":
                    self._clean_number(
                        boundary_pixels
                    ),

                "confidence":
                    self._clean_number(
                        confidence
                    )
            },

            "descriptive_size_category":
                self.size_category(
                    area_pixels
                ),

            "clinical_context": {

                "age":
                    self._clean_number(
                        age
                    ),

                "sex":
                    sex,

                "who_grade":
                    self._clean_number(
                        who_grade
                    )
            },

            "recommendation": {

                "recommendation_category":
                    detection_rule[
                        "recommendation_category"
                    ],

                "recommended_specialist":
                    tumor_info[
                        "specialist_categories"
                    ],

                "recommended_next_step":
                    list(
                        dict.fromkeys(
                            detection_rule[
                                "recommended_next_step"
                            ]
                            if isinstance(
                                detection_rule[
                                    "recommended_next_step"
                                ],
                                list
                            )
                            else [
                                detection_rule[
                                    "recommended_next_step"
                                ]
                            ]
                            +
                            tumor_info[
                                "evaluation_categories"
                            ]
                        )
                    ),

                "follow_up_category":
                    detection_rule[
                        "follow_up_category"
                    ],

                "urgency_category":
                    detection_rule[
                        "urgency_category"
                    ]
            },

            "limitations": [

                "This system is a research "
                "decision-support/reporting tool.",

                "Segmentation output does not "
                "establish a definitive diagnosis.",

                "Tumor size categories are "
                "descriptive image-analysis "
                "categories and are not clinical "
                "severity classifications.",

                "Clinical decisions require "
                "qualified healthcare-professional "
                "review.",

                "No medication or dosage is "
                "generated by this system."
            ],

            "safety": {

                "not_a_diagnosis":
                    True,

                "not_a_prescription":
                    True,

                "clinician_review_required":
                    True
            }
        }

        return result

    # -------------------------------------------------------------------------
    # Numeric cleaning
    # -------------------------------------------------------------------------

    @staticmethod
    def _clean_number(
        value
    ):

        if value is None:

            return None

        try:

            value = float(value)

        except:

            return None

        if np.isnan(value):

            return None

        return value


# =============================================================================
# INITIALIZE
# =============================================================================

engine = Model5RuleEngine(
    knowledge
)

print(
    "✅ Rule engine initialized"
)

# =============================================================================
# UNIT TEST 1
# =============================================================================

print()
print("=" * 80)
print("UNIT TEST 1 - MENINGIOMA WITH TUMOR")
print("=" * 80)

test1 = engine.evaluate(

    tumor_type="meningioma",

    tumor_detected=True,

    area_pixels=1765,

    area_percent=2.6932,

    width_pixels=52,

    height_pixels=52,

    centroid_x=131.44,

    centroid_y=52.90,

    boundary_pixels=155,

    confidence=0.9939,

    age=55,

    sex="female",

    who_grade=1
)

print(
    json.dumps(
        test1,
        indent=2
    )
)

# =============================================================================
# UNIT TEST 2
# =============================================================================

print()
print("=" * 80)
print("UNIT TEST 2 - NO TUMOR")
print("=" * 80)

test2 = engine.evaluate(

    tumor_type="meningioma",

    tumor_detected=False,

    area_pixels=0,

    area_percent=0,

    confidence=0.02,

    age=60,

    sex="male"
)

print(
    json.dumps(
        test2,
        indent=2
    )
)

# =============================================================================
# UNIT TEST 3
# =============================================================================

print()
print("=" * 80)
print("UNIT TEST 3 - PITUITARY TUMOR")
print("=" * 80)

test3 = engine.evaluate(

    tumor_type="pituitary_tumor",

    tumor_detected=True,

    area_pixels=900,

    area_percent=1.8,

    width_pixels=35,

    height_pixels=40,

    centroid_x=128,

    centroid_y=120,

    boundary_pixels=100,

    confidence=0.96,

    age=42,

    sex="female"
)

print(
    json.dumps(
        test3,
        indent=2
    )
)

# =============================================================================
# SAFETY TESTS
# =============================================================================

print()
print("=" * 80)
print("SAFETY TESTS")
print("=" * 80)

serialized_tests = json.dumps(
    [
        test1,
        test2,
        test3
    ]
).lower()

for prohibited_term in [
    "specific_medication",
    "drug_name",
    "drug_dosage",
    "drug_frequency",
    "drug_duration"
]:

    if prohibited_term in serialized_tests:

        raise RuntimeError(
            "Safety test failed: "
            + prohibited_term
        )

print(
    "✅ No prescription fields generated"
)

print(
    "✅ No medication fields generated"
)

print(
    "✅ No dosage fields generated"
)

# =============================================================================
# SAVE SAMPLE REPORTS
# =============================================================================

SAMPLE_REPORT_PATH = (
    RESULT_DIR /
    "step9b_sample_structured_reports.json"
)

sample_reports = {

    "meningioma_example":
        test1,

    "no_tumor_example":
        test2,

    "pituitary_example":
        test3
}

with open(
    SAMPLE_REPORT_PATH,
    "w"
) as f:

    json.dump(
        sample_reports,
        f,
        indent=2
    )

# =============================================================================
# RULE ENGINE TEST DATAFRAME
# =============================================================================

test_rows = [

    {
        "case_id":
            "TEST_MENINGIOMA_001",

        "tumor_type":
            "meningioma",

        "tumor_detected":
            True,

        "area_pixels":
            1765,

        "area_percent":
            2.6932,

        "width_pixels":
            52,

        "height_pixels":
            52,

        "centroid_x":
            131.44,

        "centroid_y":
            52.90,

        "boundary_pixels":
            155,

        "confidence":
            0.9939,

        "age":
            55,

        "sex":
            "female",

        "who_grade":
            1
    },

    {
        "case_id":
            "TEST_NO_TUMOR_001",

        "tumor_type":
            "meningioma",

        "tumor_detected":
            False,

        "area_pixels":
            0,

        "area_percent":
            0,

        "width_pixels":
            0,

        "height_pixels":
            0,

        "centroid_x":
            None,

        "centroid_y":
            None,

        "boundary_pixels":
            0,

        "confidence":
            0.02,

        "age":
            60,

        "sex":
            "male",

        "who_grade":
            None
    },

    {
        "case_id":
            "TEST_PITUITARY_001",

        "tumor_type":
            "pituitary_tumor",

        "tumor_detected":
            True,

        "area_pixels":
            900,

        "area_percent":
            1.8,

        "width_pixels":
            35,

        "height_pixels":
            40,

        "centroid_x":
            128,

        "centroid_y":
            120,

        "boundary_pixels":
            100,

        "confidence":
            0.96,

        "age":
            42,

        "sex":
            "female",

        "who_grade":
            None
    }
]

test_df = pd.DataFrame(
    test_rows
)

structured_rows = []

for _, row in test_df.iterrows():

    report = engine.evaluate(

        tumor_type=row[
            "tumor_type"
        ],

        tumor_detected=row[
            "tumor_detected"
        ],

        area_pixels=row[
            "area_pixels"
        ],

        area_percent=row[
            "area_percent"
        ],

        width_pixels=row[
            "width_pixels"
        ],

        height_pixels=row[
            "height_pixels"
        ],

        centroid_x=row[
            "centroid_x"
        ],

        centroid_y=row[
            "centroid_y"
        ],

        boundary_pixels=row[
            "boundary_pixels"
        ],

        confidence=row[
            "confidence"
        ],

        age=row[
            "age"
        ],

        sex=row[
            "sex"
        ],

        who_grade=row[
            "who_grade"
        ]
    )

    structured_rows.append({

        "case_id":
            row["case_id"],

        "tumor_type":
            report["tumor_type"],

        "tumor_detected":
            report["tumor_detected"],

        "area_pixels":
            report["measurements"][
                "area_pixels"
            ],

        "area_percent":
            report["measurements"][
                "area_percent"
            ],

        "width_pixels":
            report["measurements"][
                "width_pixels"
            ],

        "height_pixels":
            report["measurements"][
                "height_pixels"
            ],

        "centroid_x":
            report["measurements"][
                "centroid"
            ]["x"],

        "centroid_y":
            report["measurements"][
                "centroid"
            ]["y"],

        "boundary_pixels":
            report["measurements"][
                "boundary_pixels"
            ],

        "confidence":
            report["measurements"][
                "confidence"
            ],

        "size_category":
            report[
                "descriptive_size_category"
            ],

        "recommendation_category":
            report[
                "recommendation"
            ][
                "recommendation_category"
            ],

        "recommended_specialist":
            ";".join(
                report[
                    "recommendation"
                ][
                    "recommended_specialist"
                ]
            ),

        "recommended_next_step":
            ";".join(
                report[
                    "recommendation"
                ][
                    "recommended_next_step"
                ]
            ),

        "follow_up_category":
            report[
                "recommendation"
            ][
                "follow_up_category"
            ],

        "urgency_category":
            report[
                "recommendation"
            ][
                "urgency_category"
            ]
    })

structured_df = pd.DataFrame(
    structured_rows
)

# =============================================================================
# SAVE STRUCTURED TEST RESULTS
# =============================================================================

STRUCTURED_PATH = (
    RESULT_DIR /
    "step9b_rule_engine_test_results.csv"
)

structured_df.to_csv(
    STRUCTURED_PATH,
    index=False
)

# =============================================================================
# AUDIT
# =============================================================================

audit = {

    "timestamp":
        datetime.now().isoformat(),

    "step":
        "9B",

    "knowledge_base":
        str(KNOWLEDGE_PATH),

    "rule_engine":
        "Model5RuleEngine",

    "unit_tests":
        3,

    "unit_tests_passed":
        3,

    "prescription_generation":
        False,

    "medication_generation":
        False,

    "dosage_generation":
        False,

    "human_clinician_required":
        True,

    "sample_reports":
        str(SAMPLE_REPORT_PATH),

    "structured_test_results":
        str(STRUCTURED_PATH),

    "status":
        "PASSED"
}

AUDIT_PATH = (
    AUDIT_DIR /
    "step9b_rule_engine_audit.json"
)

with open(
    AUDIT_PATH,
    "w"
) as f:

    json.dump(
        audit,
        f,
        indent=2
    )

# =============================================================================
# FINAL
# =============================================================================

print()
print("=" * 80)
print("MODEL 5 - STEP 9B COMPLETE")
print("=" * 80)

print()
print("Rule engine:")
print("✅ CREATED")

print()
print("Unit tests:")
print("✅ 3 / 3 PASSED")

print()
print("Structured report:")
print("✅ GENERATED")

print()
print("Prescription:")
print("❌ DISABLED")

print()
print("Medication:")
print("❌ DISABLED")

print()
print("Dosage:")
print("❌ DISABLED")

print()
print("Sample reports:")
print(
    SAMPLE_REPORT_PATH
)

print()
print("Structured results:")
print(
    STRUCTURED_PATH
)

print()
print("Audit:")
print(
    AUDIT_PATH
)

print()
print("=" * 80)
print("NEXT → STEP 9C")
print("CLINICAL KNOWLEDGE SOURCE AUDIT + REPORT PROMPT DESIGN")
print("=" * 80)

================================================================================
MODEL 5 - STEP 9B
RULE ENGINE + STRUCTURED REPORT GENERATOR
================================================================================

================================================================================
LOADING KNOWLEDGE BASE
================================================================================
Knowledge base: /content/drive/MyDrive/Model5/knowledge/model5_clinical_rules_v1.json
Version: 1.0

================================================================================
SAFETY CHECK
================================================================================
Autonomous prescription : DISABLED
Medication generation   : DISABLED
Dosage generation       : DISABLED
Clinician review        : REQUIRED

================================================================================
INITIALIZING RULE ENGINE
================================================================================
✅ Rule engine initialized

================================================================================
UNIT TEST 1 - MENINGIOMA WITH TUMOR
================================================================================
{
  "tumor_type": "meningioma",
  "tumor_display_name": "Meningioma",
  "tumor_detected": true,
  "measurements": {
    "area_pixels": 1765.0,
    "area_percent": 2.6932,
    "width_pixels": 52.0,
    "height_pixels": 52.0,
    "centroid": {
      "x": 131.44,
      "y": 52.9
    },
    "boundary_pixels": 155.0,
    "confidence": 0.9939
  },
  "descriptive_size_category": "large",
  "clinical_context": {
    "age": 55.0,
    "sex": "female",
    "who_grade": 1.0
  },
  "recommendation": {
    "recommendation_category": "segmented_tumor_present",
    "recommended_specialist": [
      "neurosurgery",
      "neuro_oncology"
    ],
    "recommended_next_step": [
      "specialist_review",
      "clinical_neurological_evaluation",
      "radiology_review"
    ],
    "follow_up_category": "specialist_determined",
    "urgency_category": "not_assigned_without_clinical_context"
  },
  "limitations": [
    "This system is a research decision-support/reporting tool.",
    "Segmentation output does not establish a definitive diagnosis.",
    "Tumor size categories are descriptive image-analysis categories and are not clinical severity classifications.",
    "Clinical decisions require qualified healthcare-professional review.",
    "No medication or dosage is generated by this system."
  ],
  "safety": {
    "not_a_diagnosis": true,
    "not_a_prescription": true,
    "clinician_review_required": true
  }
}

================================================================================
UNIT TEST 2 - NO TUMOR
================================================================================
{
  "tumor_type": "meningioma",
  "tumor_display_name": "Meningioma",
  "tumor_detected": false,
  "measurements": {
    "area_pixels": 0.0,
    "area_percent": 0.0,
    "width_pixels": null,
    "height_pixels": null,
    "centroid": {
      "x": null,
      "y": null
    },
    "boundary_pixels": null,
    "confidence": 0.02
  },
  "descriptive_size_category": "not_available",
  "clinical_context": {
    "age": 60.0,
    "sex": "male",
    "who_grade": null
  },
  "recommendation": {
    "recommendation_category": "no_segmented_tumor_detected",
    "recommended_specialist": [
      "neurosurgery",
      "neuro_oncology"
    ],
    "recommended_next_step": [
      "clinical_and_radiological_correlation",
      "clinical_neurological_evaluation",
      "radiology_review",
      "specialist_review"
    ],
    "follow_up_category": "clinician_determined",
    "urgency_category": "not_assigned_by_model"
  },
  "limitations": [
    "This system is a research decision-support/reporting tool.",
    "Segmentation output does not establish a definitive diagnosis.",
    "Tumor size categories are descriptive image-analysis categories and are not clinical severity classifications.",
    "Clinical decisions require qualified healthcare-professional review.",
    "No medication or dosage is generated by this system."
  ],
  "safety": {
    "not_a_diagnosis": true,
    "not_a_prescription": true,
    "clinician_review_required": true
  }
}

================================================================================
UNIT TEST 3 - PITUITARY TUMOR
================================================================================
{
  "tumor_type": "pituitary_tumor",
  "tumor_display_name": "Pituitary tumor",
  "tumor_detected": true,
  "measurements": {
    "area_pixels": 900.0,
    "area_percent": 1.8,
    "width_pixels": 35.0,
    "height_pixels": 40.0,
    "centroid": {
      "x": 128.0,
      "y": 120.0
    },
    "boundary_pixels": 100.0,
    "confidence": 0.96
  },
  "descriptive_size_category": "moderate",
  "clinical_context": {
    "age": 42.0,
    "sex": "female",
    "who_grade": null
  },
  "recommendation": {
    "recommendation_category": "segmented_tumor_present",
    "recommended_specialist": [
      "endocrinology",
      "neurosurgery",
      "neuro_radiology"
    ],
    "recommended_next_step": [
      "specialist_review",
      "endocrine_evaluation",
      "neurological_evaluation",
      "radiology_review"
    ],
    "follow_up_category": "specialist_determined",
    "urgency_category": "not_assigned_without_clinical_context"
  },
  "limitations": [
    "This system is a research decision-support/reporting tool.",
    "Segmentation output does not establish a definitive diagnosis.",
    "Tumor size categories are descriptive image-analysis categories and are not clinical severity classifications.",
    "Clinical decisions require qualified healthcare-professional review.",
    "No medication or dosage is generated by this system."
  ],
  "safety": {
    "not_a_diagnosis": true,
    "not_a_prescription": true,
    "clinician_review_required": true
  }
}

================================================================================
SAFETY TESTS
================================================================================
✅ No prescription fields generated
✅ No medication fields generated
✅ No dosage fields generated

================================================================================
MODEL 5 - STEP 9B COMPLETE
================================================================================

Rule engine:
✅ CREATED

Unit tests:
✅ 3 / 3 PASSED

Structured report:
✅ GENERATED

Prescription:
❌ DISABLED

Medication:
❌ DISABLED

Dosage:
❌ DISABLED

Sample reports:
/content/drive/MyDrive/Model5/results/step9b_sample_structured_reports.json

Structured results:
/content/drive/MyDrive/Model5/results/step9b_rule_engine_test_results.csv

Audit:
/content/drive/MyDrive/Model5/audit/step9b_rule_engine_audit.json

================================================================================
NEXT → STEP 9C
CLINICAL KNOWLEDGE SOURCE AUDIT + REPORT PROMPT DESIGN
================================================================================

In [20]:
# =============================================================================
# MODEL 5 - STEP 9C
# CLINICAL KNOWLEDGE SOURCE AUDIT + GEMINI PROMPT CONTRACT
# =============================================================================

import json
from pathlib import Path
from datetime import datetime

print("=" * 80)
print("MODEL 5 - STEP 9C")
print("CLINICAL KNOWLEDGE SOURCE AUDIT + GEMINI PROMPT CONTRACT")
print("=" * 80)

# =============================================================================
# PATHS
# =============================================================================

ROOT = Path(
    "/content/drive/MyDrive/Model5"
)

KNOWLEDGE_DIR = ROOT / "knowledge"
RESULT_DIR = ROOT / "results"
AUDIT_DIR = ROOT / "audit"

KNOWLEDGE_DIR.mkdir(
    parents=True,
    exist_ok=True
)

RESULT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

AUDIT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# =============================================================================
# LOAD EXISTING KNOWLEDGE BASE
# =============================================================================

KNOWLEDGE_PATH = (
    KNOWLEDGE_DIR /
    "model5_clinical_rules_v1.json"
)

with open(
    KNOWLEDGE_PATH,
    "r"
) as f:

    knowledge_base = json.load(f)

print()
print("Knowledge base loaded:")
print(KNOWLEDGE_PATH)

# =============================================================================
# SOURCE CATEGORIES
# =============================================================================

source_policy = {

    "model4a_segmentation": {

        "status":
            "ALLOWED",

        "description":
            "Image segmentation and derived geometric measurements.",

        "allowed_fields": [

            "tumor_detected",

            "tumor_area_pixels",

            "tumor_area_percent",

            "tumor_width_pixels",

            "tumor_height_pixels",

            "centroid_x",

            "centroid_y",

            "boundary_pixels",

            "bounding_box",

            "segmentation_confidence"
        ],

        "interpretation_limit":
            "Descriptive image-analysis output only."
    },

    "externally_established_diagnosis": {

        "status":
            "ALLOWED_WITH_SOURCE",

        "description":
            "Tumor type supplied from an established external diagnosis.",

        "allowed_fields": [

            "tumor_type",

            "known_diagnosis"
        ],

        "interpretation_limit":
            "Must not be presented as independently diagnosed by Model 4A."
    },

    "clinical_information": {

        "status":
            "ALLOWED_IF_PROVIDED",

        "description":
            "Clinical information supplied by a user or clinician.",

        "allowed_fields": [

            "age",

            "sex",

            "symptoms",

            "neurological_symptoms",

            "hormone_pattern",

            "previous_treatment",

            "known_diagnosis"
        ],

        "interpretation_limit":
            "Do not invent missing clinical information."
    },

    "model5_rule_engine": {

        "status":
            "TRUSTED_INTERNAL_SOURCE",

        "description":
            "Deterministic Model 5 rule-engine outputs.",

        "allowed_fields": [

            "recommendation_category",

            "recommended_specialist",

            "recommended_next_step",

            "follow_up_category",

            "urgency_category",

            "descriptive_size_category"
        ],

        "interpretation_limit":
            "Gemini may explain these outputs but must not override them."
    },

    "who_grade_classifier": {

        "status":
            "EXPERIMENTAL_ONLY",

        "description":
            "Step 8A/8B WHO-grade classifier.",

        "allowed_use":
            "Research analysis only.",

        "clinical_use":
            False,

        "reason":
            "Cross-validation showed insufficient performance."
    }
}

# =============================================================================
# GEMINI PROHIBITED CLAIMS
# =============================================================================

prohibited_claims = [

    "definitive diagnosis from segmentation alone",

    "definitive tumor grade when grade is unavailable",

    "specific medication recommendation",

    "drug dosage",

    "drug frequency",

    "drug duration",

    "autonomous treatment plan",

    "autonomous surgery recommendation",

    "guaranteed prognosis",

    "guaranteed clinical outcome",

    "unsupported emergency classification",

    "invented patient history",

    "invented laboratory results",

    "invented pathology",

    "invented imaging findings",

    "invented clinical measurements"
]

# =============================================================================
# REQUIRED DISCLOSURES
# =============================================================================

required_disclosures = [

    "This is a research decision-support/reporting system.",

    "Segmentation does not establish a definitive diagnosis.",

    "The report is not a prescription.",

    "Medication and dosage are not generated.",

    "Clinical interpretation requires qualified healthcare-professional review.",

    "Missing information must be explicitly identified."
]

# =============================================================================
# GEMINI SYSTEM PROMPT
# =============================================================================

gemini_system_prompt = r"""
You are the language-generation component of a research
clinical decision-support and reporting system.

Your job is to convert STRUCTURED, ALREADY-VALIDATED information
into a clear clinical-style report.

You are NOT the diagnostic authority.

RULES:

1. Use only information contained in the supplied structured input.

2. Never invent missing patient information.

3. Never convert a segmentation result into a definitive diagnosis.

4. Treat Model 4A measurements as descriptive image-analysis findings.

5. If tumor type is supplied as an externally established diagnosis,
   report it as supplied and do not claim that you independently
   diagnosed it.

6. Model 5 deterministic rule-engine outputs must be preserved.

7. Do not override the rule engine.

8. The experimental WHO-grade classifier must never be presented
   as a clinically reliable grade predictor.

9. Never generate a medication.

10. Never generate drug dosage, frequency, or duration.

11. Never generate an autonomous treatment plan.

12. Never invent pathology, laboratory values, symptoms,
    imaging findings, or clinical history.

13. Clearly identify missing information.

14. Recommendations must remain at the category level,
    such as specialist review, radiology review,
    neurological evaluation, or endocrine evaluation.

15. Do not claim that a patient needs emergency treatment unless
    the supplied structured data explicitly supports such a statement
    and the rule engine has assigned that category.

16. Always state that qualified healthcare-professional review
    is required.

REPORT STRUCTURE:

A. Input summary
B. Segmentation findings
C. Tumor measurements
D. Clinical context
E. Rule-engine recommendation categories
F. Missing information
G. Limitations
H. Safety statement

Do not add unsupported sections.
"""

# =============================================================================
# STRUCTURED INPUT CONTRACT
# =============================================================================

gemini_input_schema = {

    "patient": {

        "patient_id":
            None,

        "age":
            None,

        "sex":
            None
    },

    "diagnosis_context": {

        "tumor_type":
            None,

        "known_diagnosis":
            None,

        "diagnosis_source":
            None
    },

    "model4a": {

        "tumor_detected":
            None,

        "tumor_area_pixels":
            None,

        "tumor_area_percent":
            None,

        "tumor_width_pixels":
            None,

        "tumor_height_pixels":
            None,

        "centroid_x":
            None,

        "centroid_y":
            None,

        "boundary_pixels":
            None,

        "bounding_box":
            None,

        "segmentation_confidence":
            None
    },

    "clinical_context": {

        "symptoms":
            None,

        "neurological_symptoms":
            None,

        "hormone_pattern":
            None,

        "previous_treatment":
            None
    },

    "model5_rules": {

        "recommendation_category":
            None,

        "recommended_specialist":
            [],

        "recommended_next_step":
            [],

        "follow_up_category":
            None,

        "urgency_category":
            None,

        "descriptive_size_category":
            None
    },

    "experimental_outputs": {

        "who_grade_prediction":
            None,

        "enabled_for_clinical_use":
            False
    }
}

# =============================================================================
# OUTPUT CONTRACT
# =============================================================================

gemini_output_schema = {

    "report_title":
        None,

    "input_summary":
        "",

    "segmentation_findings":
        "",

    "tumor_measurements":
        {},

    "clinical_context":
        "",

    "recommendation_summary":
        "",

    "recommended_specialist":
        [],

    "recommended_next_step":
        [],

    "follow_up_category":
        None,

    "missing_information":
        [],

    "limitations":
        [],

    "safety_statement":
        "",

    "medication":
        None,

    "dosage":
        None,

    "frequency":
        None,

    "duration":
        None
}

# =============================================================================
# OUTPUT SAFETY VALIDATION
# =============================================================================

print()
print("=" * 80)
print("VALIDATING GEMINI CONTRACT")
print("=" * 80)

errors = []

# Medication must remain null
for field in [
    "medication",
    "dosage",
    "frequency",
    "duration"
]:

    if gemini_output_schema[field] is not None:

        errors.append(
            f"{field} must remain None."
        )

# Clinical grade model disabled
if (
    gemini_input_schema[
        "experimental_outputs"
    ][
        "enabled_for_clinical_use"
    ]
):

    errors.append(
        "Experimental WHO-grade classifier cannot be enabled clinically."
    )

# Check required safety statements
for statement in required_disclosures:

    if not statement:

        errors.append(
            "Empty required disclosure."
        )

if errors:

    print("❌ CONTRACT VALIDATION FAILED")

    for error in errors:

        print(
            " -",
            error
        )

    raise RuntimeError(
        "Gemini contract validation failed."
    )

print(
    "✅ Input contract valid"
)

print(
    "✅ Output contract valid"
)

print(
    "✅ Medication generation blocked"
)

print(
    "✅ Dosage generation blocked"
)

print(
    "✅ Experimental WHO-grade output restricted"
)

# =============================================================================
# SAVE GEMINI CONTRACT
# =============================================================================

CONTRACT_PATH = (
    KNOWLEDGE_DIR /
    "model5_gemini_report_contract_v1.json"
)

contract = {

    "metadata": {

        "version":
            "1.0",

        "created":
            datetime.now().isoformat(),

        "status":
            "REQUIRES_CLINICAL_VALIDATION"
    },

    "source_policy":
        source_policy,

    "prohibited_claims":
        prohibited_claims,

    "required_disclosures":
        required_disclosures,

    "system_prompt":
        gemini_system_prompt,

    "input_schema":
        gemini_input_schema,

    "output_schema":
        gemini_output_schema
}

with open(
    CONTRACT_PATH,
    "w"
) as f:

    json.dump(
        contract,
        f,
        indent=2
    )

# =============================================================================
# SAVE AUDIT
# =============================================================================

audit = {

    "timestamp":
        datetime.now().isoformat(),

    "step":
        "9C",

    "knowledge_base":
        str(KNOWLEDGE_PATH),

    "gemini_contract":
        str(CONTRACT_PATH),

    "model4a_output_allowed":
        True,

    "clinical_information_allowed":
        True,

    "rule_engine_output_allowed":
        True,

    "who_grade_classifier_clinical_use":
        False,

    "medication_generation":
        False,

    "dosage_generation":
        False,

    "autonomous_treatment":
        False,

    "required_clinician_review":
        True,

    "validation_status":
        "PASSED",

    "clinical_validation_status":
        "REQUIRES_CLINICAL_VALIDATION"
}

AUDIT_PATH = (
    AUDIT_DIR /
    "step9c_gemini_contract_audit.json"
)

with open(
    AUDIT_PATH,
    "w"
) as f:

    json.dump(
        audit,
        f,
        indent=2
    )

# =============================================================================
# SAVE HUMAN-READABLE PROMPT
# =============================================================================

PROMPT_PATH = (
    KNOWLEDGE_DIR /
    "model5_gemini_system_prompt_v1.txt"
)

with open(
    PROMPT_PATH,
    "w"
) as f:

    f.write(
        gemini_system_prompt.strip()
    )

# =============================================================================
# FINAL
# =============================================================================

print()
print("=" * 80)
print("MODEL 5 - STEP 9C COMPLETE")
print("=" * 80)

print()
print("Knowledge-source policy:")
print("✅ CREATED")

print()
print("Gemini input contract:")
print("✅ CREATED")

print()
print("Gemini output contract:")
print("✅ CREATED")

print()
print("Prohibited clinical claims:")
print(
    len(prohibited_claims)
)

print()
print("Medication generation:")
print("❌ BLOCKED")

print()
print("Dosage generation:")
print("❌ BLOCKED")

print()
print("WHO-grade classifier clinical use:")
print("❌ BLOCKED")

print()
print("Gemini system prompt:")
print(
    PROMPT_PATH
)

print()
print("Gemini contract:")
print(
    CONTRACT_PATH
)

print()
print("Audit:")
print(
    AUDIT_PATH
)

print()
print("=" * 80)
print("NEXT → STEP 10")
print("END-TO-END REPORT GENERATOR + GEMINI INTEGRATION")
print("=" * 80)

================================================================================
MODEL 5 - STEP 9C
CLINICAL KNOWLEDGE SOURCE AUDIT + GEMINI PROMPT CONTRACT
================================================================================

Knowledge base loaded:
/content/drive/MyDrive/Model5/knowledge/model5_clinical_rules_v1.json

================================================================================
VALIDATING GEMINI CONTRACT
================================================================================
✅ Input contract valid
✅ Output contract valid
✅ Medication generation blocked
✅ Dosage generation blocked
✅ Experimental WHO-grade output restricted

================================================================================
MODEL 5 - STEP 9C COMPLETE
================================================================================

Knowledge-source policy:
✅ CREATED

Gemini input contract:
✅ CREATED

Gemini output contract:
✅ CREATED

Prohibited clinical claims:
16

Medication generation:
❌ BLOCKED

Dosage generation:
❌ BLOCKED

WHO-grade classifier clinical use:
❌ BLOCKED

Gemini system prompt:
/content/drive/MyDrive/Model5/knowledge/model5_gemini_system_prompt_v1.txt

Gemini contract:
/content/drive/MyDrive/Model5/knowledge/model5_gemini_report_contract_v1.json

Audit:
/content/drive/MyDrive/Model5/audit/step9c_gemini_contract_audit.json

================================================================================
NEXT → STEP 10
END-TO-END REPORT GENERATOR + GEMINI INTEGRATION
================================================================================

In [21]:
# =============================================================================
# MODEL 5 - STEP 10
# END-TO-END REPORT GENERATOR + GEMINI INTEGRATION
# =============================================================================

import os
import json
import re
from pathlib import Path
from datetime import datetime

print("=" * 80)
print("MODEL 5 - STEP 10")
print("END-TO-END REPORT GENERATOR + GEMINI INTEGRATION")
print("=" * 80)

# =============================================================================
# PATHS
# =============================================================================

ROOT = Path("/content/drive/MyDrive/Model5")

KNOWLEDGE_DIR = ROOT / "knowledge"
RESULT_DIR = ROOT / "results"
REPORT_DIR = ROOT / "reports"
AUDIT_DIR = ROOT / "audit"

for directory in [
    KNOWLEDGE_DIR,
    RESULT_DIR,
    REPORT_DIR,
    AUDIT_DIR
]:
    directory.mkdir(
        parents=True,
        exist_ok=True
    )

KNOWLEDGE_PATH = (
    KNOWLEDGE_DIR /
    "model5_clinical_rules_v1.json"
)

CONTRACT_PATH = (
    KNOWLEDGE_DIR /
    "model5_gemini_report_contract_v1.json"
)

PROMPT_PATH = (
    KNOWLEDGE_DIR /
    "model5_gemini_system_prompt_v1.txt"
)

# =============================================================================
# LOAD KNOWLEDGE
# =============================================================================

print()
print("=" * 80)
print("LOADING MODEL 5 KNOWLEDGE")
print("=" * 80)

if not KNOWLEDGE_PATH.exists():
    raise FileNotFoundError(
        f"Knowledge base missing:\n{KNOWLEDGE_PATH}"
    )

if not CONTRACT_PATH.exists():
    raise FileNotFoundError(
        f"Gemini contract missing:\n{CONTRACT_PATH}"
    )

with open(KNOWLEDGE_PATH, "r") as f:
    knowledge = json.load(f)

with open(CONTRACT_PATH, "r") as f:
    gemini_contract = json.load(f)

if PROMPT_PATH.exists():

    with open(PROMPT_PATH, "r") as f:
        gemini_system_prompt = f.read()

else:

    gemini_system_prompt = gemini_contract[
        "system_prompt"
    ]

print("✅ Knowledge base loaded")
print("✅ Gemini contract loaded")
print("✅ Gemini prompt loaded")

# =============================================================================
# SAFETY CONFIGURATION
# =============================================================================

print()
print("=" * 80)
print("SAFETY CONFIGURATION")
print("=" * 80)

FORBIDDEN_OUTPUT_FIELDS = {
    "medication",
    "specific_medication",
    "drug_name",
    "dosage",
    "drug_dosage",
    "frequency",
    "drug_frequency",
    "duration",
    "drug_duration"
}

FORBIDDEN_TERMS = [
    "prescribe",
    "prescription",
    "take ",
    "tablet",
    "capsule",
    "mg",
    "milligram",
    "medication",
    "drug dosage",
    "drug frequency",
    "drug duration"
]

print("Prescription generation : DISABLED")
print("Medication generation   : DISABLED")
print("Dosage generation       : DISABLED")
print("Autonomous treatment    : DISABLED")
print("Clinician review        : REQUIRED")

# =============================================================================
# CORRECTED RULE ENGINE
# =============================================================================

print()
print("=" * 80)
print("INITIALIZING CORRECTED RULE ENGINE")
print("=" * 80)


class Model5FinalRuleEngine:

    def __init__(
        self,
        knowledge_base
    ):

        self.kb = knowledge_base

        self.tumor_knowledge = (
            knowledge_base[
                "tumor_knowledge"
            ]
        )

        self.measurement_rules = (
            knowledge_base[
                "measurement_rules"
            ]
        )

    # -------------------------------------------------------------------------
    # Clean number
    # -------------------------------------------------------------------------

    @staticmethod
    def clean_number(value):

        if value is None:
            return None

        try:
            value = float(value)
        except:
            return None

        if value != value:
            return None

        return value

    # -------------------------------------------------------------------------
    # Tumor type
    # -------------------------------------------------------------------------

    def normalize_tumor_type(
        self,
        tumor_type
    ):

        if tumor_type is None:
            return "unknown"

        tumor_type = str(
            tumor_type
        ).lower().strip()

        if tumor_type not in self.tumor_knowledge:
            return "unknown"

        return tumor_type

    # -------------------------------------------------------------------------
    # Descriptive size
    # -------------------------------------------------------------------------

    def size_category(
        self,
        area_pixels
    ):

        area = self.clean_number(
            area_pixels
        )

        if area is None or area <= 0:
            return "not_available"

        if area < 250:
            return "very_small"

        if area < 750:
            return "small"

        if area < 1500:
            return "moderate"

        return "large"

    # -------------------------------------------------------------------------
    # FINAL EVALUATION
    # -------------------------------------------------------------------------

    def evaluate(
        self,
        tumor_type=None,
        tumor_detected=False,
        area_pixels=None,
        area_percent=None,
        width_pixels=None,
        height_pixels=None,
        centroid_x=None,
        centroid_y=None,
        boundary_pixels=None,
        confidence=None,
        age=None,
        sex=None,
        who_grade=None,
        known_diagnosis=None,
        symptoms=None,
        neurological_symptoms=None,
        hormone_pattern=None,
        previous_treatment=None
    ):

        tumor_key = self.normalize_tumor_type(
            tumor_type
        )

        tumor_info = self.tumor_knowledge[
            tumor_key
        ]

        tumor_detected = bool(
            tumor_detected
        )

        # ---------------------------------------------------------------------
        # IMPORTANT CORRECTION
        #
        # If Model 4A does not detect a segmented lesion, do NOT automatically
        # issue tumor-specific specialist recommendations.
        # ---------------------------------------------------------------------

        if tumor_detected:

            recommendation_category = (
                "segmented_tumor_present"
            )

            recommended_specialist = (
                tumor_info[
                    "specialist_categories"
                ]
            )

            recommended_next_step = list(
                dict.fromkeys(
                    [
                        "specialist_review"
                    ]
                    +
                    tumor_info[
                        "evaluation_categories"
                    ]
                )
            )

            follow_up_category = (
                "specialist_determined"
            )

            urgency_category = (
                "not_assigned_without_clinical_context"
            )

        else:

            recommendation_category = (
                "no_segmented_tumor_detected"
            )

            recommended_specialist = []

            recommended_next_step = [
                "clinical_and_radiological_correlation"
            ]

            follow_up_category = (
                "clinician_determined"
            )

            urgency_category = (
                "not_assigned_by_model"
            )

        report = {

            "report_version": "1.0",

            "generated_at":
                datetime.now().isoformat(),

            "input_summary": {

                "tumor_type":
                    tumor_key,

                "known_diagnosis":
                    known_diagnosis,

                "age":
                    self.clean_number(age),

                "sex":
                    sex
            },

            "segmentation": {

                "tumor_detected":
                    tumor_detected,

                "area_pixels":
                    self.clean_number(
                        area_pixels
                    ),

                "area_percent":
                    self.clean_number(
                        area_percent
                    ),

                "width_pixels":
                    self.clean_number(
                        width_pixels
                    ),

                "height_pixels":
                    self.clean_number(
                        height_pixels
                    ),

                "centroid": {

                    "x":
                        self.clean_number(
                            centroid_x
                        ),

                    "y":
                        self.clean_number(
                            centroid_y
                        )
                },

                "boundary_pixels":
                    self.clean_number(
                        boundary_pixels
                    ),

                "confidence":
                    self.clean_number(
                        confidence
                    )
            },

            "descriptive_size_category":
                self.size_category(
                    area_pixels
                ),

            "clinical_context": {

                "symptoms":
                    symptoms,

                "neurological_symptoms":
                    neurological_symptoms,

                "hormone_pattern":
                    hormone_pattern,

                "previous_treatment":
                    previous_treatment,

                "who_grade":
                    self.clean_number(
                        who_grade
                    )
            },

            "recommendation": {

                "recommendation_category":
                    recommendation_category,

                "recommended_specialist":
                    recommended_specialist,

                "recommended_next_step":
                    recommended_next_step,

                "follow_up_category":
                    follow_up_category,

                "urgency_category":
                    urgency_category
            },

            "limitations": [

                "Model 4A segmentation is descriptive image analysis.",

                "Segmentation does not establish a definitive diagnosis.",

                "Tumor type must come from an established diagnosis "
                "or validated external source.",

                "Descriptive size categories are not clinical severity "
                "classifications.",

                "Clinical decisions require qualified healthcare "
                "professional review.",

                "The experimental WHO-grade classifier is not used "
                "for clinical decision-making.",

                "No medication, dosage, frequency, or treatment plan "
                "is generated."
            ],

            "safety": {

                "not_a_diagnosis":
                    True,

                "not_a_prescription":
                    True,

                "clinician_review_required":
                    True
            }
        }

        return report


engine = Model5FinalRuleEngine(
    knowledge
)

print("✅ Corrected rule engine initialized")

# =============================================================================
# BUILD TEST INPUT
# =============================================================================

print()
print("=" * 80)
print("BUILDING END-TO-END TEST CASE")
print("=" * 80)

# This simulates the exact kind of information Model 4A will eventually provide.

test_input = {

    "patient": {

        "patient_id":
            "DEMO_001",

        "age":
            55,

        "sex":
            "female"
    },

    "diagnosis_context": {

        "tumor_type":
            "meningioma",

        "known_diagnosis":
            "meningioma",

        "diagnosis_source":
            "externally_established"
    },

    "model4a": {

        "tumor_detected":
            True,

        "tumor_area_pixels":
            1765,

        "tumor_area_percent":
            2.6932,

        "tumor_width_pixels":
            52,

        "tumor_height_pixels":
            52,

        "centroid_x":
            131.44,

        "centroid_y":
            52.90,

        "boundary_pixels":
            155,

        "bounding_box": {

            "x_min": 107,
            "y_min": 29,
            "x_max": 158,
            "y_max": 80
        },

        "segmentation_confidence":
            0.9939
    },

    "clinical_context": {

        "symptoms":
            None,

        "neurological_symptoms":
            None,

        "hormone_pattern":
            None,

        "previous_treatment":
            None
    },

    "experimental_outputs": {

        "who_grade_prediction":
            None,

        "enabled_for_clinical_use":
            False
    }
}

# =============================================================================
# RUN RULE ENGINE
# =============================================================================

structured_report = engine.evaluate(

    tumor_type=
        test_input[
            "diagnosis_context"
        ][
            "tumor_type"
        ],

    tumor_detected=
        test_input[
            "model4a"
        ][
            "tumor_detected"
        ],

    area_pixels=
        test_input[
            "model4a"
        ][
            "tumor_area_pixels"
        ],

    area_percent=
        test_input[
            "model4a"
        ][
            "tumor_area_percent"
        ],

    width_pixels=
        test_input[
            "model4a"
        ][
            "tumor_width_pixels"
        ],

    height_pixels=
        test_input[
            "model4a"
        ][
            "tumor_height_pixels"
        ],

    centroid_x=
        test_input[
            "model4a"
        ][
            "centroid_x"
        ],

    centroid_y=
        test_input[
            "model4a"
        ][
            "centroid_y"
        ],

    boundary_pixels=
        test_input[
            "model4a"
        ][
            "boundary_pixels"
        ],

    confidence=
        test_input[
            "model4a"
        ][
            "segmentation_confidence"
        ],

    age=
        test_input[
            "patient"
        ][
            "age"
        ],

    sex=
        test_input[
            "patient"
        ][
            "sex"
        ],

    known_diagnosis=
        test_input[
            "diagnosis_context"
        ][
            "known_diagnosis"
        ],

    symptoms=
        test_input[
            "clinical_context"
        ][
            "symptoms"
        ],

    neurological_symptoms=
        test_input[
            "clinical_context"
        ][
            "neurological_symptoms"
        ],

    hormone_pattern=
        test_input[
            "clinical_context"
        ][
            "hormone_pattern"
        ],

    previous_treatment=
        test_input[
            "clinical_context"
        ][
            "previous_treatment"
        ]
)

print(
    json.dumps(
        structured_report,
        indent=2
    )
)

# =============================================================================
# CREATE GEMINI PAYLOAD
# =============================================================================

print()
print("=" * 80)
print("CREATING GEMINI PAYLOAD")
print("=" * 80)

gemini_payload = {

    "patient": test_input["patient"],

    "diagnosis_context":
        test_input[
            "diagnosis_context"
        ],

    "model4a":
        test_input[
            "model4a"
        ],

    "clinical_context":
        test_input[
            "clinical_context"
        ],

    "model5_rules":
        structured_report[
            "recommendation"
        ],

    "descriptive_size_category":
        structured_report[
            "descriptive_size_category"
        ],

    "experimental_outputs": {

        "who_grade_prediction":
            None,

        "enabled_for_clinical_use":
            False
    }
}

print(
    "✅ Gemini payload constructed"
)

# =============================================================================
# GEMINI API KEY
# =============================================================================

print()
print("=" * 80)
print("CHECKING GEMINI API CONFIGURATION")
print("=" * 80)

GEMINI_API_KEY = os.environ.get(
    "GEMINI_API_KEY"
)

if not GEMINI_API_KEY:

    print(
        "⚠️ GEMINI_API_KEY not found."
    )

    print()
    print(
        "The local end-to-end pipeline will still be tested."
    )

    print(
        "Gemini API call will be skipped."
    )

    gemini_available = False

else:

    print(
        "✅ GEMINI_API_KEY detected"
    )

    gemini_available = True

# =============================================================================
# LOCAL PAYLOAD VALIDATION
# =============================================================================

print()
print("=" * 80)
print("VALIDATING GEMINI INPUT")
print("=" * 80)

payload_text = json.dumps(
    gemini_payload
).lower()

for forbidden in [
    "medication",
    "dosage",
    "frequency",
    "duration"
]:

    # These are allowed only in the safety/contract context,
    # not as generated clinical recommendations.
    pass

required_payload_sections = [
    "patient",
    "diagnosis_context",
    "model4a",
    "clinical_context",
    "model5_rules"
]

for section in required_payload_sections:

    if section not in gemini_payload:

        raise RuntimeError(
            f"Missing Gemini payload section: {section}"
        )

print(
    "✅ Required sections present"
)

print(
    "✅ Payload validation passed"
)

# =============================================================================
# SAVE PAYLOAD
# =============================================================================

PAYLOAD_PATH = (
    RESULT_DIR /
    "step10_gemini_input_payload.json"
)

with open(
    PAYLOAD_PATH,
    "w"
) as f:

    json.dump(
        gemini_payload,
        f,
        indent=2
    )

# =============================================================================
# GEMINI CALL
# =============================================================================

gemini_response = None
gemini_raw_text = None

if gemini_available:

    print()
    print("=" * 80)
    print("CALLING GEMINI")
    print("=" * 80)

    try:

        # ---------------------------------------------------------------------
        # Import Google GenAI SDK
        # ---------------------------------------------------------------------

        from google import genai

        client = genai.Client(
            api_key=GEMINI_API_KEY
        )

        # ---------------------------------------------------------------------
        # Prompt
        # ---------------------------------------------------------------------

        user_prompt = f"""
Generate a structured clinical-style research report from the
validated information below.

Do not add information that is not present.

Do not diagnose the patient independently.

Do not prescribe medication.

Do not provide drug names, dosage, frequency, or duration.

Do not create an autonomous treatment plan.

Preserve the Model 5 rule-engine recommendation categories.

If information is missing, explicitly say it is missing.

Return JSON only.

VALIDATED INPUT:

{json.dumps(
    gemini_payload,
    indent=2
)}

REQUIRED OUTPUT STRUCTURE:

{json.dumps(
    gemini_contract[
        "output_schema"
    ],
    indent=2
)}
"""

        response = client.models.generate_content(

            model="gemini-2.5-flash",

            contents=user_prompt,

            config={
                "system_instruction":
                    gemini_system_prompt,

                "temperature":
                    0.1,

                "response_mime_type":
                    "application/json"
            }
        )

        gemini_raw_text = (
            response.text
        )

        # ---------------------------------------------------------------------
        # Parse JSON
        # ---------------------------------------------------------------------

        try:

            gemini_response = json.loads(
                gemini_raw_text
            )

        except json.JSONDecodeError:

            # Attempt extraction if the model wrapped JSON in markdown.
            match = re.search(
                r"\{.*\}",
                gemini_raw_text,
                re.DOTALL
            )

            if not match:

                raise RuntimeError(
                    "Gemini response was not valid JSON."
                )

            gemini_response = json.loads(
                match.group(0)
            )

        print(
            "✅ Gemini response received"
        )

    except Exception as e:

        print()
        print(
            "⚠️ Gemini call failed:"
        )

        print(
            type(e).__name__,
            str(e)
        )

        print()
        print(
            "The structured Model 5 report remains available."
        )

# =============================================================================
# GEMINI OUTPUT SAFETY VALIDATION
# =============================================================================

gemini_validation = {

    "gemini_called":
        gemini_response is not None,

    "json_valid":
        gemini_response is not None,

    "forbidden_content_detected":
        False,

    "validation_status":
        "NOT_RUN"
}

if gemini_response is not None:

    print()
    print("=" * 80)
    print("VALIDATING GEMINI OUTPUT")
    print("=" * 80)

    output_text = json.dumps(
        gemini_response
    ).lower()

    detected_forbidden = []

    # Check explicit output fields first.
    for field in FORBIDDEN_OUTPUT_FIELDS:

        if field in gemini_response:

            value = gemini_response[field]

            if value not in [
                None,
                "",
                [],
                {}
            ]:

                detected_forbidden.append(
                    field
                )

    # Check suspicious medication-related language.
    #
    # "treatment" itself is intentionally NOT blocked because the
    # report may say that treatment decisions require clinicians.
    suspicious_terms = [
        "prescribe",
        "prescription",
        "dosage",
        "dose of",
        "medication:",
        "drug:",
        "tablet",
        "capsule"
    ]

    for term in suspicious_terms:

        if term in output_text:

            detected_forbidden.append(
                term
            )

    detected_forbidden = list(
        dict.fromkeys(
            detected_forbidden
        )
    )

    if detected_forbidden:

        gemini_validation[
            "forbidden_content_detected"
        ] = True

        gemini_validation[
            "detected_items"
        ] = detected_forbidden

        gemini_validation[
            "validation_status"
        ] = "FAILED"

        print(
            "❌ Gemini safety validation FAILED"
        )

        print(
            "Detected:",
            detected_forbidden
        )

    else:

        gemini_validation[
            "validation_status"
        ] = "PASSED"

        print(
            "✅ Gemini safety validation PASSED"
        )

# =============================================================================
# SAVE STRUCTURED REPORT
# =============================================================================

STRUCTURED_REPORT_PATH = (
    REPORT_DIR /
    "step10_structured_report.json"
)

with open(
    STRUCTURED_REPORT_PATH,
    "w"
) as f:

    json.dump(
        structured_report,
        f,
        indent=2
    )

# =============================================================================
# SAVE GEMINI REPORT
# =============================================================================

GEMINI_REPORT_PATH = (
    REPORT_DIR /
    "step10_gemini_report.json"
)

if gemini_response is not None:

    with open(
        GEMINI_REPORT_PATH,
        "w"
    ) as f:

        json.dump(
            gemini_response,
            f,
            indent=2
        )

# =============================================================================
# SAVE RAW GEMINI RESPONSE
# =============================================================================

RAW_RESPONSE_PATH = (
    AUDIT_DIR /
    "step10_gemini_raw_response.txt"
)

if gemini_raw_text is not None:

    with open(
        RAW_RESPONSE_PATH,
        "w"
    ) as f:

        f.write(
            gemini_raw_text
        )

# =============================================================================
# FINAL AUDIT
# =============================================================================

AUDIT_PATH = (
    AUDIT_DIR /
    "step10_end_to_end_integration_audit.json"
)

audit = {

    "timestamp":
        datetime.now().isoformat(),

    "step":
        "10",

    "architecture":
        "Model4A -> Model5 Rule Engine -> Gemini Report Generator",

    "model4a_input":
        True,

    "rule_engine":
        True,

    "gemini_available":
        gemini_available,

    "gemini_called":
        gemini_response is not None,

    "gemini_validation":
        gemini_validation,

    "prescription_generation":
        False,

    "medication_generation":
        False,

    "dosage_generation":
        False,

    "autonomous_treatment":
        False,

    "experimental_who_grade_clinical_use":
        False,

    "clinician_review_required":
        True,

    "structured_report":
        str(
            STRUCTURED_REPORT_PATH
        ),

    "gemini_report":
        (
            str(GEMINI_REPORT_PATH)
            if gemini_response is not None
            else None
        ),

    "gemini_input":
        str(PAYLOAD_PATH),

    "status":
        (
            "PASSED"
            if (
                gemini_response is None
                or
                gemini_validation[
                    "validation_status"
                ] == "PASSED"
            )
            else "FAILED"
        )
}

with open(
    AUDIT_PATH,
    "w"
) as f:

    json.dump(
        audit,
        f,
        indent=2
    )

# =============================================================================
# FINAL OUTPUT
# =============================================================================

print()
print("=" * 80)
print("MODEL 5 - STEP 10 COMPLETE")
print("=" * 80)

print()
print("End-to-end rule pipeline:")
print("✅ COMPLETE")

print()
print("Corrected no-tumor specialist logic:")
print("✅ COMPLETE")

print()
print("Structured report:")
print(
    STRUCTURED_REPORT_PATH
)

print()
print("Gemini API available:")
print(
    "YES" if gemini_available else "NO"
)

print()
print("Gemini report:")
print(
    GEMINI_REPORT_PATH
    if gemini_response is not None
    else "NOT GENERATED"
)

print()
print("Gemini input:")
print(
    PAYLOAD_PATH
)

print()
print("Audit:")
print(
    AUDIT_PATH
)

print()
print("Prescription:")
print("❌ DISABLED")

print()
print("Medication:")
print("❌ DISABLED")

print()
print("Dosage:")
print("❌ DISABLED")

print()
print("Clinical validation:")
print("⚠️ REQUIRED")

print()
print("=" * 80)

if gemini_response is None:

    print(
        "NEXT → CONFIGURE GEMINI_API_KEY AND RUN STEP 10 AGAIN"
    )

else:

    print(
        "NEXT → STEP 11"
    )

    print(
        "END-TO-END TEST WITH REAL MODEL 4A OUTPUT"
    )

print("=" * 80)

================================================================================
MODEL 5 - STEP 10
END-TO-END REPORT GENERATOR + GEMINI INTEGRATION
================================================================================

================================================================================
LOADING MODEL 5 KNOWLEDGE
================================================================================
✅ Knowledge base loaded
✅ Gemini contract loaded
✅ Gemini prompt loaded

================================================================================
SAFETY CONFIGURATION
================================================================================
Prescription generation : DISABLED
Medication generation   : DISABLED
Dosage generation       : DISABLED
Autonomous treatment    : DISABLED
Clinician review        : REQUIRED

================================================================================
INITIALIZING CORRECTED RULE ENGINE
================================================================================
✅ Corrected rule engine initialized

================================================================================
BUILDING END-TO-END TEST CASE
================================================================================
{
  "report_version": "1.0",
  "generated_at": "2026-08-22T17:58:56.999927",
  "input_summary": {
    "tumor_type": "meningioma",
    "known_diagnosis": "meningioma",
    "age": 55.0,
    "sex": "female"
  },
  "segmentation": {
    "tumor_detected": true,
    "area_pixels": 1765.0,
    "area_percent": 2.6932,
    "width_pixels": 52.0,
    "height_pixels": 52.0,
    "centroid": {
      "x": 131.44,
      "y": 52.9
    },
    "boundary_pixels": 155.0,
    "confidence": 0.9939
  },
  "descriptive_size_category": "large",
  "clinical_context": {
    "symptoms": null,
    "neurological_symptoms": null,
    "hormone_pattern": null,
    "previous_treatment": null,
    "who_grade": null
  },
  "recommendation": {
    "recommendation_category": "segmented_tumor_present",
    "recommended_specialist": [
      "neurosurgery",
      "neuro_oncology"
    ],
    "recommended_next_step": [
      "specialist_review",
      "clinical_neurological_evaluation",
      "radiology_review"
    ],
    "follow_up_category": "specialist_determined",
    "urgency_category": "not_assigned_without_clinical_context"
  },
  "limitations": [
    "Model 4A segmentation is descriptive image analysis.",
    "Segmentation does not establish a definitive diagnosis.",
    "Tumor type must come from an established diagnosis or validated external source.",
    "Descriptive size categories are not clinical severity classifications.",
    "Clinical decisions require qualified healthcare professional review.",
    "The experimental WHO-grade classifier is not used for clinical decision-making.",
    "No medication, dosage, frequency, or treatment plan is generated."
  ],
  "safety": {
    "not_a_diagnosis": true,
    "not_a_prescription": true,
    "clinician_review_required": true
  }
}

================================================================================
CREATING GEMINI PAYLOAD
================================================================================
✅ Gemini payload constructed

================================================================================
CHECKING GEMINI API CONFIGURATION
================================================================================
⚠️ GEMINI_API_KEY not found.

The local end-to-end pipeline will still be tested.
Gemini API call will be skipped.

================================================================================
VALIDATING GEMINI INPUT
================================================================================
✅ Required sections present
✅ Payload validation passed

================================================================================
MODEL 5 - STEP 10 COMPLETE
================================================================================

End-to-end rule pipeline:
✅ COMPLETE

Corrected no-tumor specialist logic:
✅ COMPLETE

Structured report:
/content/drive/MyDrive/Model5/reports/step10_structured_report.json

Gemini API available:
NO

Gemini report:
NOT GENERATED

Gemini input:
/content/drive/MyDrive/Model5/results/step10_gemini_input_payload.json

Audit:
/content/drive/MyDrive/Model5/audit/step10_end_to_end_integration_audit.json

Prescription:
❌ DISABLED

Medication:
❌ DISABLED

Dosage:
❌ DISABLED

Clinical validation:
⚠️ REQUIRED

================================================================================
NEXT → CONFIGURE GEMINI_API_KEY AND RUN STEP 10 AGAIN
================================================================================

In [22]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

!ls -lah /content/drive/MyDrive/Model5
!find /content/drive/MyDrive/Model5 -maxdepth 2 -type f | head -50

Mounted at /content/drive
total 35K
drwx------ 2 root root 4.0K Aug 22 17:58 audit
drwx------ 2 root root 4.0K Aug 22 17:21 config
drwx------ 2 root root 4.0K Aug 22 17:21 data
drwx------ 2 root root 4.0K Aug 22 17:21 exports
drwx------ 2 root root 4.0K Aug 22 17:57 knowledge
drwx------ 2 root root 4.0K Aug 22 17:45 models
-rw------- 1 root root 1.3K Aug 22 17:21 README.md
drwx------ 2 root root 4.0K Aug 22 17:58 reports
drwx------ 2 root root 4.0K Aug 22 17:58 results
-rw------- 1 root root 1021 Aug 22 17:21 STORAGE_POLICY.txt
/content/drive/MyDrive/Model5/models/Model5_WHO_Grade_Classifier.joblib
/content/drive/MyDrive/Model5/results/model5_who_grade_test_predictions.csv
/content/drive/MyDrive/Model5/results/model5_feature_importance.csv
/content/drive/MyDrive/Model5/results/model5_step8b_cv_fold_results.csv
/content/drive/MyDrive/Model5/results/model5_step8b_cv_summary.csv
/content/drive/MyDrive/Model5/results/model5_step8b_oof_predictions.csv
/content/drive/MyDrive/Model5/results/step9a_rules_validation.json
/content/drive/MyDrive/Model5/results/step9b_sample_structured_reports.json
/content/drive/MyDrive/Model5/results/step9b_rule_engine_test_results.csv
/content/drive/MyDrive/Model5/results/step10_gemini_input_payload.json
/content/drive/MyDrive/Model5/reports/step10_structured_report.json
/content/drive/MyDrive/Model5/audit/step1_initialization_audit.json
/content/drive/MyDrive/Model5/audit/step9a_clinical_rules_audit.json
/content/drive/MyDrive/Model5/audit/step9b_rule_engine_audit.json
/content/drive/MyDrive/Model5/audit/step9c_gemini_contract_audit.json
/content/drive/MyDrive/Model5/audit/step10_end_to_end_integration_audit.json
/content/drive/MyDrive/Model5/knowledge/model5_clinical_rules_v1.json
/content/drive/MyDrive/Model5/knowledge/model5_gemini_report_contract_v1.json
/content/drive/MyDrive/Model5/knowledge/model5_gemini_system_prompt_v1.txt
/content/drive/MyDrive/Model5/config/model5_config.json
/content/drive/MyDrive/Model5/STORAGE_POLICY.txt
/content/drive/MyDrive/Model5/README.md

In [23]:
from pathlib import Path
import zipfile

ROOT = Path("/content/drive/MyDrive/Model5")
OUT = Path("/content/Model5_Final_Package.zip")

print("=" * 80)
print("CREATING MODEL 5 FINAL PACKAGE")
print("=" * 80)

if not ROOT.exists():
    raise FileNotFoundError(
        f"Model5 folder not found: {ROOT}"
    )

file_count = 0
total_bytes = 0

with zipfile.ZipFile(
    OUT,
    "w",
    compression=zipfile.ZIP_DEFLATED
) as z:

    for file in ROOT.rglob("*"):

        if not file.is_file():
            continue

        relative = file.relative_to(ROOT)

        # Do not include unnecessary temporary/raw data
        if any(
            part in {"raw", "temp", "__pycache__"}
            for part in relative.parts
        ):
            continue

        z.write(
            file,
            Path("Model5") / relative
        )

        file_count += 1
        total_bytes += file.stat().st_size

print()
print(f"Files packaged : {file_count}")
print(
    f"Source size    : "
    f"{total_bytes / (1024 * 1024):.2f} MB"
)

print()
print("Package created:")
print(OUT)

print()
print("=" * 80)
print("MODEL 5 PACKAGE READY")
print("=" * 80)

================================================================================
CREATING MODEL 5 FINAL PACKAGE
================================================================================

Files packaged : 36
Source size    : 2.95 MB

Package created:
/content/Model5_Final_Package.zip

================================================================================
MODEL 5 PACKAGE READY
================================================================================

In [24]:
from google.colab import files

files.download("/content/Model5_Final_Package.zip")